import {expect,it} from 'vitest';
import {readCrmCapabilityStartup,createCrmCapabilityRuntime} from '@fss/domain/crm/capabilityStartup.ts';
import {composeCrmCapabilities} from '../src/bootstrap/crmCapabilities.ts';
import {CRM_SUPPORTED_ASK_VERSIONS} from '@fss/domain/crm/capabilityAuthority.ts';
const route={region:'us-east-1' as const,endpointId:'bedrock-runtime.us-east-1.amazonaws.com' as const,modelVersion:'us.anthropic.claude-haiku-4-5-20251001-v1:0' as const,providerKey:'synthetic-crm',accessGrantVersion:'reviewed-crm-grant',dataHandlingVersion:'reviewed-crm-handling',fundingVerifiedUntil:'2099-01-01T00:00:00Z'};
const identity={implementationCommit:'a'.repeat(40),imageDigest:`sha256:${'b'.repeat(64)}`,side:'worker' as const,schemaVersion:88,gmailAvailable:false};
it('keeps startup absent/off without opening sessions or constructing hosted transports',async()=>{const configuration=readCrmCapabilityStartup({});const result=await composeCrmCapabilities({configuration,runtime:createCrmCapabilityRuntime(configuration,identity),openSession:async()=>{throw new Error('unexpected database');},loadSurface:async()=>{throw new Error('unexpected SDK');}});expect(configuration).toEqual({capture:false});expect(result.handlers).toEqual({});});
it('pins the reviewed region/profile and exact independent purpose bindings without activating configuration',async()=>{const configuration=readCrmCapabilityStartup({FSS_CRM_CAPABILITY_ADAPTERS:JSON.stringify({extraction:route,answer:route})});let constructed=0;let calls=0;const runtime=createCrmCapabilityRuntime(configuration,identity);const result=await composeCrmCapabilities({configuration,runtime,openSession:async()=>{throw new Error('no activation session');},loadSurface:async region=>{expect(region).toBe('us-east-1');constructed++;return {endpointId:route.endpointId,converse:async()=>{calls++;throw new Error('not invoked');}};}});expect(constructed).toBe(1);expect(calls).toBe(0);expect(result.handlers.crmExtraction?.adapter?.modelVersion).toBe(route.modelVersion);expect(result.handlers.crmExtraction?.allowControlledEvaluation).toBeUndefined();expect(result.handlers.crmExtraction?.verifyPurpose).toBeTypeOf('function');expect(result.handlers.crmExtraction?.revalidatePurpose).toBeTypeOf('function');expect(result.handlers.crmAskAnswers?.verifyPurpose).toBeTypeOf('function');const config={capability:'ask_answer' as const,workspaceId:'00000000-0000-4000-8000-000000000001',ownerUserId:'00000000-0000-4000-8000-000000000002',revision:1,purpose:'answer' as const,...route,...CRM_SUPPORTED_ASK_VERSIONS,evaluationFingerprint:'c'.repeat(64),dailyCeilingCents:10,monthlyCeilingCents:100,inputTokenPriceMicros:1,outputTokenPriceMicros:1};expect(runtime.adapterAvailable(config)).toBe(true);expect(runtime.adapterAvailable({...config,retrievalVersion:'semantic-untested'})).toBe(false);expect(runtime.adapterAvailable({...config,accessGrantVersion:'classifier-grant'})).toBe(false);});
it('rejects config flags that imply authority or silently substitute another provider endpoint',()=>{for(const input of [{enabled:true},{capture:true,approved:true},{extraction:{...route,region:'us-west-2'}},{answer:{...route,modelVersion:'global.anthropic.claude-haiku'}}])expect(()=>readCrmCapabilityStartup({FSS_CRM_CAPABILITY_ADAPTERS:JSON.stringify(input)})).toThrow('crm_capability_adapter_configuration_invalid');});
