import {beforeAll,afterAll,it,expect} from 'vitest';
import {createTestDatabase,type TestDatabase} from '@fss/domain/db/testing/testDatabase.ts';
import {seedTwoWorkspaces,type TwoWorkspaces} from '@fss/domain/test/db/support/fixtures.ts';
import {qualificationConfigureCommand} from '../src/tools/fss/qualificationConfigure.ts';
let db:TestDatabase,seed:TwoWorkspaces;
beforeAll(async()=>{db=await createTestDatabase();seed=await seedTwoWorkspaces(db.session);});afterAll(async()=>db.drop());
const launch={launchedBy:'arn:aws:iam::123456789012:user/operator',taskArn:'arn:aws:ecs:us-east-1:123456789012:task/cluster/abc'};
it('requires audited explicit evaluation and active ownership, preserving unrelated switches and quota',async()=>{
 const options={'--workspace-id':seed.alpha.workspaceId,'--enabled':'true'};
 expect(await qualificationConfigureCommand({session:db.session,options})).toMatchObject({ok:false,reason:'launcher_unknown'});
 expect(await qualificationConfigureCommand({session:db.session,options,launch})).toMatchObject({ok:false,reason:'evaluation_required'});
 const approved={...options,'--owner-user-id':seed.alpha.admin.userId,'--evaluation-sha256':'a'.repeat(64),'--reviewed-eligible':'3','--false-eligible':'0'};
 expect(await qualificationConfigureCommand({session:db.session,options:{...approved,'--owner-user-id':seed.beta.admin.userId},launch})).toMatchObject({ok:false,reason:'owner_inactive'});
 expect(await qualificationConfigureCommand({session:db.session,options:{...approved,'--false-eligible':'1'},launch})).toMatchObject({ok:false});
 expect(await qualificationConfigureCommand({session:db.session,options:approved,launch})).toMatchObject({ok:true});
 expect((await db.session.query('SELECT enabled,auto_admission_enabled,qualification_evaluation FROM sourcing_discovery_settings')).rows[0]).toMatchObject({enabled:false,auto_admission_enabled:true,qualification_evaluation:{policyVersion:'qualification-v1',reviewedEligible:3,falseEligible:0}});
 expect(await qualificationConfigureCommand({session:db.session,options:{...options,'--enabled':'false'},launch})).toMatchObject({ok:true});
 expect((await db.session.query('SELECT auto_admission_enabled,qualification_evaluation FROM sourcing_discovery_settings')).rows[0]).toMatchObject({auto_admission_enabled:false,qualification_evaluation:{reviewedEligible:3}});
 expect((await db.session.query('SELECT id FROM sourcing_search_account')).rows).toHaveLength(0);
});
it('requires a fresh explicit identity review, preserves CRM history, and retires the old association',async()=>{
 const {qualificationResolveIdentityCommand}=await import('../src/tools/fss/qualificationResolveIdentity.ts');
 const {saveCandidate}=await import('@fss/domain/sourcing/candidates.ts');
 const {requestQualification}=await import('@fss/domain/sourcing/qualificationStore.ts');
 const {recordSourcingFeedback}=await import('@fss/domain/sourcing/feedback.ts');
 const {repositoryContext,workspaceScope}=await import('@fss/domain/db/workspaceScope.ts');
 const {withTransaction}=await import('@fss/domain/db/queryable.ts');
 const {createFirm}=await import('@fss/domain/crm/firms.ts');const {addPhoneRoute}=await import('@fss/domain/crm/routes.ts');
 const ctx=repositoryContext(workspaceScope(seed.alpha.workspaceId,{kind:'user',role:'admin',userId:seed.alpha.admin.userId}),db.session);
 const candidate=await saveCandidate(ctx,{firmName:'Identity PM',website:'https://identity.example.test/',locality:'Dallas',region:'TX',signal:'fit_only',evidence:'Unknown',sourceUrl:'https://identity.example.test/',observedOn:'2026-10-01',preparedBy:'Fixture'});if(!candidate.ok)throw new Error(candidate.reason);
 const requested=await withTransaction(db.session,()=>requestQualification(ctx,{candidateId:candidate.value.id,expectedRevision:1}));if(!requested.ok)throw new Error(requested.reason);
 const firm=await withTransaction(db.session,()=>createFirm(ctx,{name:'Preserved CRM firm',assignedUserId:seed.alpha.admin.userId}));if(!firm.ok)throw new Error(firm.reason);
 const route=await withTransaction(db.session,()=>addPhoneRoute(ctx,{firmId:firm.value.id,e164:'+12145550199',source:'website'}));if(!route.ok)throw new Error(route.reason);
 await db.session.query('INSERT INTO sourcing_admissions(workspace_id,candidate_id,run_id,firm_id,route_id) VALUES($1,$2,$3,$4,$5)',[seed.alpha.workspaceId,candidate.value.id,requested.value.runId,firm.value.id,route.value.id]);
 await withTransaction(db.session,()=>recordSourcingFeedback(ctx,{candidateId:candidate.value.id,qualificationRunId:requested.value.runId,code:'wrong_firm'}));
 const options={'--workspace-id':seed.alpha.workspaceId,'--candidate-id':candidate.value.id,'--expected-revision':'1','--confirmed-identity':'true','--reason':'Human checked the candidate website and name.'};
 expect(await qualificationResolveIdentityCommand({session:db.session,options:{...options,'--expected-revision':'2'},launch})).toMatchObject({ok:false,reason:'candidate_changed'});
 expect(await qualificationResolveIdentityCommand({session:db.session,options,launch})).toMatchObject({ok:true,value:{revision:2,researchRequired:true}});
 expect((await db.session.query('SELECT id FROM firms WHERE id=$1',[firm.value.id])).rows).toHaveLength(1);
 expect((await db.session.query('SELECT firm_id FROM sourcing_admissions WHERE candidate_id=$1',[candidate.value.id])).rows).toHaveLength(0);
 expect((await db.session.query('SELECT state,reason FROM sourcing_qualification_runs WHERE id=$1',[requested.value.runId])).rows[0]).toEqual({state:'unavailable',reason:'identity_recheck_required'});
 expect(await qualificationResolveIdentityCommand({session:db.session,options,launch})).toMatchObject({ok:false,reason:'candidate_changed'});
 const next=await withTransaction(db.session,()=>requestQualification(ctx,{candidateId:candidate.value.id,expectedRevision:2}));expect(next).toMatchObject({ok:true});if(next.ok)expect(next.value.runId).not.toBe(requested.value.runId);
});
