import {afterAll,beforeAll,it,expect,vi} from 'vitest';
import {createTestDatabase,type TestDatabase} from '@fss/domain/db/testing/testDatabase.ts';
import {withTransaction} from '@fss/domain/db/queryable.ts';
import {repositoryContext,workspaceScope} from '@fss/domain/db/workspaceScope.ts';
import {seedTwoWorkspaces} from '@fss/domain/test/db/support/fixtures.ts';
import {saveCandidate,reviewCandidate} from '@fss/domain/sourcing/candidates.ts';
import {enqueueJob} from '@fss/domain/jobs/jobStore.ts';
import {HandlerRegistry} from '@fss/domain/jobs/handlerRegistry.ts';
import {runOnce} from '../src/runner/jobRunner.ts';
import {sourcingMonitorHandler,sourcingMonitorSource} from '../src/handlers/sourcingMonitor.ts';
import {sourcingCheckHandler} from '../src/handlers/sourcingCheck.ts';
import {registerHandlers,workerSourceFlags,workerDueWorkSources} from '../src/bootstrap/main.ts';
let db:TestDatabase;
beforeAll(async()=>{db=await createTestDatabase();});afterAll(async()=>{await db.drop();});
it('schedules one hourly sweep and runs a kept source check; disabled composition inserts nothing',async()=>{
 const seed=await seedTwoWorkspaces(db.session),ctx=repositoryContext(workspaceScope(seed.alpha.workspaceId,{kind:'system',component:'worker'}),db.session);
 const saved=await saveCandidate(ctx,{firmName:'PM',website:'https://example.test',locality:'Dallas',region:'TX',signal:'fit_only',evidence:'Maintenance',sourceUrl:'https://example.test/maintenance',observedOn:'2026-10-01',preparedBy:'Test'});if(!saved.ok)throw new Error('save');
 await reviewCandidate(ctx,{id:saved.value.id,expectedRevision:1,status:'kept'});
 await db.session.query("UPDATE sourcing_candidates SET next_source_check_at=now()-interval '1 minute'");
 const now=new Date().toISOString();expect(await sourcingMonitorSource(false).find(db.session,now)).toEqual([]);
 const source=sourcingMonitorSource(true);
 await withTransaction(db.session,async()=>{for(let i=0;i<2;i++)for(const job of await source.find(db.session,now))await enqueueJob(db.session,job);});
 expect((await db.session.query("SELECT id FROM jobs WHERE kind='sourcing.monitor'")).rows).toHaveLength(1);
 const fetchPages=vi.fn(async()=>({ok:false as const,costCents:0,failureCode:'fixture-unavailable'}));
 const registry=new HandlerRegistry().register(sourcingMonitorHandler());
 expect((await runOnce(db.session,{registry,owner:'monitor-test',limit:5})).failed).toBe(0);expect(fetchPages).not.toHaveBeenCalled();
 registry.register(sourcingCheckHandler({providerKey:'test',fetchPages}));
 await runOnce(db.session,{registry,owner:'monitor-test',limit:5});expect(fetchPages).toHaveBeenCalledTimes(1);
 expect(await source.find(db.session,now)).toEqual([]);
 const row=(await db.session.query<{source_check:{state:string};next_source_check_at:Date}>('SELECT source_check,next_source_check_at FROM sourcing_candidates')).rows[0]!;
 expect(row.source_check.state).toBe('unavailable');expect(row.next_source_check_at.getTime()).toBeGreaterThan(Date.now()+6*86400_000);
 expect((await db.session.query('SELECT id FROM firms')).rows).toHaveLength(0);
 const composition={classifier:undefined,mail:undefined,send:undefined,research:{pageFetch:{providerKey:'test',fetchPages}}};
 expect(registerHandlers(new HandlerRegistry(),composition).get('sourcing.monitor')).toBeDefined();
 expect(workerSourceFlags(composition).sourcing).toBe(true);
 expect(workerSourceFlags({...composition,research:undefined}).sourcing).toBe(false);
 expect(registerHandlers(new HandlerRegistry(),{...composition,research:undefined}).get('sourcing.monitor')).toBeUndefined();
 expect(workerDueWorkSources(workerSourceFlags(composition)).map(s=>s.name)).toContain('sourcing-monitor');
});
