import {readOperationalProgress} from './progressOperational.ts';
import {mailConversationSchema} from '@fss/contracts';
import {createHash} from 'node:crypto';
import type {RepositoryContext} from '../db/workspaceScope.ts';
import {readMailConversation,mailContextPredicate,type ExactMailSource} from '../mail/crmSources.ts';
import {lockIdentityContext,sourceContextPredicate,activeIdentityActor} from './identityAccess.ts';
import type {Queryable} from '../db/queryable.ts';
/** One canonical mail reference mapping for every displayed milestone. */
function sourceReference(workspaceId:string,source:Extract<Awaited<ReturnType<typeof readMailConversation>>,{state:'available'}>['source']){
 return {workspaceId,sourceId:source.sourceId,kind:'mail' as const,revision:source.sourceRevision,contentHash:source.contentHash,locator:null,speaker:null,occurredAt:source.occurredAt,observedAt:source.observedAt,completeness:source.completeness==='complete'?'complete' as const:'partial' as const,availability:'available' as const};
}
/** Membership authority is held before identity/copy locks, matching departure ordering. */
async function lockProgressActor(context:RepositoryContext){const actor=context.scope.actor;if(actor.kind!=='user')return false;const row=(await context.db.query<{role:string;status:string}>('SELECT role,status FROM workspace_memberships WHERE workspace_id=$1 AND user_id=$2 FOR SHARE',[context.scope.workspaceId,actor.userId])).rows[0];return row?.role===actor.role&&row.status==='active';}
/** Bounded exact conversation dependency. A later import creates a new key, never rebinds a job. */
export async function mailProgressDependency(db:Queryable,workspaceId:string,sourceId:string){
 const root=(await db.query<{mailbox_id:string;account_binding:string;provider_thread_id:string}>(`SELECT s.mailbox_id,s.account_binding,m.provider_thread_id FROM crm_mail_sources s JOIN mail_messages m ON m.workspace_id=s.workspace_id AND m.id=s.source_id WHERE s.workspace_id=$1 AND s.source_id=$2 AND s.availability='available'`,[workspaceId,sourceId])).rows[0];if(!root)return null;
 const sources=(await db.query<{source_id:string;source_revision:number;content_hash:string;participants:string[]}>(`SELECT s.source_id,s.source_revision,s.content_hash,s.participants FROM crm_mail_sources s JOIN mail_messages m ON m.workspace_id=s.workspace_id AND m.id=s.source_id WHERE s.workspace_id=$1 AND s.mailbox_id=$2 AND s.account_binding=$3 AND m.provider_thread_id=$4 AND s.availability='available' ORDER BY s.source_id LIMIT 101`,[workspaceId,root.mailbox_id,root.account_binding,root.provider_thread_id])).rows;if(sources.length>100)return null;
 const contexts=(await db.query<{id:string;source_id:string;source_revision:number;person_id:string|null;firm_id:string|null;context_kind:string;review:string}>(`SELECT cx.id,cx.source_id,cx.source_revision,cx.person_id,cx.firm_id,cx.context_kind,cx.review FROM crm_mail_source_contexts cx JOIN crm_mail_sources s ON s.workspace_id=cx.workspace_id AND s.source_id=cx.source_id WHERE s.workspace_id=$1 AND s.source_id=ANY($2::uuid[]) AND ${mailContextPredicate()} ORDER BY cx.id LIMIT 10001`,[workspaceId,sources.map(s=>s.source_id)])).rows;if(contexts.length>10000)return null;
 const endpointKeys=[...new Set(sources.flatMap(copy=>copy.participants).map(value=>createHash('sha256').update(value).digest('hex')))].sort();if(endpointKeys.length>100)return null;
 const endpoints=(await db.query<{id:string;value_hash:string}>(`SELECT id,value_hash FROM crm_identity_endpoints WHERE workspace_id=$1 AND kind='email' AND value_hash=ANY($2::text[]) ORDER BY id`,[workspaceId,endpointKeys])).rows;
 const claims=(await db.query<{id:string;person_id:string|null;firm_id:string|null;source_id:string;source_revision:number;source_hash:string;revision:number;source_invalidated:boolean;shared:boolean;status:string}>(`SELECT c.id,c.person_id,c.firm_id,c.source_id,c.source_revision,c.source_hash,c.revision,c.source_invalidated,c.shared,c.status,c.start_date::text,c.end_date::text,s.availability,s.revision AS current_source_revision,s.content_hash AS current_source_hash FROM crm_endpoint_claims c JOIN crm_selected_sources s ON s.workspace_id=c.workspace_id AND s.id=c.source_id WHERE c.workspace_id=$1 AND c.endpoint_id=ANY($2::uuid[]) ORDER BY c.id LIMIT 1001`,[workspaceId,endpoints.map(endpoint=>endpoint.id)])).rows;if(claims.length>1000)return null;
 const selectedSourceIds=[...new Set(claims.map(claim=>claim.source_id))].sort();
 const selectedContexts=(await db.query<{firm_id:string;person_id:string}>(`SELECT cx.id,cx.source_id,cx.source_revision,cx.source_hash,cx.firm_id,cx.person_id,cx.review FROM crm_selected_sources s JOIN crm_source_relationship_contexts cx ON ${sourceContextPredicate()} WHERE s.workspace_id=$1 AND s.id=ANY($2::uuid[]) ORDER BY cx.id LIMIT 10001`,[workspaceId,selectedSourceIds])).rows;if(selectedContexts.length>10000)return null;
 const hash=createHash('sha256').update(JSON.stringify({root,sources:sources.map(({participants:_,...exact})=>exact),contexts,endpointKeys,endpoints,claims,selectedContexts})).digest('hex');
 return {hash,sources,endpointKeys,endpoints,selectedSourceIds,firmIds:[...new Set([...contexts.flatMap(cx=>cx.firm_id?[cx.firm_id]:[]),...selectedContexts.map(cx=>cx.firm_id),...claims.flatMap(cx=>cx.firm_id?[cx.firm_id]:[])])].sort(),personIds:[...new Set([...contexts.flatMap(cx=>cx.person_id?[cx.person_id]:[]),...selectedContexts.map(cx=>cx.person_id),...claims.flatMap(cx=>cx.person_id?[cx.person_id]:[])])].sort()};
}
/** Completed CRM work grants no outreach permission and changes no stop. */
export async function projectMailProgress(context:RepositoryContext,exact:ExactMailSource & {dependencyHash:string},fence:()=>Promise<boolean>){
 if(!await lockProgressActor(context))return;
 const snapshot=await mailProgressDependency(context.db,context.scope.workspaceId,exact.sourceId);if(!snapshot||exact.dependencyHash!==snapshot.hash)return;
 if(!await lockIdentityContext(context,{firmIds:snapshot.firmIds,personIds:snapshot.personIds,sourceIds:snapshot.selectedSourceIds}))return;
 for(const hash of snapshot.endpointKeys)await context.db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`identity-endpoint:${context.scope.workspaceId}:email:${hash}`]);
 for(const endpoint of snapshot.endpoints)await context.db.query('SELECT id FROM crm_identity_endpoints WHERE workspace_id=$1 AND id=$2 FOR UPDATE',[context.scope.workspaceId,endpoint.id]);
 const checked=await mailProgressDependency(context.db,context.scope.workspaceId,exact.sourceId);if(checked?.hash!==snapshot.hash)return;
 const reads=new Map<string,ReturnType<typeof mailConversationSchema.parse>>();
 for(const copy of snapshot.sources){const current=await mailProgressDependency(context.db,context.scope.workspaceId,exact.sourceId);if(current?.hash!==snapshot.hash)return;reads.set(copy.source_id,mailConversationSchema.parse(await readMailConversation(context,{sourceId:copy.source_id,sourceRevision:copy.source_revision,contentHash:copy.content_hash})));}
 if((await mailProgressDependency(context.db,context.scope.workspaceId,exact.sourceId))?.hash!==snapshot.hash)return;
 const read=reads.get(exact.sourceId);if(read?.state!=='available'||read.source.sourceRevision!==exact.sourceRevision||read.source.contentHash!==exact.contentHash)return;
 const source=read.source;
 if(source.completeness!=='complete'||!source.ranges.some(r=>r.kind==='authored'))return;
 const eventKind=source.direction==='outgoing'?'contacted':'replied';
 if(eventKind==='contacted'&&!source.sentProof)return;
 const prior=[...reads.values()].find(prior=>prior.state==='available'&&prior.source.direction==='outgoing'&&prior.source.sentProof&&prior.source.completeness==='complete'&&prior.source.ranges.some(r=>r.kind==='authored')&&prior.source.occurredAt<source.occurredAt&&prior.source.participants.slice(1).includes(source.participants[0]!)&&source.participants.slice(1).includes(prior.source.participants[0]!));
 if(eventKind==='replied'&&prior?.state!=='available')return;
 const prerequisite=eventKind==='replied'&&prior?.state==='available'?prior.source:null;
 const canonical=(await context.db.query<{provider_thread_id:string}>('SELECT provider_thread_id FROM mail_messages WHERE workspace_id=$1 AND id=$2',[context.scope.workspaceId,exact.sourceId])).rows[0];if(!canonical)return;
 const contexts=[...source.originalContexts,...source.reviewedContexts];
 const firmIds=[...new Set(contexts.flatMap(cx=>cx.firmId?[cx.firmId]:[]))].sort();
 const personIds=[...new Set(contexts.flatMap(cx=>cx.personId?[cx.personId]:[]))].sort();
 if(!await fence())return;
 const args=[context.scope.workspaceId,source.sourceId,source.sourceRevision,source.contentHash,source.ownerUserId,source.mailboxId,source.accountBinding,source.occurredAt,createHash('sha256').update(JSON.stringify(contexts)).digest('hex'),firmIds,personIds,eventKind,prerequisite?.sourceId??null,prerequisite?.sourceRevision??null,prerequisite?.contentHash??null];
 const receipt=(await context.db.query<{id:string}>(`INSERT INTO crm_mail_progress_receipts(workspace_id,source_id,source_revision,source_hash,owner_user_id,mailbox_id,account_binding,event_kind,provider_at,context_hash,original_firm_ids,original_person_ids,prerequisite_source_id,prerequisite_source_revision,prerequisite_source_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$12,$8,$9,$10,$11,$13,$14,$15) ON CONFLICT DO NOTHING RETURNING id`,args)).rows[0]??(await context.db.query<{id:string}>('SELECT id FROM crm_mail_progress_receipts WHERE workspace_id=$1 AND source_id=$2 AND source_revision=$3 AND source_hash=$4 AND event_kind=$5',[context.scope.workspaceId,source.sourceId,source.sourceRevision,source.contentHash,eventKind])).rows[0];if(!receipt||eventKind==='replied')return;
 const requests=(await context.db.query<{id:string;contact_id:string;firm_id:string}>(`SELECT m.id,x.contact_id,x.firm_id FROM mail_messages m JOIN crm_mail_sources incoming ON incoming.workspace_id=m.workspace_id AND incoming.source_id=m.id JOIN mail_message_matches x ON x.workspace_id=m.workspace_id AND x.mail_message_id=m.id WHERE m.workspace_id=$1 AND m.mailbox_id=$2 AND m.provider_thread_id=$3 AND m.direction='incoming' AND incoming.availability='available' AND incoming.provider_at<$4::timestamptz AND x.firm_id=ANY($5::uuid[]) AND x.contact_id IS NOT NULL AND NOT x.ambiguous AND x.selected IS DISTINCT FROM false AND NOT EXISTS(SELECT 1 FROM mail_message_matches other WHERE other.workspace_id=x.workspace_id AND other.mail_message_id=x.mail_message_id AND other.id<>x.id) AND EXISTS(SELECT 1 FROM mail_message_classifications c WHERE c.workspace_id=m.workspace_id AND c.mail_message_id=m.id AND c.layer='deterministic' AND c.class IN ('human','uncertain')) ORDER BY m.id LIMIT 100`,[context.scope.workspaceId,source.mailboxId,canonical.provider_thread_id,source.occurredAt,firmIds])).rows;
 for(const request of requests){
  const original=reads.get(request.id);if(original?.state!=='available')continue;
  if(original.source.occurredAt>=source.occurredAt||original.source.accountBinding!==source.accountBinding||original.source.mailboxId!==source.mailboxId||!source.participants.slice(1).includes(original.source.participants[0]!)||!original.source.participants.slice(1).includes(source.participants[0]!))continue;
  const sender=original.source.participants[0]!;
  const endpointHash=createHash('sha256').update(sender).digest('hex');
  const claims=(await context.db.query<{shared:boolean;person_id:string|null;status:string;start_date:string|null;end_date:string|null;available:boolean}>(`SELECT c.shared,c.person_id,c.status,c.start_date::text,c.end_date::text,(NOT c.source_invalidated AND s.availability='available' AND s.revision=c.source_revision AND s.content_hash=c.source_hash) AS available FROM crm_identity_endpoints e JOIN crm_endpoint_claims c ON c.workspace_id=e.workspace_id AND c.endpoint_id=e.id JOIN crm_selected_sources s ON s.workspace_id=c.workspace_id AND s.id=c.source_id WHERE e.workspace_id=$1 AND e.kind='email' AND e.value_hash=$2 ORDER BY c.id LIMIT 2`,[context.scope.workspaceId,endpointHash])).rows;
  if(claims.length>0){const claim=claims[0]!;const person=(await context.db.query<{person_id:string}>('SELECT person_id FROM crm_legacy_contact_people WHERE workspace_id=$1 AND contact_id=$2',[context.scope.workspaceId,request.contact_id])).rows[0];const day=source.occurredAt.slice(0,10);if(claims.length!==1||claim.shared||!claim.available||claim.status!=='current'||claim.start_date===null||claim.start_date>day||claim.end_date!==null&&claim.end_date<day||person?.person_id!==claim.person_id)continue;}
  const routes=(await context.db.query<{contact_id:string|null;firm_id:string;eligibility:string}>('SELECT contact_id,firm_id,eligibility FROM email_addresses WHERE workspace_id=$1 AND address=$2 AND retired_at IS NULL ORDER BY id LIMIT 2',[context.scope.workspaceId,sender])).rows;
  if(routes.length!==1||routes[0]!.contact_id!==request.contact_id||routes[0]!.firm_id!==request.firm_id||routes[0]!.eligibility!=='usable')continue;
  if(!await fence())return;
  await context.db.query('INSERT INTO crm_mail_reply_resolutions(workspace_id,request_message_id,sent_receipt_id,request_provider_at) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[context.scope.workspaceId,request.id,receipt.id,original.source.occurredAt]);
 }
}

/** Manual opt-out confirmations are receipts, never automatic disposition commands. */
async function optOutSources(context:RepositoryContext,input:{firmId?:string|undefined;personId?:string|undefined;limit:number}){
 const actor=context.scope.actor;if(actor.kind!=='user')return [];
 return (await context.db.query<{confirmation_id:string;confirmed_at:Date;source_id:string;source_revision:number;content_hash:string;firm_id:string}>(`SELECT c.id AS confirmation_id,c.created_at AS confirmed_at,s.source_id,s.source_revision,s.content_hash,c.firm_id FROM mail_reply_confirmations c JOIN crm_mail_sources s ON s.workspace_id=c.workspace_id AND s.source_id=c.mail_message_id JOIN mail_messages m ON m.workspace_id=s.workspace_id AND m.id=s.source_id WHERE c.workspace_id=$1 AND c.disposition='opt_out' AND m.direction='incoming' AND s.availability='available' AND ($2 OR s.owner_user_id=$3) AND ($4::uuid IS NULL OR c.firm_id=$4) AND ($5::uuid IS NULL OR EXISTS(SELECT 1 FROM crm_mail_source_contexts cx WHERE cx.workspace_id=s.workspace_id AND cx.source_id=s.source_id AND ${mailContextPredicate()} AND cx.person_id=$5)) ORDER BY c.created_at,c.id LIMIT $6`,[context.scope.workspaceId,actor.role==='admin',actor.userId,input.firmId??null,input.personId??null,input.limit+1])).rows;
}
/** Current source authority is checked before source-linked progress is displayed. */
export async function readCrmProgress(context:RepositoryContext,input:{firmId?:string|undefined;personId?:string|undefined;limit:number}){
 const actor=context.scope.actor;if(actor.kind!=='user'||!await lockProgressActor(context))return null;
 const rows=(await context.db.query<{id:string;source_id:string;source_revision:number;source_hash:string;event_kind:'contacted'|'replied';prerequisite_source_id:string|null;prerequisite_source_revision:number|null;prerequisite_source_hash:string|null;original_firm_ids:string[];original_person_ids:string[]}>(`SELECT id,source_id,source_revision,source_hash,event_kind,prerequisite_source_id,prerequisite_source_revision,prerequisite_source_hash,original_firm_ids,original_person_ids FROM crm_mail_progress_receipts WHERE workspace_id=$1 AND state='active' AND ($2 OR owner_user_id=$3) AND ($4::uuid IS NULL OR $4=ANY(original_firm_ids)) AND ($5::uuid IS NULL OR $5=ANY(original_person_ids)) ORDER BY provider_at,id LIMIT $6`,[context.scope.workspaceId,actor.role==='admin',actor.userId,input.firmId??null,input.personId??null,input.limit+1])).rows;
 const visible=rows.slice(0,input.limit);
 const optOuts=await optOutSources(context,input);
 const exactCopies=[...visible.flatMap(row=>[{sourceId:row.source_id,sourceRevision:row.source_revision,contentHash:row.source_hash},...(row.prerequisite_source_id===null||row.prerequisite_source_revision===null||row.prerequisite_source_hash===null?[]:[{sourceId:row.prerequisite_source_id,sourceRevision:row.prerequisite_source_revision,contentHash:row.prerequisite_source_hash}])]),...optOuts.slice(0,input.limit).map(row=>({sourceId:row.source_id,sourceRevision:row.source_revision,contentHash:row.content_hash}))].sort((a,b)=>a.sourceId<b.sourceId?-1:a.sourceId>b.sourceId?1:a.sourceRevision-b.sourceRevision);
 const sourceIds=[...new Set(exactCopies.map(copy=>copy.sourceId))];
 const collect=async()=>(await context.db.query<{source_id:string;source_revision:number;content_hash:string;availability:string;firm_id:string|null;person_id:string|null}>(`SELECT s.source_id,s.source_revision,s.content_hash,s.availability,cx.id,cx.firm_id,cx.person_id,cx.context_kind,cx.review,cx.source_revision AS context_revision FROM crm_mail_sources s LEFT JOIN crm_mail_source_contexts cx ON cx.workspace_id=s.workspace_id AND cx.source_id=s.source_id AND ${mailContextPredicate()} WHERE s.workspace_id=$1 AND s.source_id=ANY($2::uuid[]) ORDER BY s.source_id,cx.id LIMIT 15001`,[context.scope.workspaceId,sourceIds])).rows;
 const closure=await collect();if(closure.length>15000)return null;
 const operationalPerson=input.personId===undefined?null:(await context.db.query<{firm_id:string}>('SELECT c.firm_id FROM crm_legacy_contact_people b JOIN contacts c ON c.workspace_id=b.workspace_id AND c.id=b.contact_id WHERE b.workspace_id=$1 AND b.person_id=$2',[context.scope.workspaceId,input.personId])).rows[0];
 const firms=[...new Set([...closure.flatMap(cx=>cx.firm_id?[cx.firm_id]:[]),...optOuts.map(row=>row.firm_id),...(input.firmId===undefined?[]:[input.firmId]),...(operationalPerson?[operationalPerson.firm_id]:[])])].sort();
 const people=[...new Set([...closure.flatMap(cx=>cx.person_id?[cx.person_id]:[]),...(input.personId===undefined?[]:[input.personId])])].sort();
 if(!await lockIdentityContext(context,{firmIds:firms,personIds:people})||JSON.stringify(await collect())!==JSON.stringify(closure))return null;
 const operational=await readOperationalProgress(context,input);if(operational===null)return null;
 const reads=new Map<string,Awaited<ReturnType<typeof readMailConversation>>>();
 for(const copy of exactCopies){const key=`${copy.sourceId}:${copy.sourceRevision}:${copy.contentHash}`;if(reads.has(key))continue;if(JSON.stringify(await collect())!==JSON.stringify(closure))return null;reads.set(key,await readMailConversation(context,copy));}
 if(JSON.stringify(await collect())!==JSON.stringify(closure)||!await activeIdentityActor(context))return null;
 const events=[];
 for(const row of visible){
  const read=reads.get(`${row.source_id}:${row.source_revision}:${row.source_hash}`);if(read?.state!=='available')continue;
  if(row.event_kind==='replied'){if(row.prerequisite_source_id===null||row.prerequisite_source_revision===null||row.prerequisite_source_hash===null)continue;const prior=reads.get(`${row.prerequisite_source_id}:${row.prerequisite_source_revision}:${row.prerequisite_source_hash}`);if(prior?.state!=='available'||!prior.source.sentProof)continue;}
  const source=read.source;
  events.push({id:row.id,kind:row.event_kind,occurredAt:source.occurredAt,dateBasis:'provider_event' as const,observedAt:source.observedAt,bookingState:null,firmIds:row.original_firm_ids,personIds:row.original_person_ids,source:sourceReference(context.scope.workspaceId,source),evidence:{kind:'mail_source' as const,id:source.sourceId}});
 }
 if(JSON.stringify(await optOutSources(context,input))!==JSON.stringify(optOuts))return null;
 for(const row of optOuts.slice(0,input.limit)){const read=reads.get(`${row.source_id}:${row.source_revision}:${row.content_hash}`);if(read?.state!=='available')continue;const source=read.source;events.push({id:row.confirmation_id,kind:'opted_out' as const,occurredAt:source.occurredAt,dateBasis:'provider_event' as const,observedAt:row.confirmed_at.toISOString(),bookingState:null,firmIds:[row.firm_id],personIds:input.personId===undefined?[]:[input.personId],source:sourceReference(context.scope.workspaceId,source),evidence:{kind:'reply_opt_out' as const,id:row.confirmation_id}});}
 const merged=[...events,...operational].sort((a,b)=>a.occurredAt<b.occurredAt?-1:a.occurredAt>b.occurredAt?1:a.id<b.id?-1:1);
 return {version:1 as const,events:merged.slice(0,input.limit),truncated:rows.length>input.limit||optOuts.length>input.limit||merged.length>input.limit,coverage:'partial' as const};
}
