import type { AssessmentRow } from "../src/assessments";

/** R3 three-family, owner-occupied (mail zip == situs zip). */
export const ROW_R3_OWNER_OCC: AssessmentRow = {
  PID: "0100001000",
  ST_NUM: "195",
  ST_NAME: "Lexington ST",
  UNIT_NUM: null,
  CITY: "EAST BOSTON",
  ZIP_CODE: "02128",
  LUC: "105",
  LU: "R3",
  OWN_OCC: "Y",
  OWNER: "PASCUCCI CARLO",
  MAIL_ADDRESSEE: null,
  MAIL_STREET_ADDRESS: "195 LEXINGTON ST",
  MAIL_CITY: "EAST BOSTON",
  MAIL_STATE: "MA",
  MAIL_ZIP_CODE: "02128",
  RES_UNITS: null,
  COM_UNITS: null,
  RC_UNITS: null,
  TOTAL_VALUE: "822,900",
  GROSS_TAX: " $10,203.96 ",
  YR_BUILT: "1900",
};

/** Trust-owned R3, absentee (Wakefield mailing). */
export const ROW_TRUST_ABSENTEE: AssessmentRow = {
  PID: "0100002000",
  ST_NUM: "197",
  ST_NAME: "Lexington ST",
  UNIT_NUM: null,
  CITY: "EAST BOSTON",
  ZIP_CODE: "02128",
  LUC: "105",
  LU: "R3",
  OWN_OCC: "N",
  OWNER: "SEMBRANO LIVING TRUST",
  MAIL_ADDRESSEE: null,
  MAIL_STREET_ADDRESS: "2 MITCHELL LANE",
  MAIL_CITY: "WAKEFIELD",
  MAIL_STATE: "MA",
  MAIL_ZIP_CODE: "01880",
  RES_UNITS: null,
  COM_UNITS: null,
  RC_UNITS: null,
  TOTAL_VALUE: "868,400",
  GROSS_TAX: " $10,768.16 ",
  YR_BUILT: "1920",
};

/** LLC-owned A-class apartment building with unit counts. */
export const ROW_LLC_APARTMENT: AssessmentRow = {
  PID: "0200003000",
  ST_NUM: "12",
  ST_NAME: "Maverick SQ",
  UNIT_NUM: null,
  CITY: "EAST BOSTON",
  ZIP_CODE: "02128",
  LUC: "112",
  LU: "A",
  OWN_OCC: "N",
  OWNER: "MAVERICK HOLDINGS LLC",
  MAIL_ADDRESSEE: null,
  MAIL_STREET_ADDRESS: "1 FINANCIAL CTR STE 900",
  MAIL_CITY: "BOSTON",
  MAIL_STATE: "MA",
  MAIL_ZIP_CODE: "02111",
  RES_UNITS: "8",
  COM_UNITS: "1",
  RC_UNITS: null,
  TOTAL_VALUE: "3,200,000",
  GROSS_TAX: " $39,680.00 ",
  YR_BUILT: "1925",
};

/** CD condo unit, sparse data. */
export const ROW_CONDO: AssessmentRow = {
  PID: "0300004000",
  ST_NUM: "45",
  ST_NAME: "Province ST",
  UNIT_NUM: "1203",
  CITY: "BOSTON",
  ZIP_CODE: "02108",
  LUC: "102",
  LU: "CD",
  OWN_OCC: "Y",
  OWNER: "CHEN WEI",
  MAIL_ADDRESSEE: null,
  MAIL_STREET_ADDRESS: "45 PROVINCE ST UNIT 1203",
  MAIL_CITY: "BOSTON",
  MAIL_STATE: "MA",
  MAIL_ZIP_CODE: "02108",
  RES_UNITS: "1",
  COM_UNITS: null,
  RC_UNITS: null,
  TOTAL_VALUE: "710,500",
  GROSS_TAX: " $8,810.20 ",
  YR_BUILT: "2008",
};
