/** Synthetic fixture matching observed controls, never an external social request. */
export const linkedinComposerFixture=`<!doctype html><html><body><dialog open data-testid="dialog"></dialog><script>
const root=document.querySelector('dialog');let text='',schedule='',imageUrl='',alt='';
function composer(){root.innerHTML='<div role="button" id="identity">Fixture Founder</div><div role="button">Post to Anyone</div><div role="button">Comments: Anyone</div><div contenteditable="true" role="textbox" componentkey="ShareBox_textEditor"></div><div id="summary"></div><button aria-label="Media">Media</button><a aria-label="Scheduled">Scheduled</a><button disabled>Schedule</button>';
root.querySelector('[aria-label="Media"]').onclick=openMedia;if(imageUrl){const image=document.createElement('img');image.src=imageUrl;image.alt=alt;root.append(image);}
const editor=root.querySelector('[contenteditable]');editor.textContent=text;editor.oninput=()=>{text=editor.innerText;};root.querySelector('#summary').textContent=schedule;
root.querySelector('#identity').onclick=()=>{const old=root.querySelector('[role="radio"]');if(old)old.remove();else{const e=document.createElement('div');e.setAttribute('role','radio');e.setAttribute('aria-checked','true');e.textContent='Fixture Founder';root.append(e);}};
root.querySelector('a').onclick=()=>{root.innerHTML='<input data-testid="date-picker-input"><input data-testid="time-picker-input"><button>Confirm</button>';root.querySelector('button').onclick=()=>{const date=root.querySelector('[data-testid="date-picker-input"]').value,time=root.querySelector('[data-testid="time-picker-input"]').value;const d=new Date(date+' '+time);const p=Object.fromEntries(new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric'}).formatToParts(d).map(p=>[p.type,p.value]));schedule='Posting at '+p.weekday+', '+p.month+' '+p.day+', '+time;composer();};};
}
function openMedia(){const media=document.createElement('dialog');media.open=true;media.dataset.testid='dialog';document.body.append(media);const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg';input.multiple=true;input.style.display='none';document.body.append(input);
function editor(){media.innerHTML='<h2>Editor</h2>'+(imageUrl?'<img alt="Image Preview"><span>1 of 1</span><button role="checkbox" aria-label="Alternative text">Alternative text</button>':'<p>Select files to begin</p>')+'<button id="next">Next</button>';const next=media.querySelector('#next');next.disabled=!imageUrl;next.onclick=()=>{media.remove();input.remove();composer();};if(imageUrl){media.querySelector('img').src=imageUrl;media.querySelector('[role="checkbox"]').onclick=()=>{media.innerHTML='<h2>Editor</h2><h2>Add alt text</h2><textarea></textarea><button id="save">Add</button><button aria-label="Back">Back</button>';const field=media.querySelector('textarea');field.value=alt;media.querySelector('#save').onclick=()=>{alt=field.value;editor();};media.querySelector('[aria-label="Back"]').onclick=editor;};}}
input.onchange=()=>{imageUrl=URL.createObjectURL(input.files[0]);editor();};editor();
}
composer();</script></body></html>`;
