import {z} from 'zod';
import {commandIdSchema} from './auth.ts';
import {semanticVersionSchema} from './clientVersion.ts';
import {askExplicitCorpusScopeSchema,askPassagesResponseSchema} from './ask.ts';
import {crmResolvedSourceSchema} from './crmProcessing.ts';
export const askAnswerStateSchema=z.enum(['pending','unavailable','unknown_acceptance','stale','complete','deleted']);
export const askAnswerReasonSchema=z.enum(['purpose_unavailable','evaluation_unavailable','processing_authority_unavailable','budget_held','input_bound_reached','source_unavailable','source_changed','purpose_changed','provider_acceptance_unknown','processing_failed','unsupported_answer','deleted']);
export const askAnswerRequestPayloadSchema=z.strictObject({question:z.string().trim().min(1).max(300),scope:askExplicitCorpusScopeSchema});
export const askAnswerRequestSchema=askAnswerRequestPayloadSchema.extend({commandId:commandIdSchema,clientVersion:semanticVersionSchema}).strict();
export const askAnswerAcknowledgmentSchema=z.strictObject({requestId:z.uuid(),version:z.number().int().positive(),state:z.enum(['pending','unavailable'])});
export const askAnswerReadSchema=z.strictObject({requestId:z.uuid()});
export const askAnswerSourceReadSchema=askAnswerReadSchema.extend({expectedVersion:z.number().int().positive(),windowId:z.uuid()}).strict();
export const askAnswerCoverageSchema=z.strictObject({acquisition:z.literal('unverified'),semantic:z.enum(['bounded_evaluated','unavailable','unverified']),input:z.enum(['complete','partial','unavailable']),sourceCeiling:z.literal(10),windowCeiling:z.literal(1000),groupCeiling:z.literal(10),evaluationFingerprint:z.string().regex(/^[a-f0-9]{64}$/u).nullable()});
export const askAnswerMissingEvidenceSchema=z.enum(['no_supported_answer','inference_unverified','conflict_unresolved','input_partial','semantic_coverage_unverified','no_relevant_passages']);
export const askAnswerClaimSchema=z.strictObject({text:z.string().min(1).max(1000),kind:z.enum(['extractive','inferred']),citationWindowIds:z.array(z.uuid()).min(1).max(10),verification:z.literal('supported')});
export const askGroundedAnswerSchema=z.strictObject({answeredAt:z.iso.datetime(),claims:z.array(askAnswerClaimSchema).max(20),conflicts:z.array(z.strictObject({conflictId:z.uuid(),revision:z.number().int().positive(),state:z.literal('open'),resolution:z.null()})).max(10),missingEvidence:z.array(askAnswerMissingEvidenceSchema).max(10),abstained:z.boolean(),coverage:askAnswerCoverageSchema}).refine(value=>!value.abstained||value.claims.length===0,'Abstention cannot publish claims');
export const askAnswerReadResultSchema=z.strictObject({requestId:z.uuid(),version:z.number().int().positive(),createdAt:z.iso.datetime(),state:askAnswerStateSchema,reason:askAnswerReasonSchema.nullable(),question:z.string().max(300).nullable(),fallback:askPassagesResponseSchema.nullable(),answer:askGroundedAnswerSchema.nullable()}).refine(value=>(value.state==='complete')===(value.answer!==null),'Only completed current results carry an answer').refine(value=>!(['deleted','stale'].includes(value.state)||value.reason==='source_unavailable')||(value.question===null&&value.fallback===null&&value.answer===null),'Invalidated history carries no copied private content');
export const askAnswerSourceResultSchema=z.strictObject({requestId:z.uuid(),version:z.number().int().positive(),windowId:z.uuid(),source:crmResolvedSourceSchema});
export type AskAnswerRequest=z.infer<typeof askAnswerRequestSchema>;
export type AskAnswerRead=z.infer<typeof askAnswerReadSchema>;
export type AskAnswerReadResult=z.infer<typeof askAnswerReadResultSchema>;
export type AskGroundedAnswer=z.infer<typeof askGroundedAnswerSchema>;
