import { z } from 'zod';
import { commandIdSchema } from './auth.ts';
import { semanticVersionSchema } from './clientVersion.ts';
import { uuid, sha256Hex } from './foundationRows.ts';
export const businessPolicyReadSchema = z.strictObject({ mailboxId: uuid.optional() });
export const businessDisclosureSchema = z.strictObject({ version: z.string().min(1).max(100), sha256: sha256Hex });
export const businessPolicySchema = z.strictObject({ mailboxId: uuid.nullable(), ownerUserId: uuid.nullable(), emailAddress: z.string().nullable(), generation: z.number().int().positive().nullable(), accountBinding: sha256Hex.nullable(), revision: z.number().int().nonnegative(), enabled: z.boolean(), scopeDays: z.literal(90), classificationMode: z.literal('metadata_only'), disclosure: businessDisclosureSchema.nullable(), ready: z.literal(false), reasons: z.array(z.string()), metadataReviewDisclosureText: z.string().min(1).max(2000), metadataReviewDisclosure: businessDisclosureSchema });
export const businessPolicySavePayloadSchema = z.strictObject({ mailboxId: uuid, expectedGeneration: z.number().int().positive(), expectedAccountBinding: sha256Hex, expectedRevision: z.number().int().nonnegative(), enabled: z.boolean(), disclosure: businessDisclosureSchema.nullable() });
export const businessPolicySaveSchema = businessPolicySavePayloadSchema.extend({ commandId: commandIdSchema, clientVersion: semanticVersionSchema });
export type BusinessPolicy = z.infer<typeof businessPolicySchema>;
export const businessCategorySchema = z.enum(['business', 'uncertain', 'personal', 'newsletter', 'receipt', 'routine_support']);
export const businessReviewReadSchema = z.strictObject({ mailboxId: uuid, after: uuid.optional(), limit: z.number().int().min(1).max(100).default(50) });
export const businessConversationSchema = z.strictObject({ conversationId: uuid, subject: z.string().max(500), participants: z.array(z.string().max(320)).max(50), latestProviderAt: z.iso.datetime(), category: businessCategorySchema, reason: z.string().max(100), metadataRevision: z.number().int().positive(), decisionRevision: z.number().int().nonnegative(), humanDecision: z.enum(['include', 'exclude']).nullable(), effectiveDecision: z.enum(['included', 'excluded', 'needs_review']), captureAllowed: z.literal(false) });
export const businessReviewSchema = z.strictObject({ available: z.boolean(), reasons: z.array(z.string()), mailboxId: uuid, accountBinding: sha256Hex.nullable(), generation: z.number().int().positive().nullable(), policyRevision: z.number().int().nonnegative(), captureAllowed: z.literal(false), conversations: z.array(businessConversationSchema), nextAfter: uuid.nullable() });
export const businessReviewDecidePayloadSchema = z.strictObject({ mailboxId: uuid, conversationId: uuid, expectedAccountBinding: sha256Hex, expectedGeneration: z.number().int().positive(), expectedPolicyRevision: z.number().int().positive(), expectedMetadataRevision: z.number().int().positive(), expectedDecisionRevision: z.number().int().nonnegative(), decision: z.enum(['include', 'exclude']) });
export const businessReviewDecideSchema = businessReviewDecidePayloadSchema.extend({ commandId: commandIdSchema, clientVersion: semanticVersionSchema });
export type BusinessReviewPage = z.infer<typeof businessReviewSchema>;
/** Metadata observer input only; never an API route or provider fetch grant. */
export const businessMetadataObservationSchema = z.strictObject({ mailboxId: uuid, providerAccountId: z.string().min(1).max(320), generation: z.number().int().positive(), expectedPolicyRevision: z.number().int().positive(), providerThreadId: z.string().min(1).max(320), providerMessageId: z.string().min(1).max(320), subject: z.string().max(500), participants: z.array(z.string().min(1).max(320)).max(50), latestProviderAt: z.iso.datetime(), category: businessCategorySchema, reason: z.enum(['business_metadata', 'unclassified_metadata', 'personal_metadata', 'newsletter_headers', 'receipt_headers', 'routine_support_headers']), classifierVersion: z.string().min(1).max(100) });
