import {z} from 'zod';
import {uuid} from './foundationRows.ts';
import {commandIdSchema} from './auth.ts';
import {semanticVersionSchema} from './clientVersion.ts';
export const prospectingAuthorizationReadSchema=z.strictObject({mailboxId:uuid});
export const prospectingAuthorizationSaveSchema=z.strictObject({mailboxId:uuid,expectedRevision:z.number().int().nonnegative(),enabled:z.boolean(),basis:z.literal('owner_reported_google_permission'),commandId:commandIdSchema,clientVersion:semanticVersionSchema});
export const prospectingAuthorizationViewSchema=z.strictObject({allowed:z.boolean(),revision:z.number().int().positive().nullable(),reason:z.string().nullable()});
export const answerBlockKindSchema=z.enum(['product','pricing','booking','material']);
export const answerBlockSchema=z.strictObject({id:uuid,version:z.number().int().positive(),kind:answerBlockKindSchema,text:z.string().trim().min(1).max(4000),approvedAt:z.string().nullable(),retiredAt:z.string().nullable()});
export type AnswerBlock=z.infer<typeof answerBlockSchema>;
export const saveAnswerBlockSchema=z.strictObject({id:uuid.optional(),expectedVersion:z.number().int().nonnegative().optional(),kind:answerBlockKindSchema,text:z.string().trim().min(1).max(4000)}).refine(v=>v.id===undefined?v.expectedVersion===undefined:v.expectedVersion!==undefined,'Existing block needs expected version');
export type SaveAnswerBlock=z.infer<typeof saveAnswerBlockSchema>;
export const saveAnswerBlockCommandSchema=saveAnswerBlockSchema.safeExtend({commandId:commandIdSchema,clientVersion:semanticVersionSchema});
export const answerBlockApprovalCommandSchema=z.strictObject({id:uuid,version:z.number().int().positive(),commandId:commandIdSchema,clientVersion:semanticVersionSchema});
export const answerBlocksReadSchema=z.strictObject({afterId:uuid.optional()});
export const sequenceSubjectSchema=z.discriminatedUnion('kind',[z.strictObject({kind:z.literal('opportunity'),opportunityId:uuid}),z.strictObject({kind:z.literal('outreach'),outreachPlanId:uuid})]);
export type SequenceSubject=z.infer<typeof sequenceSubjectSchema>;
export const outreachPlanSchema=z.strictObject({id:uuid,firmId:uuid,contactId:uuid,ownerUserId:uuid,mailboxId:uuid,lane:z.enum(['call_first','email_first']),revision:z.number().int().positive(),state:z.enum(['active','reply_pending','manual','booked','completed','stopped'])});
export type OutreachPlan=z.infer<typeof outreachPlanSchema>;
export const createOutreachPlanSchema=z.strictObject({firmId:uuid,contactId:uuid,mailboxId:uuid,lane:z.enum(['call_first','email_first']),qualificationRunId:uuid,expectedOwnerUserId:uuid});
export type CreateOutreachPlan=z.infer<typeof createOutreachPlanSchema>;
