import { z } from 'zod';
import { commandIdSchema } from './auth.ts';
import { semanticVersionSchema } from './clientVersion.ts';
import { uuid, instant } from './foundationRows.ts';
const envelope = { commandId: commandIdSchema, clientVersion: semanticVersionSchema };
export const personCreateSchema = z.object({ ...envelope, fullName: z.string().trim().min(1).max(240) }).strict();
export const personReadSchema = z.object({ personId: uuid, afterSourceId: uuid.optional(), limit: z.number().int().min(1).max(100).default(50) }).strict();
export const personListSchema = z.object({ afterId: uuid.optional(), limit: z.number().int().min(1).max(100).default(50) }).strict();
export const personSourceAddSchema = z.object({ ...envelope, personId: uuid, sourceKey: z.string().min(1).max(200), excerpt: z.string().trim().min(1).max(20000), occurredAt: instant }).strict();
export const personSourceChangeSchema = z.object({ ...envelope, personId: uuid, sourceId: uuid, expectedRevision: z.number().int().positive() }).strict();
export const personSourceRecaptureSchema = personSourceChangeSchema.extend({ excerpt: z.string().trim().min(1).max(20000), occurredAt: instant }).strict();
export const personBridgeSchema = z.object({ ...envelope, contactIds: z.array(uuid).min(1).max(100) }).strict();
export const canonicalSourceReferenceSchema = z.object({ workspaceId: uuid, sourceId: uuid, kind: z.enum(['selected_note', 'mail', 'call_transcript', 'meeting_transcript']), revision: z.number().int().positive(), contentHash: z.string().regex(/^[a-f0-9]{64}$/u).nullable(), locator: z.string().nullable(), speaker: z.string().nullable(), occurredAt: instant.nullable(), observedAt: instant, completeness: z.enum(['selected_excerpt', 'complete', 'partial', 'unavailable']), availability: z.enum(['available', 'deleted', 'awaiting_recapture', 'unavailable']) }).strict();
export const personSourceSchema = canonicalSourceReferenceSchema.extend({ excerpt: z.string().nullable() }).strict();
export const personSchema = z.object({ personId: uuid, fullName: z.string(), firm: z.object({ firmId: uuid, name: z.string() }).nullable(), revision: z.number().int().positive() }).strict();
export const personPageSchema = z.object({ person: personSchema, sources: z.array(personSourceSchema), nextAfterSourceId: uuid.nullable() }).strict();
export const peopleListSchema = z.object({ people: z.array(personSchema), nextAfterId: uuid.nullable() }).strict();
export type CanonicalSourceReference = z.infer<typeof canonicalSourceReferenceSchema>;
export type PersonPage = z.infer<typeof personPageSchema>;
