import { z } from 'zod';
import { commandIdSchema } from './auth.ts';
import { semanticVersionSchema } from './clientVersion.ts';
import { uuid, instant } from './foundationRows.ts';
import { personSourceSchema } from './people.ts';
const envelope = { commandId: commandIdSchema, clientVersion: semanticVersionSchema };
const day = z.string().regex(/^\d{4}-\d{2}-\d{2}$/u).refine(value => {
  const [year, month, date] = value.split('-').map(Number);
  if (year === undefined || month === undefined || date === undefined || year < 1)
    return false;
  const check = new Date(0);
  check.setUTCFullYear(year, month - 1, date);
  return check.getUTCFullYear() === year && check.getUTCMonth() === month - 1 && check.getUTCDate() === date;
}, 'Use a valid calendar date');
export const identityEvidenceSchema = z.object({ sourceId: uuid, sourceRevision: z.number().int().positive(), contentHash: z.string().regex(/^[a-f0-9]{64}$/u) }).strict();
const assertion = { status: z.enum(['current', 'historical', 'unknown']), startDate: day.nullable(), endDate: day.nullable(), evidence: identityEvidenceSchema };
export const relationshipSaveSchema = z.object({ ...envelope, personId: uuid, firmId: uuid, ...assertion }).strict();
export const relationshipCorrectSchema = relationshipSaveSchema.extend({ relationshipId: uuid, expectedRevision: z.number().int().positive() }).strict();
export const relationshipReadSchema = z.object({ personId: uuid, afterId: uuid.optional(), limit: z.number().int().min(1).max(100).default(50) }).strict();
export const relationshipSchema = z.object({ relationshipId: uuid, personId: uuid, firmId: uuid, firmName: z.string(), status: assertion.status, startDate: day.nullable(), endDate: day.nullable(), revision: z.number().int().positive(), evidence: identityEvidenceSchema, sourceState: z.enum(['available', 'unavailable']), contextReview: z.enum(['current', 'required']) }).strict();
export const relationshipListSchema = z.object({ relationships: z.array(relationshipSchema), nextAfterId: uuid.nullable() }).strict();
const endpointClaimObject = z.object({ ...envelope, kind: z.enum(['email', 'phone']), value: z.string().trim().min(1).max(320), personId: uuid.nullable(), firmId: uuid.nullable(), shared: z.boolean(), ...assertion }).strict();
export const endpointClaimSchema = endpointClaimObject.refine(value => (value.personId !== null && value.firmId === null && !value.shared) || (value.personId === null && value.firmId !== null && value.shared), 'An endpoint belongs to a person or a shared firm address');
export const endpointCorrectSchema = endpointClaimObject.extend({ claimId: uuid, expectedRevision: z.number().int().positive() }).strict().refine(value => (value.personId !== null && value.firmId === null && !value.shared) || (value.personId === null && value.firmId !== null && value.shared), 'An endpoint belongs to a person or a shared firm address');
export const endpointListInputSchema = z.object({ personId: uuid.optional(), firmId: uuid.optional(), afterId: uuid.optional(), limit: z.number().int().min(1).max(100).default(50) }).strict();
export const endpointAssertionSchema = z.object({ claimId: uuid, endpointId: uuid, kind: z.enum(['email', 'phone']), value: z.string(), personId: uuid.nullable(), personName: z.string().nullable(), firmId: uuid.nullable(), firmName: z.string().nullable(), shared: z.boolean(), status: assertion.status, startDate: day.nullable(), endDate: day.nullable(), revision: z.number().int().positive(), evidence: identityEvidenceSchema, sourceState: z.enum(['available', 'unavailable']) }).strict();
export const endpointListSchema = z.object({ claims: z.array(endpointAssertionSchema), nextAfterId: uuid.nullable() }).strict();
export const endpointMatchInputSchema = z.object({ kind: z.enum(['email', 'phone']), value: z.string().trim().min(1).max(320) }).strict();
export const endpointMatchSchema = z.object({ outcome: z.enum(['person_match', 'firm_endpoint_match', 'needs_review', 'no_supported_match']), reason: z.enum(['supported_unique', 'shared_endpoint', 'uncertain_identity', 'no_supported_evidence']), personId: uuid.nullable(), firmId: uuid.nullable(), candidates: z.array(endpointAssertionSchema) }).strict();
export const sourceContextSaveSchema = z.object({ ...envelope, personId: uuid, relationshipId: uuid, relationshipRevision: z.number().int().positive(), evidence: identityEvidenceSchema }).strict();
export const sourceContextListSchema = z.object({ contexts: z.array(z.object({ contextId: uuid, sourceId: uuid, relationshipId: uuid, relationshipRevision: z.number().int().positive(), firmId: uuid, review: z.enum(['current', 'required']) }).strict()), nextAfterId: uuid.nullable() }).strict();
export const firmSourceAddSchema = z.object({ ...envelope, firmId: uuid, sourceKey: z.string().min(1).max(200), excerpt: z.string().trim().min(1).max(20000), occurredAt: instant }).strict();
export const firmSourceReadSchema = z.object({ firmId: uuid, afterSourceId: uuid.optional(), limit: z.number().int().min(1).max(100).default(50) }).strict();
export const firmSourcePageSchema = z.object({ sources: z.array(personSourceSchema), nextAfterSourceId: uuid.nullable() }).strict();
export type IdentityEvidence = z.infer<typeof identityEvidenceSchema>;
export const firmSourceChangeSchema = z.object({ ...envelope, firmId: uuid, sourceId: uuid, expectedRevision: z.number().int().positive() }).strict();
export const firmSourceRecaptureSchema = firmSourceChangeSchema.extend({ excerpt: z.string().trim().min(1).max(20000), occurredAt: instant }).strict();
export const endpointClaimPayloadSchema = endpointClaimObject.omit({ commandId: true, clientVersion: true }).refine(value => (value.personId !== null && value.firmId === null && !value.shared) || (value.personId === null && value.firmId !== null && value.shared), 'An endpoint belongs to a person or a shared firm address');
export const endpointCorrectPayloadSchema = endpointClaimObject.omit({ commandId: true, clientVersion: true }).extend({ claimId: uuid, expectedRevision: z.number().int().positive() }).strict().refine(value => (value.personId !== null && value.firmId === null && !value.shared) || (value.personId === null && value.firmId !== null && value.shared), 'An endpoint belongs to a person or a shared firm address');
