import {
  GmailClientError,
  directionOfLabels,
  type GmailAccessGrant,
  type GmailAccessOutcome,
  type GmailAttachmentReference,
  type GmailClient,
  type GmailHistoryOutcome,
  type GmailHistoryRecord,
  type GmailHistoryRequest,
  type GmailListOutcome,
  type GmailListRequest,
  type GmailMessageBody,
  type GmailMessageMetadata,
  type GmailOAuthConfig,
  type GmailProfile,
  type GmailTokenOutcome,
  type GmailWatchOutcome,
} from './gmailClient.ts';

/**
 * The recorded-fixture Gmail client.
 *
 * A fixture is a recording of one mailbox: its profile, the messages it holds with
 * their allowlisted headers, and the history records Gmail would replay from a given
 * cursor. The fake answers from that recording and records every call it was given,
 * so a test asserts two things the network could never tell it: what FSS asked for,
 * and what it did *not* ask for.
 *
 * The second is the interesting one. `metadataReads` and `bodyReads` are separate
 * lists, so "no body was fetched for a message that did not match" and "no attachment
 * bytes were ever requested" are assertions rather than hopes.
 *
 * The fake also reproduces the four failures the specification gives a defined
 * recovery to: an expired history cursor (12.3), a revoked grant (12.6), a rate
 * limit, and a message that has been deleted between the history page and the read.
 * Each is a flag on the fixture rather than a special client, because a test that
 * needs the failure halfway through a run needs one client, not two.
 *
 * It contains no credential, no real address and no real person. Every identifier is
 * generated by the test that builds the fixture.
 */

export interface GmailFixtureMessage {
  readonly id: string;
  readonly threadId: string;
  readonly internalDateEpochMilliseconds: number;
  readonly labelIds?: readonly string[] | undefined;
  readonly headers: Readonly<Record<string, string>>;
  readonly body?: string | undefined;
  readonly bodyTruncated?: boolean | undefined;
  readonly attachments?: readonly GmailAttachmentReference[] | undefined;
  /** The history id at which this message appeared. Orders the history replay. */
  readonly historyId: string;
}

export interface GmailFixture {
  readonly emailAddress: string;
  /** The mailbox's current history id: what `getProfile` and a watch return. */
  readonly historyId: string;
  readonly messages: readonly GmailFixtureMessage[];
  /** Cursors the fixture refuses with `history_expired` (12.3, Appendix G 13). */
  readonly expiredHistoryIds?: readonly string[] | undefined;
  readonly grantRevoked?: boolean | undefined;
  readonly rateLimited?: boolean | undefined;
  /** Ids the reads pretend are gone, as a message deleted between page and read. */
  readonly vanishedMessageIds?: readonly string[] | undefined;
  /** How many history records a page carries. Small in tests, 100 in Gmail. */
  readonly historyPageSize?: number | undefined;
  readonly listPageSize?: number | undefined;
  readonly watchExpiresAtEpochMilliseconds?: number | undefined;
  /** The refresh token a consent hands back. Generated by the test, never a literal. */
  readonly refreshToken?: string | undefined;
}

export interface GmailFakeCall {
  readonly method: string;
  readonly detail: Readonly<Record<string, unknown>>;
}

export interface RecordedGmailClient extends GmailClient {
  readonly calls: readonly GmailFakeCall[];
  /** Message ids `getMetadata` was called for, in order, including repeats. */
  readonly metadataReads: readonly string[];
  /** Message ids `getBody` was called for. Empty is the assertion that matters. */
  readonly bodyReads: readonly string[];
  /** Header names every metadata read asked for, deduplicated. */
  readonly requestedHeaders: readonly string[];
}

const byHistoryId = (left: GmailFixtureMessage, right: GmailFixtureMessage): number =>
  Number(left.historyId) - Number(right.historyId);

export function recordedGmailClient(fixture: GmailFixture): RecordedGmailClient {
  const calls: GmailFakeCall[] = [];
  const metadataReads: string[] = [];
  const bodyReads: string[] = [];
  const requestedHeaders = new Set<string>();
  const expired = new Set(fixture.expiredHistoryIds ?? []);
  const vanished = new Set(fixture.vanishedMessageIds ?? []);
  const historyPageSize = fixture.historyPageSize ?? 100;
  const listPageSize = fixture.listPageSize ?? 500;
  const messages = [...fixture.messages].sort(byHistoryId);

  const record = (method: string, detail: Readonly<Record<string, unknown>>): void => {
    calls.push({ method, detail });
  };

  /** Every planned refusal, in the order a real client would hit them. */
  const refusal = (): 'grant_revoked' | 'rate_limited' | null => {
    if (fixture.grantRevoked === true) return 'grant_revoked';
    if (fixture.rateLimited === true) return 'rate_limited';
    return null;
  };

  const find = (id: string): GmailFixtureMessage | undefined =>
    vanished.has(id) ? undefined : messages.find(message => message.id === id);

  return {
    calls,
    metadataReads,
    bodyReads,
    get requestedHeaders(): readonly string[] {
      return [...requestedHeaders];
    },

    authorizationUrl(config: GmailOAuthConfig, input): string {
      record('authorizationUrl', { scopes: input.scopes });
      const url = new URL(config.authorizationEndpoint);
      url.searchParams.set('client_id', config.clientId);
      url.searchParams.set('redirect_uri', config.redirectUri);
      url.searchParams.set('response_type', 'code');
      url.searchParams.set('scope', input.scopes.join(' '));
      url.searchParams.set('state', input.state);
      url.searchParams.set('code_challenge', input.codeChallenge);
      url.searchParams.set('code_challenge_method', 'S256');
      url.searchParams.set('access_type', 'offline');
      url.searchParams.set('prompt', 'consent');
      if (input.loginHint !== undefined) url.searchParams.set('login_hint', input.loginHint);
      return url.toString();
    },

    exchangeAuthorizationCode: async (_config, input): Promise<GmailTokenOutcome> => {
      record('exchangeAuthorizationCode', { code: input.code });
      await Promise.resolve();
      if (fixture.grantRevoked === true) return { ok: false, reason: 'grant_refused' };
      return {
        ok: true,
        grant: {
          accessToken: `fixture-access-${input.code}`,
          expiresAtEpochSeconds: Math.floor(Date.now() / 1000) + 3600,
          refreshToken: fixture.refreshToken ?? null,
          grantedScopes: [
            'https://www.googleapis.com/auth/gmail.readonly',
            'https://www.googleapis.com/auth/gmail.send',
          ],
        },
      };
    },

    refreshAccessToken: async (): Promise<GmailAccessOutcome> => {
      record('refreshAccessToken', {});
      await Promise.resolve();
      if (fixture.grantRevoked === true) return { ok: false, reason: 'grant_revoked' };
      return {
        ok: true,
        grant: { accessToken: 'fixture-access', expiresAtEpochSeconds: Math.floor(Date.now() / 1000) + 3600 },
      };
    },

    revokeRefreshToken: async (): Promise<void> => {
      record('revokeRefreshToken', {});
      await Promise.resolve();
    },

    getProfile: async (): Promise<GmailProfile> => {
      record('getProfile', {});
      await Promise.resolve();
      if (fixture.grantRevoked === true) {
        throw new GmailClientError('unexpected_status', 'the fixture grant is revoked', 401);
      }
      return { emailAddress: fixture.emailAddress, historyId: fixture.historyId };
    },

    watch: async (_access: GmailAccessGrant, input): Promise<GmailWatchOutcome> => {
      record('watch', { topicName: input.topicName });
      await Promise.resolve();
      if (fixture.grantRevoked === true) return { ok: false, reason: 'grant_revoked' };
      return {
        ok: true,
        watch: {
          historyId: fixture.historyId,
          expiresAtEpochMilliseconds:
            fixture.watchExpiresAtEpochMilliseconds ?? Date.now() + 7 * 24 * 3600 * 1000,
        },
      };
    },

    stopWatch: async (): Promise<void> => {
      record('stopWatch', {});
      await Promise.resolve();
    },

    listHistory: async (_access, request: GmailHistoryRequest): Promise<GmailHistoryOutcome> => {
      record('listHistory', { startHistoryId: request.startHistoryId, pageToken: request.pageToken ?? null });
      await Promise.resolve();
      const planned = refusal();
      if (planned !== null) return { ok: false, reason: planned };
      if (expired.has(request.startHistoryId)) return { ok: false, reason: 'history_expired' };

      const after = messages.filter(message => Number(message.historyId) > Number(request.startHistoryId));
      const offset = request.pageToken === undefined ? 0 : Number(request.pageToken);
      if (!Number.isInteger(offset) || offset < 0) {
        throw new GmailClientError('malformed_response', 'the fixture was given a page token it never issued');
      }
      const page = after.slice(offset, offset + historyPageSize);
      const records: GmailHistoryRecord[] = page.map(message => ({
        historyId: message.historyId,
        messageId: message.id,
        threadId: message.threadId,
        kind: 'message_added',
        labelIds: message.labelIds ?? [],
      }));
      const nextOffset = offset + page.length;
      return {
        ok: true,
        records,
        nextPageToken: nextOffset < after.length ? String(nextOffset) : null,
        historyId: fixture.historyId,
      };
    },

    listMessageIds: async (_access, request: GmailListRequest): Promise<GmailListOutcome> => {
      record('listMessageIds', {
        afterEpochSeconds: request.afterEpochSeconds,
        beforeEpochSeconds: request.beforeEpochSeconds,
        maxResults: request.maxResults,
        pageToken: request.pageToken ?? null,
      });
      await Promise.resolve();
      const planned = refusal();
      if (planned !== null) return { ok: false, reason: planned };

      const inRange = messages.filter(message => {
        const seconds = Math.floor(message.internalDateEpochMilliseconds / 1000);
        return seconds >= request.afterEpochSeconds && seconds < request.beforeEpochSeconds;
      });
      const offset = request.pageToken === undefined ? 0 : Number(request.pageToken);
      const size = Math.min(request.maxResults, listPageSize);
      const page = inRange.slice(offset, offset + size);
      const nextOffset = offset + page.length;
      return {
        ok: true,
        messageIds: page.map(message => message.id),
        nextPageToken: nextOffset < inRange.length ? String(nextOffset) : null,
      };
    },

    getMetadata: async (_access, messageId, headers): Promise<GmailMessageMetadata | null> => {
      record('getMetadata', { messageId, headers });
      metadataReads.push(messageId);
      for (const header of headers) requestedHeaders.add(header);
      await Promise.resolve();
      if (fixture.grantRevoked === true) {
        throw new GmailClientError('unexpected_status', 'the fixture grant is revoked', 401);
      }
      const message = find(messageId);
      if (message === undefined) return null;

      // Only the allowlist comes back, whatever the fixture holds: that is the
      // contract `format=metadata&metadataHeaders=` gives, and a fake that returned
      // more would hide a lane asking for a header it is not allowed to read.
      const wanted = new Set(headers.map(header => header.toLowerCase()));
      const allowed: Record<string, string> = {};
      for (const [name, value] of Object.entries(message.headers)) {
        if (wanted.has(name.toLowerCase())) allowed[name] = value;
      }
      return {
        id: message.id,
        threadId: message.threadId,
        internalDateEpochMilliseconds: message.internalDateEpochMilliseconds,
        labelIds: message.labelIds ?? [],
        headers: allowed,
        attachments: message.attachments ?? [],
        sizeEstimate: 1024,
      };
    },

    getBody: async (_access, messageId): Promise<GmailMessageBody | null> => {
      record('getBody', { messageId });
      bodyReads.push(messageId);
      await Promise.resolve();
      const message = find(messageId);
      if (message === undefined || message.body === undefined) return null;
      return { text: message.body, truncated: message.bodyTruncated ?? false };
    },
  };
}

/** The direction the fixture's labels imply, for a test asserting on its own data. */
export function fixtureDirection(message: GmailFixtureMessage): 'incoming' | 'outgoing' {
  return directionOfLabels(message.labelIds ?? []);
}
