import { createHash } from 'node:crypto';
import {
  GmailClientError,
  directionOfLabels,
  headerValue,
  type GmailAccessGrant,
  type GmailAccessOutcome,
  type GmailAttachmentReference,
  type GmailClient,
  type GmailHistoryChange,
  type GmailHistoryOutcome,
  type GmailHistoryRecord,
  type GmailHistoryRequest,
  type GmailListOutcome,
  type GmailListRequest,
  type GmailMessageBody,
  type GmailMessageMetadata,
  type GmailOAuthConfig,
  type GmailProfile,
  type GmailSendOutcome,
  type GmailSendRequest,
  type GmailSentSearchOutcome,
  type GmailTokenOutcome,
  type GmailWatchOutcome,
} from './gmailClient.ts';
import { compareHistoryIds } from './historyIds.ts';

/**
 * The recorded-fixture Gmail client.
 *
 * A fixture is a recording of one mailbox: its profile, the messages it holds with
 * their allowlisted headers, and the history records Gmail would replay from a given
 * cursor. The fake answers from that recording and records every call it was given,
 * so a test asserts two things the network could never tell it: what FSS asked for,
 * and what it did *not* ask for.
 *
 * The second is the interesting one. `metadataReads` and `bodyReads` are separate
 * lists, so "no body was fetched for a message that did not match" and "no attachment
 * bytes were ever requested" are assertions rather than hopes.
 *
 * The fake also reproduces the four failures the specification gives a defined
 * recovery to: an expired history cursor (12.3), a revoked grant (12.6), a rate
 * limit, and a message that has been deleted between the history page and the read.
 * Each is a flag on the fixture rather than a special client, because a test that
 * needs the failure halfway through a run needs one client, not two.
 *
 * It contains no credential, no real address and no real person. Every identifier is
 * generated by the test that builds the fixture.
 */

export interface GmailFixtureMessage {
  readonly id: string;
  readonly threadId: string;
  readonly internalDateEpochMilliseconds: number;
  readonly labelIds?: readonly string[] | undefined;
  readonly headers: Readonly<Record<string, string>>;
  readonly body?: string | undefined;
  readonly bodyTruncated?: boolean | undefined;
  readonly attachments?: readonly GmailAttachmentReference[] | undefined;
  /**
   * The id of the history record in which this message appeared. Orders the history
   * replay, and messages that share one id are *one* record carrying several messages,
   * as a Gmail `History` can.
   */
  readonly historyId: string;
}

export interface GmailFixture {
  readonly emailAddress: string;
  /** The mailbox's current history id: what `getProfile` and a watch return. */
  readonly historyId: string;
  readonly messages: readonly GmailFixtureMessage[];
  /** Cursors the fixture refuses with `history_expired` (12.3, Appendix G 13). */
  readonly expiredHistoryIds?: readonly string[] | undefined;
  readonly grantRevoked?: boolean | undefined;
  readonly rateLimited?: boolean | undefined;
  /** Ids the reads pretend are gone, as a message deleted between page and read. */
  readonly vanishedMessageIds?: readonly string[] | undefined;
  /** How many history records a page carries. Small in tests, 100 in Gmail. */
  readonly historyPageSize?: number | undefined;
  readonly listPageSize?: number | undefined;
  readonly watchExpiresAtEpochMilliseconds?: number | undefined;
  /** The refresh token a consent hands back. Generated by the test, never a literal. */
  readonly refreshToken?: string | undefined;
  /**
   * How `sendMessage` behaves. `accept` is the ordinary case.
   *
   * `indeterminate` is Appendix B's "any request bytes may have left": the fake
   * records the send, does *not* add it to the Sent folder, and reports that nobody
   * knows. `indeterminate_but_delivered` is the nastier half of scenario 5 — Gmail
   * accepted the message and dropped the response — so the fake records the send,
   * adds it to the Sent folder, and still reports that nobody knows.
   */
  readonly sendBehaviour?:
    | 'accept'
    | 'refuse'
    | 'indeterminate'
    | 'indeterminate_but_delivered'
    | undefined;
  readonly sendRefusalReason?:
    | 'grant_revoked'
    | 'rate_limited'
    | 'recipient_rejected'
    | 'provider_refusal'
    | undefined;
  /**
   * How many Sent-folder searches miss before the message is found.
   *
   * Appendix B's "Sent search finds nothing ... remain reconciling" followed by
   * "Sent search finds deterministic Message-ID". Gmail's Sent index is not
   * immediate, and a reconciliation that trusted the first miss would mark a
   * delivered message unknown.
   */
  readonly sentIndexingDelay?: number | undefined;
  /**
   * RFC Message-IDs the mailbox's Sent folder already holds when the client is built.
   *
   * A recording is of a mailbox, and a mailbox's Sent folder outlives the process that
   * sent into it. The restore drill runs in a different process from the seed that
   * sent (lane g59): the seed's client adds each delivered send to its own Sent folder,
   * reports the folder, and the drill's client is built with it here, so Appendix E
   * step 3's Sent search answers from what the earlier client delivered rather than
   * from an empty folder no Gmail mailbox would have.
   */
  readonly sentMessageIds?: readonly string[] | undefined;
  /**
   * The Sent folder's messages themselves, with their metadata (lane g73).
   *
   * `sentMessageIds` is enough for a search by Message-ID, which asks about a fence the
   * database knows. Appendix E step 3 also has to *list* the folder, for the sends whose
   * fence a restore lost, and a listing needs what Gmail returns for a message: an id, a
   * thread, an internal date, and the allowlisted headers (`Message-ID`, `To`,
   * `Subject`). Each one's `Message-ID` joins `sentMessageIds` for the search as well.
   *
   * Kept apart from `messages` on purpose: the inbox listing, the history replay and the
   * recovery sync answer from `messages` exactly as they did before this lane, so a
   * fixture that gains a Sent folder changes nothing any other read sees.
   */
  readonly sentMessages?: readonly GmailFixtureMessage[] | undefined;
}

/**
 * The Gmail id this fake gives the message it delivers with a given Message-ID.
 *
 * Derived from the Message-ID rather than counted, so two processes that each deliver
 * into "the same" recorded mailbox — a seed phase and the drill, which run as separate
 * tasks and merge their recordings (lane g59) — can never give two messages one id, and
 * a re-run can rebuild the recording of a message it did not send this time.
 */
export function recordedSentMessageId(rfcMessageId: string): string {
  return `sent-${createHash('sha256').update(rfcMessageId, 'utf8').digest('hex').slice(0, 20)}`;
}

/** The thread the fake files that message in: its own, as a first touch is. */
export function recordedSentThreadId(rfcMessageId: string): string {
  return `thread-${recordedSentMessageId(rfcMessageId)}`;
}

export interface GmailFakeCall {
  readonly method: string;
  readonly detail: Readonly<Record<string, unknown>>;
}

export interface RecordedGmailClient extends GmailClient {
  readonly calls: readonly GmailFakeCall[];
  /** Message ids `getMetadata` was called for, in order, including repeats. */
  readonly metadataReads: readonly string[];
  /** Message ids `getBody` was called for. Empty is the assertion that matters. */
  readonly bodyReads: readonly string[];
  /** Header names every metadata read asked for, deduplicated. */
  readonly requestedHeaders: readonly string[];
  /**
   * Every message this fake was asked to send, in order.
   *
   * The assertion that matters is almost always its *length*. Appendix B's whole
   * promise is that a given fence appears here at most once however many workers,
   * leases and crashes were involved, and a recording is the only way to say so:
   * the database can show one `sent` row after two sends just as easily as after one.
   */
  readonly sends: readonly GmailSendRequest[];
  /** RFC Message-IDs the Sent-folder search was run for, in order. */
  readonly sentSearches: readonly string[];
  /**
   * RFC Message-IDs the Sent folder holds now: the fixture's own, and every send this
   * client delivered (an `accept`, or an `indeterminate_but_delivered` whose response
   * was dropped). Not the refused or the indeterminate ones, which never arrived.
   */
  readonly sentMessageIds: readonly string[];
  /**
   * The Sent folder as a listing sees it (lane g73): the fixture's `sentMessages` and a
   * message for every send this client delivered, oldest first.
   */
  readonly sentMessages: readonly GmailFixtureMessage[];
}

// `BigInt`, through `compareHistoryIds`: a fixture near 2^53 must order the way Gmail
// does, or a test of the sync's lossless comparison would be a test of the fake's.
const byHistoryId = (left: GmailFixtureMessage, right: GmailFixtureMessage): number =>
  compareHistoryIds(left.historyId, right.historyId);

export function recordedGmailClient(fixture: GmailFixture): RecordedGmailClient {
  const calls: GmailFakeCall[] = [];
  const metadataReads: string[] = [];
  const bodyReads: string[] = [];
  const sends: GmailSendRequest[] = [];
  const sentSearches: string[] = [];
  /** RFC Message-IDs the Sent folder holds, whatever the caller was told. */
  const sentFolder = new Set<string>(fixture.sentMessageIds ?? []);
  /** The same folder's messages, by Gmail id, for the listing and the metadata read (g73). */
  const sentStore = new Map<string, GmailFixtureMessage>();
  for (const message of fixture.sentMessages ?? []) {
    sentStore.set(message.id, message);
    const header = headerValue(message.headers, 'Message-ID');
    if (header !== undefined) sentFolder.add(header);
  }
  const bySentAt = (left: GmailFixtureMessage, right: GmailFixtureMessage): number =>
    left.internalDateEpochMilliseconds - right.internalDateEpochMilliseconds || left.id.localeCompare(right.id);
  const sentFolderMessages = (): readonly GmailFixtureMessage[] => [...sentStore.values()].sort(bySentAt);
  const sentMessageFor = (rfcMessageId: string): GmailFixtureMessage | undefined =>
    [...sentStore.values()].find(message => headerValue(message.headers, 'Message-ID') === rfcMessageId);
  const searchesFor = new Map<string, number>();
  const requestedHeaders = new Set<string>();
  const expired = new Set(fixture.expiredHistoryIds ?? []);
  const vanished = new Set(fixture.vanishedMessageIds ?? []);
  const historyPageSize = fixture.historyPageSize ?? 100;
  const listPageSize = fixture.listPageSize ?? 500;
  // Read the fixture's list on every call rather than once. A test that adds a
  // message after the client exists is the ordinary case — Gmail receives mail while
  // FSS is running — and a snapshot taken at construction would make that invisible.
  const currentMessages = (): readonly GmailFixtureMessage[] => [...fixture.messages].sort(byHistoryId);

  const record = (method: string, detail: Readonly<Record<string, unknown>>): void => {
    calls.push({ method, detail });
  };

  /** Every planned refusal, in the order a real client would hit them. */
  const refusal = (): 'grant_revoked' | 'rate_limited' | null => {
    if (fixture.grantRevoked === true) return 'grant_revoked';
    if (fixture.rateLimited === true) return 'rate_limited';
    return null;
  };

  // The Sent folder is searched after the inbox fixture, so a metadata read of a
  // delivered message answers as Gmail would; nothing else lists those ids (lane g73).
  const find = (id: string): GmailFixtureMessage | undefined =>
    vanished.has(id) ? undefined : (currentMessages().find(message => message.id === id) ?? sentStore.get(id));

  return {
    calls,
    metadataReads,
    bodyReads,
    sends,
    sentSearches,
    get requestedHeaders(): readonly string[] {
      return [...requestedHeaders];
    },
    get sentMessageIds(): readonly string[] {
      return [...sentFolder];
    },
    get sentMessages(): readonly GmailFixtureMessage[] {
      return sentFolderMessages();
    },

    authorizationUrl(config: GmailOAuthConfig, input): string {
      record('authorizationUrl', { scopes: input.scopes });
      const url = new URL(config.authorizationEndpoint);
      url.searchParams.set('client_id', config.clientId);
      url.searchParams.set('redirect_uri', config.redirectUri);
      url.searchParams.set('response_type', 'code');
      url.searchParams.set('scope', input.scopes.join(' '));
      url.searchParams.set('state', input.state);
      url.searchParams.set('code_challenge', input.codeChallenge);
      url.searchParams.set('code_challenge_method', 'S256');
      url.searchParams.set('access_type', 'offline');
      url.searchParams.set('prompt', 'consent');
      if (input.loginHint !== undefined) url.searchParams.set('login_hint', input.loginHint);
      return url.toString();
    },

    exchangeAuthorizationCode: async (_config, input): Promise<GmailTokenOutcome> => {
      record('exchangeAuthorizationCode', { code: input.code });
      await Promise.resolve();
      if (fixture.grantRevoked === true) return { ok: false, reason: 'grant_refused' };
      return {
        ok: true,
        grant: {
          accessToken: `fixture-access-${input.code}`,
          expiresAtEpochSeconds: Math.floor(Date.now() / 1000) + 3600,
          refreshToken: fixture.refreshToken ?? null,
          grantedScopes: [
            'https://www.googleapis.com/auth/gmail.readonly',
            'https://www.googleapis.com/auth/gmail.send',
          ],
        },
      };
    },

    refreshAccessToken: async (): Promise<GmailAccessOutcome> => {
      record('refreshAccessToken', {});
      await Promise.resolve();
      if (fixture.grantRevoked === true) return { ok: false, reason: 'grant_revoked' };
      return {
        ok: true,
        grant: { accessToken: 'fixture-access', expiresAtEpochSeconds: Math.floor(Date.now() / 1000) + 3600 },
      };
    },

    revokeRefreshToken: async (): Promise<void> => {
      record('revokeRefreshToken', {});
      await Promise.resolve();
    },

    getProfile: async (): Promise<GmailProfile> => {
      record('getProfile', {});
      await Promise.resolve();
      if (fixture.grantRevoked === true) {
        throw new GmailClientError('unexpected_status', 'the fixture grant is revoked', 401);
      }
      return { emailAddress: fixture.emailAddress, historyId: fixture.historyId };
    },

    watch: async (_access: GmailAccessGrant, input): Promise<GmailWatchOutcome> => {
      record('watch', { topicName: input.topicName });
      await Promise.resolve();
      if (fixture.grantRevoked === true) return { ok: false, reason: 'grant_revoked' };
      return {
        ok: true,
        watch: {
          historyId: fixture.historyId,
          expiresAtEpochMilliseconds:
            fixture.watchExpiresAtEpochMilliseconds ?? Date.now() + 7 * 24 * 3600 * 1000,
        },
      };
    },

    stopWatch: async (): Promise<void> => {
      record('stopWatch', {});
      await Promise.resolve();
    },

    listHistory: async (_access, request: GmailHistoryRequest): Promise<GmailHistoryOutcome> => {
      record('listHistory', { startHistoryId: request.startHistoryId, pageToken: request.pageToken ?? null });
      await Promise.resolve();
      const planned = refusal();
      if (planned !== null) return { ok: false, reason: planned };
      if (expired.has(request.startHistoryId)) return { ok: false, reason: 'history_expired' };

      // Strictly after the start, as `startHistoryId` is documented: "Returns history
      // records after the specified startHistoryId."
      const after = currentMessages().filter(
        message => compareHistoryIds(message.historyId, request.startHistoryId) > 0,
      );
      // One record per history id, and a page is whole records, as Gmail's are: a
      // page boundary never falls inside a record.
      const grouped = new Map<string, GmailHistoryChange[]>();
      for (const message of after) {
        const change: GmailHistoryChange = {
          messageId: message.id,
          threadId: message.threadId,
          kind: 'message_added',
          labelIds: message.labelIds ?? [],
        };
        const changes = grouped.get(message.historyId);
        if (changes === undefined) grouped.set(message.historyId, [change]);
        else changes.push(change);
      }
      const all: GmailHistoryRecord[] = [...grouped].map(([id, changes]) => ({ id, changes }));
      const offset = request.pageToken === undefined ? 0 : Number(request.pageToken);
      if (!Number.isInteger(offset) || offset < 0) {
        throw new GmailClientError('malformed_response', 'the fixture was given a page token it never issued');
      }
      const records = all.slice(offset, offset + historyPageSize);
      const nextOffset = offset + records.length;
      return {
        ok: true,
        records,
        nextPageToken: nextOffset < all.length ? String(nextOffset) : null,
        historyId: fixture.historyId,
      };
    },

    listMessageIds: async (_access, request: GmailListRequest): Promise<GmailListOutcome> => {
      record('listMessageIds', {
        afterEpochSeconds: request.afterEpochSeconds,
        beforeEpochSeconds: request.beforeEpochSeconds,
        maxResults: request.maxResults,
        pageToken: request.pageToken ?? null,
      });
      await Promise.resolve();
      const planned = refusal();
      if (planned !== null) return { ok: false, reason: planned };

      const inRange = currentMessages().filter(message => {
        const seconds = Math.floor(message.internalDateEpochMilliseconds / 1000);
        return seconds >= request.afterEpochSeconds && seconds < request.beforeEpochSeconds;
      });
      const offset = request.pageToken === undefined ? 0 : Number(request.pageToken);
      const size = Math.min(request.maxResults, listPageSize);
      const page = inRange.slice(offset, offset + size);
      const nextOffset = offset + page.length;
      return {
        ok: true,
        messageIds: page.map(message => message.id),
        nextPageToken: nextOffset < inRange.length ? String(nextOffset) : null,
      };
    },

    getMetadata: async (_access, messageId, headers): Promise<GmailMessageMetadata | null> => {
      record('getMetadata', { messageId, headers });
      metadataReads.push(messageId);
      for (const header of headers) requestedHeaders.add(header);
      await Promise.resolve();
      if (fixture.grantRevoked === true) {
        throw new GmailClientError('unexpected_status', 'the fixture grant is revoked', 401);
      }
      const message = find(messageId);
      if (message === undefined) return null;

      // Only the allowlist comes back, whatever the fixture holds: that is the
      // contract `format=metadata&metadataHeaders=` gives, and a fake that returned
      // more would hide a lane asking for a header it is not allowed to read.
      const wanted = new Set(headers.map(header => header.toLowerCase()));
      const allowed: Record<string, string> = {};
      for (const [name, value] of Object.entries(message.headers)) {
        if (wanted.has(name.toLowerCase())) allowed[name] = value;
      }
      return {
        id: message.id,
        threadId: message.threadId,
        internalDateEpochMilliseconds: message.internalDateEpochMilliseconds,
        labelIds: message.labelIds ?? [],
        headers: allowed,
        attachments: message.attachments ?? [],
        sizeEstimate: 1024,
      };
    },

    getBody: async (_access, messageId): Promise<GmailMessageBody | null> => {
      record('getBody', { messageId });
      bodyReads.push(messageId);
      await Promise.resolve();
      const message = find(messageId);
      if (message === undefined || message.body === undefined) return null;
      return { text: message.body, truncated: message.bodyTruncated ?? false };
    },

    sendMessage: async (_access, request: GmailSendRequest): Promise<GmailSendOutcome> => {
      record('sendMessage', { to: request.to, rfcMessageId: request.rfcMessageId });
      // Recorded before any decision about what to report, because the recording is
      // "was this called", not "did it succeed". A fence that was dispatched twice
      // must show two entries even if both reported failure.
      sends.push(request);
      await Promise.resolve();
      const behaviour = fixture.sendBehaviour ?? 'accept';
      if (behaviour === 'refuse') {
        return { ok: false, outcome: 'refused', reason: fixture.sendRefusalReason ?? 'provider_refusal' };
      }
      if (behaviour === 'indeterminate') {
        return { ok: false, outcome: 'indeterminate', detail: 'the connection closed before a response' };
      }
      sentFolder.add(request.rfcMessageId);
      // The delivered message, as the Sent folder will list it (lane g73). Its internal
      // date is the wall clock, which is what Gmail stamps; its headers are the ones
      // FSS wrote and a metadata read with the allowlist would return.
      const messageId = recordedSentMessageId(request.rfcMessageId);
      const threadId = recordedSentThreadId(request.rfcMessageId);
      sentStore.set(messageId, {
        id: messageId,
        threadId,
        internalDateEpochMilliseconds: Date.now(),
        labelIds: ['SENT'],
        headers: {
          From: request.from,
          To: request.to,
          Subject: request.subject,
          'Message-ID': request.rfcMessageId,
        },
        historyId: fixture.historyId,
      });
      if (behaviour === 'indeterminate_but_delivered') {
        return { ok: false, outcome: 'indeterminate', detail: 'the response was dropped after delivery' };
      }
      return { ok: true, messageId, threadId };
    },

    searchSentByMessageId: async (_access, rfcMessageId): Promise<GmailSentSearchOutcome> => {
      record('searchSentByMessageId', { rfcMessageId });
      sentSearches.push(rfcMessageId);
      await Promise.resolve();
      const planned = refusal();
      if (planned !== null) return { ok: false, reason: planned };
      const attempt = (searchesFor.get(rfcMessageId) ?? 0) + 1;
      searchesFor.set(rfcMessageId, attempt);
      // A miss is a real answer: the index has not caught up yet.
      if (attempt <= (fixture.sentIndexingDelay ?? 0)) return { ok: true, found: null };
      if (!sentFolder.has(rfcMessageId)) return { ok: true, found: null };
      // The message's own ids when the folder holds it as a message, so a fence the
      // search reconciles and the listing's message agree about which Gmail message it is.
      const held = sentMessageFor(rfcMessageId);
      return {
        ok: true,
        found: {
          messageId: held?.id ?? recordedSentMessageId(rfcMessageId),
          threadId: held?.threadId ?? recordedSentThreadId(rfcMessageId),
        },
      };
    },

    listSentMessageIds: async (_access, request: GmailListRequest): Promise<GmailListOutcome> => {
      record('listSentMessageIds', {
        afterEpochSeconds: request.afterEpochSeconds,
        beforeEpochSeconds: request.beforeEpochSeconds,
        maxResults: request.maxResults,
        pageToken: request.pageToken ?? null,
      });
      await Promise.resolve();
      const planned = refusal();
      if (planned !== null) return { ok: false, reason: planned };

      // Gmail's `after:`/`before:` with epoch seconds: the same second arithmetic the
      // inbox listing uses above.
      const inRange = sentFolderMessages().filter(message => {
        if (vanished.has(message.id)) return false;
        const seconds = Math.floor(message.internalDateEpochMilliseconds / 1000);
        return seconds >= request.afterEpochSeconds && seconds < request.beforeEpochSeconds;
      });
      const offset = request.pageToken === undefined ? 0 : Number(request.pageToken);
      if (!Number.isInteger(offset) || offset < 0) {
        throw new GmailClientError('malformed_response', 'the fixture was given a page token it never issued');
      }
      const size = Math.min(request.maxResults, listPageSize);
      const page = inRange.slice(offset, offset + size);
      const nextOffset = offset + page.length;
      return {
        ok: true,
        messageIds: page.map(message => message.id),
        nextPageToken: nextOffset < inRange.length ? String(nextOffset) : null,
      };
    },
  };
}

/** The direction the fixture's labels imply, for a test asserting on its own data. */
export function fixtureDirection(message: GmailFixtureMessage): 'incoming' | 'outgoing' {
  return directionOfLabels(message.labelIds ?? []);
}
