import {createHash} from 'node:crypto';
import type {AnswerBlock} from '@fss/contracts';
import {replyDraftContextInputSchema,type ReplyDraftContextInput,type ReplyDraftContext,type ReplyComposerResult} from '../../contracts/src/replyComposer.ts';
import type {RepositoryContext} from '../db/workspaceScope.ts';
import {readMessage,readMessageBody} from '../mail/messages.ts';
import {directSendTargetOf} from '../mail/matching.ts';
import {readFirm} from '../crm/firms.ts';
import {decideFirmRead,firmReadIsAudited} from '../crm/authorization.ts';
import {recordCrmAuditEvent} from '../crm/audit.ts';
import {authorizationForMailbox} from '../outreach/authorization.ts';
import {readApprovedAnswerBlocks} from '../outreach/facts.ts';
import {firstSuppressed} from '../suppression/effective.ts';
import {listApplicableHolds} from '../policy/holds.ts';
import {workspaceBusinessZone} from '../research/ledger.ts';

/** No body is persisted here. Human drafting is independent of routine automation. */
export async function readReplyDraftContext(ctx:RepositoryContext,input:ReplyDraftContextInput):Promise<ReplyComposerResult<ReplyDraftContext>>{
 if(!replyDraftContextInputSchema.safeParse(input).success)return {ok:false,reason:'invalid_input'};
 const actor=ctx.scope.actor;if(actor.kind!=='user')return {ok:false,reason:'human_required'};
 const message=await readMessage(ctx,input.messageId);if(!message)return {ok:false,reason:'message_unavailable'};
 const target=await directSendTargetOf(ctx,message.id);if(!target?.contactId)return {ok:false,reason:'ambiguous_sender'};
 const firm=await readFirm(ctx,target.firmId);if(!firm||firm.status!=='active'||decideFirmRead(ctx,firm)!=='assigned_or_admin')return {ok:false,reason:'not_assigned'};
 const mailbox=(await ctx.db.query<{owner_user_id:string;email_address:string;provider_account_id:string|null;status:string;sync_state:string;generation:number}>('SELECT owner_user_id,email_address,provider_account_id,status,sync_state,generation FROM mailboxes WHERE workspace_id=$1 AND id=$2',[ctx.scope.workspaceId,message.mailboxId])).rows[0];
 if(!mailbox||mailbox.owner_user_id!==firm.assigned_user_id||actor.role!=='admin'&&actor.userId!==mailbox.owner_user_id)return {ok:false,reason:'owner_changed'};
 const auth=await authorizationForMailbox(ctx,message.mailboxId);if(!auth.allowed||auth.revision===null||mailbox.status!=='connected'||mailbox.sync_state!=='ready')return {ok:false,reason:'mailbox_unavailable'};
 const body=await readMessageBody(ctx,message.id);
 if(message.direction!=='incoming'||!message.matched||message.metadataOnly||!message.headerFrom||!message.rfcMessageId||!body||body.truncated||message.listId!==null||message.autoSubmitted!==null&&message.autoSubmitted!=='no')return {ok:false,reason:'message_unavailable'};
 const routes=(await ctx.db.query<{id:string;version:number;address:string;contact_id:string}>(`SELECT e.id,e.version,e.address,e.contact_id FROM email_addresses e JOIN contacts c ON c.workspace_id=e.workspace_id AND c.id=e.contact_id AND c.firm_id=e.firm_id WHERE e.workspace_id=$1 AND e.firm_id=$2 AND e.retired_at IS NULL AND e.eligibility='usable' AND e.technical_validation='passed' AND e.address=ANY($3::text[]) ORDER BY e.address LIMIT 21`,[ctx.scope.workspaceId,firm.id,[message.headerFrom,...message.headerTo,...message.headerCc]])).rows;
 const own=(await ctx.db.query<{address:string}>(`SELECT email_address AS address FROM mailboxes WHERE workspace_id=$1 UNION SELECT email_address AS address FROM mailbox_accounts WHERE workspace_id=$1`,[ctx.scope.workspaceId])).rows;
 const recipientOptions=routes.filter(r=>!own.some(identity=>identity.address===r.address)&&routes.filter(other=>other.address===r.address).length===1).map(r=>({address:r.address,contactId:r.contact_id}));
 const sender=recipientOptions.filter(r=>r.address===message.headerFrom&&r.contactId===target.contactId);
 if(sender.length!==1||recipientOptions.length>20)return {ok:false,reason:'sender_unverified'};
 const envelope={to:[...(input.envelope?.to??[sender[0]!.address])],cc:[...(input.envelope?.cc??[])]};
 const recipients=[...envelope.to,...envelope.cc];
 if(new Set(recipients).size!==recipients.length||recipients.some(address=>!recipientOptions.some(r=>r.address===address))||!envelope.to.includes(sender[0]!.address))return {ok:false,reason:'recipient_unverified'};
 if(await firstSuppressed(ctx,[{scope:'firm',canonicalKey:firm.id},...recipients.map(address=>({scope:'handle' as const,canonicalKey:address}))],'email'))return {ok:false,reason:'conversation_stopped'};
 const holds=await listApplicableHolds(ctx,{actionKind:'email_send',firmId:firm.id,opportunityId:target.opportunityId??undefined,ownerUserId:mailbox.owner_user_id,mailboxId:message.mailboxId,channel:'email'});
 const answered=(await ctx.db.query(`SELECT 1 FROM mail_message_effects e JOIN mail_messages o ON o.workspace_id=e.workspace_id AND o.id=e.mail_message_id WHERE e.workspace_id=$1 AND o.mailbox_id=$2 AND o.direction='outgoing' AND e.effect_kind='direct_send_conversation' AND e.detail->>'firmId'=$3 AND o.provider_thread_id=$4 AND e.detail->'recipientContactIds' ? $5 AND o.internal_date>$6::timestamptz LIMIT 1`,[ctx.scope.workspaceId,message.mailboxId,firm.id,message.providerThreadId,target.contactId,message.internalDate])).rows[0];
 if(answered)return {ok:false,reason:'answered_manually'};
 const thread=(await ctx.db.query<{id:string;direction:'incoming'|'outgoing';internal_date:Date;body_text:string|null;truncated:boolean|null}>(`SELECT m.id,m.direction,m.internal_date,b.body_text,b.truncated FROM mail_messages m LEFT JOIN mail_message_bodies b ON b.workspace_id=m.workspace_id AND b.mail_message_id=m.id WHERE m.workspace_id=$1 AND m.mailbox_id=$2 AND m.provider_thread_id=$3 ORDER BY m.internal_date,m.id LIMIT 21`,[ctx.scope.workspaceId,message.mailboxId,message.providerThreadId])).rows;
 if(thread.length>20)return {ok:false,reason:'context_too_large'};
 if(thread.filter(m=>m.direction==='incoming').at(-1)?.id!==message.id)return {ok:false,reason:'thread_changed'};
 if(thread.some(m=>m.body_text===null||m.truncated))return {ok:false,reason:'context_incomplete'};
 const catalog=(await ctx.db.query<{block_id:string;version:number;kind:AnswerBlock['kind'];text:string;approved_at:Date}>(`SELECT v.* FROM outreach_answer_blocks b JOIN outreach_answer_block_versions v ON v.workspace_id=b.workspace_id AND v.block_id=b.id AND v.version=b.current_version WHERE b.workspace_id=$1 AND v.approved_at IS NOT NULL AND v.retired_at IS NULL ORDER BY b.id LIMIT 51`,[ctx.scope.workspaceId])).rows;
 if(catalog.length>50)return {ok:false,reason:'facts_catalogue_too_large'};
 const availableFacts=catalog.map(b=>({id:b.block_id,version:b.version,kind:b.kind,text:b.text,approvedAt:b.approved_at.toISOString(),retiredAt:null}));
 const refs=input.factRefs??(availableFacts.length<=20?availableFacts.map(b=>({id:b.id,version:b.version})):[]);
 if(new Set(refs.map(r=>r.id)).size!==refs.length)return {ok:false,reason:'invalid_input'};
 const selected=refs.length?await readApprovedAnswerBlocks(ctx,refs):{ok:true as const,value:[]};if(!selected.ok)return {ok:false,reason:selected.reason};
 const meetingRows=(await ctx.db.query<{id:string;state:ReplyDraftContext['bookings'][number]['state'];starts_at:Date;ends_at:Date}>(`SELECT id,state,starts_at,ends_at FROM meetings WHERE workspace_id=$1 AND firm_id=$2 ORDER BY starts_at DESC,id LIMIT 21`,[ctx.scope.workspaceId,firm.id])).rows;
 if(meetingRows.length>20)return {ok:false,reason:'context_too_large'};
 const bookings=meetingRows.map(m=>({id:m.id,state:m.state,startsAt:m.starts_at.toISOString(),endsAt:m.ends_at.toISOString()}));
 const plan=target.outreachPlanId?(await ctx.db.query('SELECT id,revision,state,owner_user_id,mailbox_id FROM outreach_plans WHERE workspace_id=$1 AND id=$2 AND firm_id=$3',[ctx.scope.workspaceId,target.outreachPlanId,firm.id])).rows[0]:null;
 const opportunity=target.opportunityId?(await ctx.db.query('SELECT id,status,control_mode,control_mode_changed_at,stage_id FROM opportunities WHERE workspace_id=$1 AND id=$2 AND firm_id=$3',[ctx.scope.workspaceId,target.opportunityId,firm.id])).rows[0]:null;
 const confirmation=(await ctx.db.query('SELECT id,disposition FROM mail_reply_confirmations WHERE workspace_id=$1 AND mail_message_id=$2',[ctx.scope.workspaceId,message.id])).rows[0]??null;
 const source={messageId:message.id,firmId:firm.id,contactId:target.contactId,authorUserId:actor.userId,mailboxId:message.mailboxId,mailboxOwnerUserId:mailbox.owner_user_id,authorAddress:mailbox.email_address,authorizationRevision:auth.revision,subject:message.subject??'',senderAddress:message.headerFrom,providerThreadId:message.providerThreadId,inReplyTo:message.rfcMessageId,references:[...new Set([...message.referenceMessageIds,message.rfcMessageId])],observedTo:[...message.headerTo],observedCc:[...message.headerCc],replyToMetadata:'unavailable' as const,envelope,recipientOptions,messageText:body.text,priorContext:thread.filter(m=>m.id!==message.id).map(m=>({direction:m.direction,text:m.body_text!})),facts:selected.value};
 const sourceRevision=createHash('sha256').update(JSON.stringify({source,bookings,plan,opportunity,confirmation,sourceZone:firm.time_zone??await workspaceBusinessZone(ctx),assignedUserId:firm.assigned_user_id,matchId:target.id,mailboxAccountId:mailbox.provider_account_id,mailboxGeneration:mailbox.generation,threadIds:thread.map(m=>m.id),routes,holds})).digest('hex');
 if(firmReadIsAudited(ctx,firm))await recordCrmAuditEvent(ctx,{action:'reply_composer.context_read',subjectKind:'mail_message',subjectId:message.id});
 return {ok:true,value:{...source,bookings,sourceRevision,availableFacts}};
}
