import {randomUUID} from 'node:crypto';
import {beforeAll,afterAll,it,expect} from 'vitest';
import {createTestDatabase,type TestDatabase} from '../../db/testing/testDatabase.ts';
import {seedTwoWorkspaces,type TwoWorkspaces} from '../db/support/fixtures.ts';
import {repositoryContext,workspaceScope} from '../../db/workspaceScope.ts';
import {withTransaction} from '../../db/queryable.ts';
import {saveSocialPost,approveSocialPost,requestSocialCancellation,readSocialPost} from '../../social/posts.ts';
let db:TestDatabase,seed:TwoWorkspaces,accountId:string;
const ctx=(beta=false)=>{const s=beta?seed.beta:seed.alpha;return repositoryContext(workspaceScope(s.workspaceId,{kind:'user',userId:s.admin.userId,role:'admin'}),db.session);};
const tx=<T>(fn:()=>Promise<T>)=>withTransaction(db.session,fn);
const draft=()=>({accountId,text:'After-hours maintenance should not need your personal number.',images:[],publishAt:new Date(Date.now()+86400_000).toISOString(),zone:'America/New_York'});
beforeAll(async()=>{db=await createTestDatabase();seed=await seedTwoWorkspaces(db.session);accountId=randomUUID();await db.session.query("INSERT INTO social_accounts(workspace_id,id,owner_user_id,platform,external_id,display_name,account_kind,state,adapter_version,verified_at,max_schedule_days) VALUES($1,$2,$3,'linkedin','fixture-david','David','profile','connected','fixture-v1',now(),30)",[seed.alpha.workspaceId,accountId,seed.alpha.admin.userId]);});afterAll(async()=>db.drop());
it('freezes exact account, text, time and revision; an unscheduled edit invalidates approval',async()=>{
 const p=await tx(()=>saveSocialPost(ctx(),draft()));if(!p.ok)throw new Error(p.reason);
 const a=await tx(()=>approveSocialPost(ctx(),{postId:p.value.postId,expectedRevision:1}));expect(a.ok).toBe(true);
 if(!a.ok)throw new Error(a.reason);expect(a.value.fingerprint).toMatch(/^[a-f0-9]{64}$/);
 expect(await tx(()=>saveSocialPost(ctx(),{...draft(),postId:p.value.postId,expectedRevision:0}))).toEqual({ok:false,reason:'stale_revision'});
 const e=await tx(()=>saveSocialPost(ctx(),{...draft(),postId:p.value.postId,expectedRevision:1,text:'Updated copy.'}));expect(e).toMatchObject({ok:true,value:{revision:2,state:'draft'}});
 expect(await tx(()=>approveSocialPost(ctx(),{postId:p.value.postId,expectedRevision:1}))).toEqual({ok:false,reason:'stale_revision'});
 expect(await readSocialPost(ctx(true),p.value.postId)).toBeNull();
 const a2=await tx(()=>approveSocialPost(ctx(),{postId:p.value.postId,expectedRevision:2}));if(!a2.ok)throw new Error(a2.reason);expect(a2.value.fingerprint).not.toBe(a.value.fingerprint);
});
it('requires a future instant, verified destination and a Facebook Page; free X cannot become a thread',async()=>{
 const p=await tx(()=>saveSocialPost(ctx(),{...draft(),publishAt:new Date(Date.now()-60000).toISOString()}));if(!p.ok)throw new Error(p.reason);
 expect(await tx(()=>approveSocialPost(ctx(),{postId:p.value.postId,expectedRevision:1}))).toEqual({ok:false,reason:'schedule_in_past'});
 const id=randomUUID();await db.session.query("INSERT INTO social_accounts(workspace_id,id,owner_user_id,platform,external_id,display_name,account_kind,state) VALUES($1,$2,$3,'facebook','fixture-profile','David','profile','unsupported')",[seed.alpha.workspaceId,id,seed.alpha.admin.userId]);
 const facebook=await tx(()=>saveSocialPost(ctx(),{...draft(),accountId:id}));if(!facebook.ok)throw new Error(facebook.reason);
 expect(await tx(()=>approveSocialPost(ctx(),{postId:facebook.value.postId,expectedRevision:1}))).toEqual({ok:false,reason:'facebook_page_required'});
});
it('keeps the actual schedule while cancellation is pending and never calls a published post cancelled',async()=>{
 const p=await tx(()=>saveSocialPost(ctx(),draft()));if(!p.ok)throw new Error(p.reason);
 await tx(()=>approveSocialPost(ctx(),{postId:p.value.postId,expectedRevision:1}));
 await db.session.query("UPDATE social_post_revisions SET state='scheduled' WHERE workspace_id=$1 AND post_id=$2",[seed.alpha.workspaceId,p.value.postId]);
 expect(await tx(()=>saveSocialPost(ctx(),{...draft(),postId:p.value.postId,expectedRevision:1,text:'Replacement'}))).toEqual({ok:false,reason:'cancel_before_edit'});
 expect(await tx(()=>requestSocialCancellation(ctx(),{postId:p.value.postId,expectedRevision:1}))).toMatchObject({ok:true,value:{state:'cancellation_pending',text:draft().text}});
 await db.session.query("UPDATE social_post_revisions SET state='published' WHERE workspace_id=$1 AND post_id=$2",[seed.alpha.workspaceId,p.value.postId]);
 expect(await tx(()=>requestSocialCancellation(ctx(),{postId:p.value.postId,expectedRevision:1}))).toEqual({ok:false,reason:'already_published'});
});
it('rejects originals, removed images, and content beyond ordinary free-account limits',async()=>{
 const {registerSocialAsset,completeSocialAsset,deleteSocialAsset}=await import('../../social/assets.ts');
 const original={sha256:'a'.repeat(64),bytes:100,mime:'image/png' as const,origin:{kind:'screenshot' as const,sourceUrl:null,usageNote:null}};
 const a=await tx(()=>registerSocialAsset(ctx(),original));if(!a.ok)throw new Error(a.reason);await tx(()=>completeSocialAsset(ctx(),{...a.value,verified:original}));
 const p=await tx(()=>saveSocialPost(ctx(),{...draft(),images:[{assetId:a.value.assetId,version:1,altText:'Test screenshot'}]}));if(!p.ok)throw new Error(p.reason);
 expect(await tx(()=>approveSocialPost(ctx(),{postId:p.value.postId,expectedRevision:1}))).toEqual({ok:false,reason:'image_unavailable'});
 const d=await tx(()=>registerSocialAsset(ctx(),{...original,assetId:a.value.assetId,expectedVersion:1,width:10,height:10}));if(!d.ok)throw new Error(d.reason);await tx(()=>completeSocialAsset(ctx(),{...d.value,verified:original}));
 const e=await tx(()=>saveSocialPost(ctx(),{...draft(),postId:p.value.postId,expectedRevision:1,images:[{assetId:a.value.assetId,version:2,altText:'Test screenshot'}]}));expect(e.ok).toBe(true);
 expect((await tx(()=>approveSocialPost(ctx(),{postId:p.value.postId,expectedRevision:2}))).ok).toBe(true);
 await tx(()=>deleteSocialAsset(ctx(),a.value.assetId));expect(await tx(()=>approveSocialPost(ctx(),{postId:p.value.postId,expectedRevision:2}))).toEqual({ok:false,reason:'image_unavailable'});
 const x=randomUUID();await db.session.query("INSERT INTO social_accounts(workspace_id,id,owner_user_id,platform,external_id,display_name,account_kind,state,adapter_version,verified_at,max_schedule_days) VALUES($1,$2,$3,'x','fixture-x','David','profile','connected','fixture-v1',now(),30)",[seed.alpha.workspaceId,x,seed.alpha.admin.userId]);
 const overweight=await tx(()=>saveSocialPost(ctx(),{...draft(),accountId:x,text:'界'.repeat(141)}));if(!overweight.ok)throw new Error(overweight.reason);expect(await tx(()=>approveSocialPost(ctx(),{postId:overweight.value.postId,expectedRevision:1}))).toEqual({ok:false,reason:'content_needs_edit'});
 const xp=await tx(()=>saveSocialPost(ctx(),{...draft(),accountId:x,text:'x'.repeat(281)}));if(!xp.ok)throw new Error(xp.reason);expect(await tx(()=>approveSocialPost(ctx(),{postId:xp.value.postId,expectedRevision:1}))).toEqual({ok:false,reason:'content_needs_edit'});
});
