import {outreachSenderStandingV2ResponseSchema} from '@fss/contracts';
import {QualificationPanel} from '../sourcing/QualificationPanel.tsx';
import {useCallback,useEffect,useReducer,useRef,useState} from 'react';
import type {OutreachControl,OutreachCohortPreview,OutreachMutation,OutreachSenderStandingResponse,OutreachSenderStandingV2Response,ProviderIncidentView} from '@fss/contracts';
import type {OperationInput,OperationOutput} from '../../shared/operations.ts';
import {operations} from '../app/bridges.ts';
import {useSessionEpoch} from '../app/drafts.tsx';
import {navigate} from '../routes.ts';
import {noDefiniteAnswer} from '../today/afterCallModel.ts';
import {Button} from '../ui/button.tsx';
import {Input} from '../ui/input.tsx';
import {Section} from '../settings/Group.tsx';
import {ApprovedFactsEditor,type FactDraft} from './ApprovedFactsEditor.tsx';
export interface OutreachPorts {
 read():Promise<OperationOutput<'outreach.control'>>;
 standing?():Promise<OperationOutput<'outreach.senderStanding'>|OperationOutput<'outreach.senderStandingV2'>>;
 preview(input:OperationInput<'outreach.preview'>):Promise<OperationOutput<'outreach.preview'>>;
 mutate(input:OutreachMutation):Promise<OperationOutput<'outreach.mutate'>>;
}
const api=()=>{const a=operations();if(!a)throw new Error('unavailable');return a;};
const defaults:OutreachPorts={read:()=>api().read('outreach.control',{}),standing:()=>api().read('outreach.senderStandingV2',{}),preview:i=>api().read('outreach.preview',i),mutate:i=>api().command('outreach.mutate',i)};
type Policy={expectedRevision:number;enabled:boolean;sequenceVersionId:string|null;bookingUrl:string|null};
interface Memory {open:boolean;view:OutreachControl|null;standing:OutreachSenderStandingResponse|OutreachSenderStandingV2Response|null;busy:boolean;generation:number;message:string|null;pending:OutreachMutation|null;sender:string;autoSequence:string|null;fact:FactDraft;factRefreshRequired:boolean;policy:Policy|null;selected:string[];email:string;call:string;reviewed:boolean;preview:OutreachCohortPreview|null;listeners:Set<()=>void>}
const fresh=():Memory=>({open:false,view:null,standing:null,busy:false,generation:0,message:null,pending:null,sender:'',autoSequence:null,fact:{kind:'product',text:''},factRefreshRequired:false,policy:null,selected:[],email:'',call:'',reviewed:false,preview:null,listeners:new Set()});
const sessions=new WeakMap<object,Memory>();
function useMemory(){const epoch=useSessionEpoch(),[fallback]=useState(fresh),[,bump]=useReducer((n:number)=>n+1,0);let found=epoch?sessions.get(epoch):fallback;if(!found){found=fresh();sessions.set(epoch!,found);}const m=found;useEffect(()=>{const notify=()=>bump();m.listeners.add(notify);return()=>{m.listeners.delete(notify);m.generation++;m.busy=false;};},[m]);return {m,touch:useCallback(()=>{for(const fn of m.listeners)fn();},[m])};}
const refusal=(reason:string|null)=>({configuration_required:'Choose an authorized sender and an approved five-email sequence.',configuration_incomplete:'Choose both a sender and an approved five-email sequence.',owner_changed:'Choose a sender that you own.',owner_inactive:'The configured owner is no longer active.',approved_email_sequence_required:'Choose a published five-email sequence with approved content.',mailbox_binding_changed:'Sender authorization changed. Save the configuration and evaluate it again.',sequence_binding_changed:'Sequence content changed. Save the configuration and evaluate it again.',evaluation_required:'Evaluation is still required.',evaluation_mismatch:'Evaluation no longer matches the current configuration.',activation_not_available:'Automatic email admission is not available yet. Sending and authentication verification are still required.',stale_revision:'This changed elsewhere. Refresh before saving.',stale_version:'This fact changed elsewhere. Refresh and compare it with your draft.',preview_changed:'The selected firms or sender changed. Preview the cohort again.',mailbox_not_authorized:'Choose a connected, authorized sender that you own.',approved_reply_content_required:'Choose a published one-email sequence and approve at least one answer fact.',campaign_sequence_required:'Choose an approved sequence for this outreach lane.',qualification_requires_review:'Review the evidence before enabling these firms.',one_reply_sequence_required:'Choose a published sequence with exactly one approved email.',booking_link_invalid:'Use your public HTTPS Cal.com booking link.'}[reason??'']??'The action could not be completed. Refresh and review the current settings.');
const standingReason=(reason:string)=>({unresolved_submission:'A previous send still needs reconciliation.',authentication_failing:'Sending is paused or the recorded authentication checks are incomplete.',mailbox_disconnected:'Reconnect this mailbox before sending.',coverage_incomplete:'Mailbox sync coverage needs verification before sending.',coverage_unproven:'Mailbox sync coverage needs verification.',coverage_stale:'Mailbox sync needs to catch up before sending.',owner_inactive:'The mailbox owner is inactive.'}[reason]??'Sending is held until the current mailbox issue is resolved.');
const incidentSentence=(incident:ProviderIncidentView):string=>{
 if(incident.state==='waiting'&&incident.retryAt!==null)return `Provider cooldown: sending waits until ${new Date(incident.retryAt).toLocaleString()}. Current checks still apply afterwards.`;
 if(incident.reason==='unresolved_submission')return 'A previous send still needs reconciliation. Sending remains held.';
 if(incident.state==='revalidation_due')return 'Cooldown has ended. Current mailbox checks must pass before sending can resume.';
 if(incident.classification==='authentication')return 'Authentication requires review. Sending remains held.';
 if(incident.classification==='reputation')return 'Sender reputation requires review. Sending remains held.';
 return 'This provider incident needs review. Sending remains held.';
};
function currentIncidents(standing:OutreachSenderStandingResponse|OutreachSenderStandingV2Response|null,mailboxId:string):ProviderIncidentView[]|null{
 const parsed=outreachSenderStandingV2ResponseSchema.safeParse(standing);
 return parsed.success?parsed.data.senders.find(sender=>sender.mailboxId===mailboxId)?.incidents??null:null;
}
const smallSelect='rounded-md border border-input bg-background p-2 text-sm max-w-full';
export function OutreachSection({enabled,ports=defaults,initialMailboxId}:{enabled:boolean;ports?:OutreachPorts;initialMailboxId?:string}){
 const {m,touch}=useMemory(),ref=useRef(ports),focusedTarget=useRef<string|null>(null);ref.current=ports;
 const accept=(v:OutreachControl)=>{m.view=v;if(initialMailboxId&&focusedTarget.current!==initialMailboxId){m.sender=v.senders.some(sender=>sender.id===initialMailboxId)?initialMailboxId:'';focusedTarget.current=initialMailboxId;m.preview=null;m.reviewed=false;if(!m.sender)m.message='The requested sender is no longer available.';}if(m.autoSequence===null)m.autoSequence=v.emailAdmission.sequenceVersionId??'';if(!m.sender&&!initialMailboxId)m.sender=v.emailAdmission.mailboxId??v.senders[0]?.id??'';if(!m.policy)m.policy={expectedRevision:v.settings.revision,enabled:v.settings.enabled,sequenceVersionId:v.settings.sequenceVersionId,bookingUrl:v.settings.bookingUrl};};
 const readStanding=async(g:number)=>{m.standing=null;try{const r=await ref.current.standing?.();if(g===m.generation)m.standing=r?.view??null;}catch{if(g===m.generation)m.standing=null;}};
 const load=async()=>{const g=++m.generation;m.busy=true;touch();try{const [result]=await Promise.allSettled([ref.current.read(),readStanding(g)]);if(g!==m.generation)return;if(result.status==='rejected')throw result.reason;const r=result.value;if(r.view)accept(r.view);else m.message=refusal(r.reason);}catch{if(g===m.generation)m.message='Could not refresh outreach. Your draft is kept.';}finally{if(g===m.generation){m.busy=false;touch();}}};
 const currentLoad=useRef(load);currentLoad.current=load;
 useEffect(()=>{if(!initialMailboxId)return;focusedTarget.current=null;m.open=true;void currentLoad.current();},[initialMailboxId,m]);
 const perform=async(p:OutreachMutation)=>{if(m.busy||!enabled)return;const g=++m.generation;m.pending=p;m.busy=true;touch();try{const r=await ref.current.mutate(p);if(g!==m.generation)return;if(r.accepted){m.pending=null;if(p.action==='policy')m.policy=null;if(p.action==='email_admission')m.autoSequence=null;if(p.action==='fact_save'){m.fact={kind:'product',text:''};m.factRefreshRequired=false;}if(p.action==='cohort_enable'){m.preview=null;m.selected=[];m.reviewed=false;}if(r.view)accept(r.view);await readStanding(g);if(g!==m.generation)return;m.message=r.view?'Saved. Sending controls still apply.':'Saved. Refresh to read the latest settings.';}else if(noDefiniteAnswer(r.reason))m.message='No definite answer. Retry the same action.';else{m.pending=null;if(p.action==='fact_save'&&r.reason==='stale_version')m.factRefreshRequired=true;m.message=refusal(r.reason);}}catch{if(g===m.generation)m.message='No definite answer. Retry the same action.';}finally{if(g===m.generation){m.busy=false;touch();}}};
 const input=():OperationInput<'outreach.preview'>=>({mailboxId:m.sender,candidateIds:[...m.selected],emailSequenceVersionId:m.email||null,callSequenceVersionId:m.call||null});
 const preview=async()=>{if(m.busy||!enabled)return;const g=++m.generation;m.busy=true;m.preview=null;touch();try{const r=await ref.current.preview(input());if(g!==m.generation)return;m.preview=r.view;if(!r.view)m.message=refusal(r.reason);}catch{if(g===m.generation)m.message='Could not preview this cohort.';}finally{if(g===m.generation){m.busy=false;touch();}}};
 const blocked=!enabled||m.busy||m.pending!==null,box=m.view?.senders.find(s=>s.id===m.sender),senderStanding=m.standing?.senders.find(s=>s.mailboxId===m.sender),standing=senderStanding?.standing,incidents=currentIncidents(m.standing,m.sender);
 const change=()=>{m.preview=null;m.reviewed=false;touch();};
 return <Section title="Outreach"><Button variant="quiet" aria-expanded={m.open} onClick={()=>{m.open=!m.open;touch();if(m.open)void load();}}>Outreach setup</Button>
 {m.open?<div className="space-y-6 pt-3">
  {m.message?<p role="status" className="text-sm">{m.message}</p>:null}
  {m.pending?<Button disabled={m.busy||!enabled} onClick={()=>{if(m.pending)void perform(m.pending);}}>Retry outreach action</Button>:null}
  <Button variant="quiet" disabled={m.busy} onClick={()=>void load()}>Refresh outreach</Button>
  <fieldset className="space-y-2"><legend className="font-medium">Sender</legend>
   <select aria-label="Outreach sender" className={smallSelect} value={m.sender} disabled={blocked} onChange={e=>{m.sender=e.target.value;change();}}><option value="">Choose a sender</option>{m.view?.senders.map(s=><option key={s.id} value={s.id}>{s.address}</option>)}</select>
   {box?<><p className="text-sm">{box.sendingEnabled?'Domain sending enabled':'Sending paused'}</p><p className="text-sm text-muted-foreground">Authorization applies only to this connected mailbox. The sending switch stays in Sending settings.</p>
   {standing?<div className="space-y-1 text-sm" aria-label="Sender standing">
    <p>Current allowance: {standing.effectiveCap} emails per day, including follow-ups.</p>
    <p>Earned history: {standing.healthySendingDays} healthy sending days · {standing.earnedCap} emails per day.</p>
    {standing.recovery?.active?<p>Inactivity recovery: {standing.recovery.qualifyingDays%5} of 5 qualifying days completed at this stage; {standing.recovery.nextStageAfterDays} more required before the next stage.</p>:null}
    <p>{standing.activityBasis==='confirmed_send'&&standing.lastActivityAt?`Last observed send: ${new Date(standing.lastActivityAt).toLocaleString()} · ${standing.inactivityDays} calendar days ago.`:`No confirmed sending activity observed. Inactivity is measured from mailbox creation (${standing.inactivityDays} calendar days).`}</p>
    {incidents===null?<p>Provider incident details are unavailable. Refresh to check.</p>:incidents.length?<ul aria-label="Provider incidents">{incidents.map(incident=><li key={incident.id}>{incidentSentence(incident)}</li>)}</ul>:null}
    {standing.readiness.ready?<p>Current mailbox checks pass. Each send still requires its normal safety checks.</p>:<ul>{standing.readiness.reasons.map(reason=><li key={reason}>{standingReason(reason)}</li>)}</ul>}
    <p className="text-muted-foreground">This is a ceiling, not a daily target. Recovery needs qualifying activity and passing checks; waiting alone does not raise it. These checks do not prove inbox placement.</p>
   </div>:<p className="text-sm">Current sender standing is unavailable. Refresh to check the allowance and recovery status.</p>}
   <Button size="sm" disabled={blocked||!box.connected} onClick={()=>void perform({action:'authorization',mailboxId:box.id,expectedRevision:box.authorizationRevision,enabled:!box.authorized,basis:'owner_reported_google_permission',commandId:crypto.randomUUID()})}>{box.authorized?'Revoke sender authorization':'Authorize this sender'}</Button></>:null}
  </fieldset>
  {m.view?<fieldset className="space-y-3"><legend className="font-medium">Automatic email admission</legend>
   <p className="text-sm">Off · no prospects are admitted automatically.</p>
   <p className="text-sm text-muted-foreground">Save the sender and reusable sequence for later evaluation. Saving clears previous evaluation and does not enroll or email anyone.</p>
   <label className="grid gap-1 text-sm">Reusable email sequence<select className={smallSelect} value={m.autoSequence??''} disabled={blocked} onChange={e=>{m.autoSequence=e.target.value;touch();}}><option value="">Choose an approved five-email sequence</option>{m.view.sequences.filter(s=>s.kind==='email_first').map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label>
   <ul className="space-y-1 text-sm text-muted-foreground">{m.view.emailAdmission.reasons.map(reason=><li key={reason}>{refusal(reason)}</li>)}</ul>
   <Button size="sm" disabled={blocked||!box?.authorized||!m.autoSequence} onClick={()=>{if(m.view&&box&&m.autoSequence)void perform({action:'email_admission',expectedRevision:m.view.emailAdmission.revision,enabled:false,ownerUserId:box.ownerUserId,mailboxId:box.id,sequenceVersionId:m.autoSequence,evaluation:null,commandId:crypto.randomUUID()});}}>Save disabled configuration</Button>
  </fieldset>:null}
  <ApprovedFactsEditor blocks={m.view?.blocks??[]} draft={m.fact} blocked={blocked} refreshRequired={m.factRefreshRequired} onChange={draft=>{m.fact=draft;touch();}} onBegin={draft=>{m.fact=draft;m.factRefreshRequired=false;touch();}} onAdopt={version=>{m.fact={...m.fact,expectedVersion:version};m.factRefreshRequired=false;touch();}} onMutate={input=>void perform(input)}/>
  {m.policy?<fieldset className="space-y-3"><legend className="font-medium">Routine replies</legend><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={m.policy.enabled} disabled={blocked} onChange={e=>{m.policy!.enabled=e.target.checked;touch();}}/>Automatically answer supported replies</label><p className="text-sm text-muted-foreground">Uses approved facts and a one-email sequence. Unclear requests, stops and unsupported questions stay for your review.</p>
   <label className="grid gap-1 text-sm">Reply sequence<select className={smallSelect} value={m.policy.sequenceVersionId??''} disabled={blocked} onChange={e=>{m.policy!.sequenceVersionId=e.target.value||null;touch();}}><option value="">Choose a one-email sequence</option>{m.view?.sequences.filter(s=>s.kind==='reply').map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label>
   <label className="grid gap-1 text-sm">Public booking link<Input value={m.policy.bookingUrl??''} disabled={blocked} onChange={e=>{m.policy!.bookingUrl=e.target.value||null;touch();}}/></label>
   {m.policy.expectedRevision!==m.view?.settings.revision?<p role="alert">The policy changed elsewhere. <Button variant="quiet" onClick={()=>{m.policy=null;if(m.view)accept(m.view);touch();}}>Load current policy</Button></p>:null}
   <Button size="sm" disabled={blocked||m.policy.expectedRevision!==m.view?.settings.revision} onClick={()=>{if(m.policy)void perform({action:'policy',...m.policy,commandId:crypto.randomUUID()});}}>Save reply policy</Button>
  </fieldset>:null}
  <fieldset className="space-y-3"><legend className="font-medium">New outreach cohort</legend><p className="text-sm text-muted-foreground">Email-first: up to five emails over 21 days. Call-first: four calls and four emails. One prospecting touch per firm per weekday. Replies and bookings stop obsolete outreach.</p>
   {(['email_first','call_first'] as const).map(kind=><label key={kind} className="grid gap-1 text-sm">{kind==='email_first'?'Email-first sequence':'Call-first sequence'}<select className={smallSelect} disabled={blocked} value={kind==='email_first'?m.email:m.call} onChange={e=>{if(kind==='email_first')m.email=e.target.value;else m.call=e.target.value;change();}}><option value="">Choose a published sequence</option>{m.view?.sequences.filter(s=>s.kind===kind).map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label>)}
   {!m.view?.candidates.length?<p className="text-sm text-muted-foreground">No currently researched candidates. Review firms in Sourcing first.</p>:<ul className="max-h-64 space-y-2 overflow-auto">{m.view.candidates.map(c=><li key={c.id}><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={m.selected.includes(c.id)} disabled={blocked||(!m.selected.includes(c.id)&&m.selected.length>=25)} onChange={e=>{m.selected=e.target.checked?[...m.selected,c.id]:m.selected.filter(id=>id!==c.id);change();}}/>{c.name} · {c.location}</label></li>)}</ul>}
   <Button size="sm" disabled={blocked||!m.sender||!m.selected.length} onClick={()=>void preview()}>Preview selected firms</Button>
   {m.preview?<div className="space-y-3"><ul>{m.preview.rows.map(r=><li key={r.candidateId} className="py-2 text-sm"><strong>{r.name}</strong><br/>{r.address??'No supported email'} · {r.lane==='call_first'?'Call first':'Email first'}{r.reason?<p>{refusal(r.reason)}</p>:null}<QualificationPanel candidateId={r.candidateId} revision={r.revision} enabled={false}/></li>)}</ul><label className="flex gap-2 text-sm"><input type="checkbox" checked={m.reviewed} disabled={blocked} onChange={e=>{m.reviewed=e.target.checked;touch();}}/>I reviewed these firms and their source evidence.</label><Button disabled={blocked||!m.reviewed||m.preview.rows.some(r=>r.reason!==null)} onClick={()=>{if(m.preview)void perform({action:'cohort_enable',...input(),expectedHash:m.preview.hash,reviewed:m.reviewed,commandId:crypto.randomUUID()});}}>Enable selected cohort</Button><p className="text-xs text-muted-foreground">This enrolls only these firms. Sending still requires your domain switch, available capacity and verified routes.</p></div>:null}
  </fieldset>
  {m.view?.replies.length?<div className="space-y-3"><h3 className="font-medium">Reply review</h3>{m.view.replies.map(r=><article key={r.id} className="rounded-md border border-border p-3 space-y-2"><Button variant="quiet" onClick={()=>navigate({name:'firm',firmId:r.firmId})}>{r.firmName}</Button><p className="text-sm">{r.state==='ready'?'Prepared answer awaiting normal sending checks':r.state==='expired'?'Answer window expired; review the conversation':'Your review is needed'}</p><Button size="sm" disabled={blocked} onClick={()=>void perform({action:'reply_manual',id:r.id,expectedRevision:r.revision,commandId:crypto.randomUUID()})}>Handle this conversation myself</Button></article>)}</div>:null}
 </div>:null}</Section>;
}
