import {randomUUID} from 'node:crypto';
import type {SessionQueryable} from '../../../db/queryable.ts';
import type {TwoWorkspaces} from './fixtures.ts';
import type {SeededMail} from './mailFixtures.ts';
import {seedMailCaptureCatalogFixture} from './mailCaptureCases.ts';
import type {SeededCrm} from './crmFixtures.ts';
interface Fixture{session:SessionQueryable;seeded:TwoWorkspaces;mail:SeededMail;crm:SeededCrm}
interface Case{constraint:string;run(f:Fixture):Promise<unknown>}
type Row=Record<string,unknown>;
const absent='00000000-0000-4000-8000-000000009999';
const insert=(f:Fixture,table:string,row:Row)=>f.session.query(`INSERT INTO ${table}(${Object.keys(row).join(',')}) VALUES(${Object.keys(row).map((_,i)=>`$${i+1}`).join(',')})`,Object.values(row));
function authority(f:Fixture):Row{const id=randomUUID(),w=f.seeded.alpha.workspaceId,u=f.seeded.alpha.admin.userId;return {workspace_id:w,id,capability:'crm_extraction',owner_user_id:u,configuration_sha256:'a'.repeat(64),authority_sha256:'b'.repeat(64),receipt:JSON.stringify({id,configuration:{workspaceId:w,ownerUserId:u,capability:'crm_extraction'},configurationFingerprint:'a'.repeat(64),reviewedBy:u,reviewReference:'catalog',verifiedAt:'2026-10-01T00:00:00Z',validUntil:'2026-11-01T00:00:00Z',proof:{release:{}}}),reviewed_by:u,review_reference:'catalog',verified_at:'2026-10-01',valid_until:'2026-11-01'};}
function adjustAuthority(row:Row,patch:Row){const receipt=JSON.parse(String(row['receipt']));if('configuration_sha256' in patch)receipt.configurationFingerprint=patch['configuration_sha256'];if('workspace_id' in patch)receipt.configuration.workspaceId=patch['workspace_id'];if('owner_user_id' in patch)receipt.configuration.ownerUserId=patch['owner_user_id'];return {...row,receipt:JSON.stringify(receipt),...patch};}
const table='crm_capability_authority_receipts';
export const CRM_CAPABILITY_CONSTRAINT_CASES:Case[]=[];
for(const [name,patch] of Object.entries({capability_check:{capability:'wrong'},configuration_sha256_check:{configuration_sha256:'bad'},authority_sha256_check:{authority_sha256:'bad'},receipt_check:{receipt:'[]'},review_reference_check:{review_reference:''},check:{valid_until:'2026-09-01'},revocation_reference_check:{revocation_reference:'',revoked_at:'2026-10-02'},check1:{revoked_at:'2026-10-02'},check2:{receipt:JSON.stringify({id:randomUUID(),configuration:{},configurationFingerprint:'a'.repeat(64),reviewedBy:randomUUID(),reviewReference:'x',verifiedAt:'2026-10-01',validUntil:'2026-11-01',proof:{release:{}}})},workspace_id_fkey:{workspace_id:absent},workspace_id_reviewed_by_fkey:{reviewed_by:absent}}))CRM_CAPABILITY_CONSTRAINT_CASES.push({constraint:`${table}_${name}`,run:f=>insert(f,table,{...adjustAuthority(authority(f),patch)})});
CRM_CAPABILITY_CONSTRAINT_CASES.push({constraint:'crm_capability_authority_receip_workspace_id_owner_user_id_fkey',run:f=>insert(f,table,adjustAuthority(authority(f),{owner_user_id:absent}))},{constraint:'crm_capability_authority_body_free',run:f=>{const row=authority(f);const receipt=JSON.parse(String(row['receipt']));receipt.proof.body='must not retain';return insert(f,table,{...row,receipt:JSON.stringify(receipt)});}},{constraint:`${table}_pkey`,run:async f=>{const row=authority(f);await insert(f,table,row);return insert(f,table,row);}});
const oauth='mailbox_oauth_grant_observations';
function observation(f:Fixture):Row{return {workspace_id:f.seeded.alpha.workspaceId,id:randomUUID(),mailbox_id:f.mail.alpha.mailboxId,owner_user_id:f.seeded.alpha.salesperson.userId,provider_account_id:'catalog',generation:1,granted_scopes:['scope']};}
for(const [suffix,patch]of Object.entries({generation_check:{generation:0},provider_account_id_check:{provider_account_id:''},granted_scopes_check:{granted_scopes:[]},workspace_id_mailbox_id_fkey:{mailbox_id:absent}}))CRM_CAPABILITY_CONSTRAINT_CASES.push({constraint:`${oauth}_${suffix}`,run:f=>insert(f,oauth,{...observation(f),...patch})});
CRM_CAPABILITY_CONSTRAINT_CASES.push({constraint:'mailbox_oauth_grant_observation_workspace_id_owner_user_id_fkey',run:f=>insert(f,oauth,{...observation(f),owner_user_id:absent})},{constraint:`${oauth}_pkey`,run:async f=>{const row=observation(f);await insert(f,oauth,row);return insert(f,oauth,row);}});
for(const [target,name]of [['crm_business_policies','crm_business_policies_workspace_id_authority_receipt_id_fkey'],['crm_mail_capture_controls','crm_mail_capture_controls_workspace_id_authority_receipt_i_fkey'],['crm_extraction_purposes','crm_extraction_purposes_workspace_id_authority_receipt_id_fkey'],['crm_ask_purposes','crm_ask_purposes_workspace_id_authority_receipt_id_fkey']]as const)CRM_CAPABILITY_CONSTRAINT_CASES.push({constraint:name,run:async f=>{if(target==='crm_mail_capture_controls'){await seedMailCaptureCatalogFixture(f);return f.session.query(`UPDATE ${target} SET authority_receipt_id=$1`,[absent]);}if(target==='crm_business_policies')return f.session.query(`INSERT INTO ${target}(workspace_id,mailbox_id,owner_user_id,provider_account_id,account_binding,generation,revision,disclosure_version,disclosure_sha256,authority_receipt_id) VALUES($1,$2,$3,'account',repeat('a',64),1,1,'v1',repeat('b',64),$4)`,[f.seeded.alpha.workspaceId,f.mail.alpha.mailboxId,f.seeded.alpha.salesperson.userId,absent]);return insert(f,target,{workspace_id:f.seeded.alpha.workspaceId,revision:1,enabled:false,authority_receipt_id:absent,endpoint_id:'fixture',model_version:'fixture',access_grant_version:'grant',data_handling_version:'data',daily_ceiling_cents:10,monthly_ceiling_cents:100,input_token_price_micros:1,output_token_price_micros:1,approved_by:f.seeded.alpha.admin.userId,...target==='crm_ask_purposes'?{purpose:'answer',evaluation_fingerprint:'a'.repeat(64),processor_version:'ask-answer-v1',retrieval_version:'lexical-original-v1',answer_version:'literal-v1',support_version:'exact-original-v1',chunker_version:'lexical-original-v1'}:{}});}});
