import {randomUUID} from 'node:crypto';
import {callSession,type CallToBookingFixture} from './callToBookingCases.ts';
import type {SqlParameter} from '../../../db/queryable.ts';
type Fixture=CallToBookingFixture;
type Case={constraint:string;run(f:Fixture):Promise<unknown>};
const absent='00000000-0000-4000-8000-000000004880';
const hash='a'.repeat(64);
async function insert(f:Pick<Fixture,'session'>,table:string,row:Record<string,SqlParameter>){const columns=Object.keys(row);return await f.session.query<{id:string}>(`INSERT INTO ${table}(${columns.join(',')}) VALUES(${columns.map((_,index)=>'$'+(index+1)).join(',')}) RETURNING *`,Object.values(row));}
function generation(f:Pick<Fixture,'session'|'seeded'|'crm'>,patch:Record<string,SqlParameter>={}){return {workspace_id:f.seeded.alpha.workspaceId,id:randomUUID(),source_id:randomUUID(),source_kind:'selected_note',source_revision:1,source_hash:hash,requested_by:f.seeded.alpha.salesperson.userId,processor_version:'crm-extract-v1',purpose_revision:1,model_version:'fixture-v1',state:'pending',reason:null,original_firm_id:f.crm.alpha.firmId,...patch};}
function purpose(f:Fixture,patch:Record<string,SqlParameter>={}){return {workspace_id:f.seeded.alpha.workspaceId,revision:1,enabled:false,endpoint_id:'fixture',model_version:'fixture-v1',access_grant_version:'grant-v1',data_handling_version:'data-v1',daily_ceiling_cents:100,monthly_ceiling_cents:1000,input_token_price_micros:2,output_token_price_micros:8,approved_by:f.seeded.alpha.admin.userId,...patch};}
async function financial(f:Pick<Fixture,'session'|'seeded'|'crm'>,patch:Record<string,SqlParameter>={}){
 const gen=generation(f);await insert(f,'crm_extraction_generations',gen);
 const reservation=randomUUID(),job=randomUUID();
 await insert(f,'provider_reservations',{workspace_id:f.seeded.alpha.workspaceId,id:reservation,provider_key:'fixture.crm_extraction',subject_kind:'crm_extraction',subject_id:gen.id,attempt:1,business_date:'2026-10-01',business_time_zone:'America/New_York',cents:1,model_name:'fixture-v1',max_input_tokens:100,max_output_tokens:100});
 await insert(f,'jobs',{workspace_id:f.seeded.alpha.workspaceId,id:job,kind:'crm.extract',payload:'{}',idempotency_key:randomUUID()});
 return {workspace_id:f.seeded.alpha.workspaceId,generation_id:gen.id,reservation_id:reservation,job_id:job,fencing_token:1,dispatch_state:'reserved',endpoint_id:'fixture',model_version:'fixture-v1',access_grant_version:'grant-v1',data_handling_version:'data-v1',purpose_revision:1,input_price_micros:2,output_price_micros:8,...patch};
}
async function claim(f:Fixture,patch:Record<string,SqlParameter>={}){const gen=generation(f);await insert(f,'crm_extraction_generations',gen);return {workspace_id:f.seeded.alpha.workspaceId,id:randomUUID(),generation_id:gen.id,kind:'need',interpretation:'Needs help',status:'stated',locator:'text:0:4',quote:'Help',claim_hash:hash,...patch};}
export const CRM_EXTRACTION_CONSTRAINT_CASES:readonly Case[]=[
 ...(['input_token_price_micros','output_token_price_micros'] as const).map(column=>({constraint:`crm_extraction_purposes_${column}_check`,run:async(f:Fixture)=>await insert(f,'crm_extraction_purposes',purpose(f,{[column]:'0.0000001'}))})),
 ...(['input_price_micros','output_price_micros'] as const).map(column=>({constraint:column==='input_price_micros'?'crm_financial_input_price_bounded':'crm_financial_output_price_bounded',run:async(f:Fixture)=>await insert(f,'crm_extraction_financial_receipts',await financial(f,{[column]:'0.0000001'}))})),
 {constraint:'crm_extraction_context_body_free',run:async f=>await insert(f,'crm_extraction_generations',generation(f,{context_snapshot:JSON.stringify({personId:null,firmIds:[],relationships:[{relationshipId:randomUUID(),revision:1,quote:'Forbidden duplicated body'}],review:'current'})}))},
 {constraint:'crm_selected_extraction_enqueue',run:async f=>{
  await insert(f,'crm_extraction_purposes',purpose(f,{enabled:true}));
  await f.session.query("CREATE FUNCTION fixture_crm_queue_refusal() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.kind='crm.extract' THEN RAISE EXCEPTION 'durable queue unavailable'; END IF; RETURN NEW; END $$");
  await f.session.query('CREATE TRIGGER fixture_crm_queue_refusal BEFORE INSERT ON jobs FOR EACH ROW EXECUTE FUNCTION fixture_crm_queue_refusal()');
  await f.session.query('SET CONSTRAINTS crm_selected_extraction_enqueue IMMEDIATE');
  return await insert(f,'crm_selected_sources',{workspace_id:f.seeded.alpha.workspaceId,firm_id:f.crm.alpha.firmId,person_id:null,owner_user_id:f.seeded.alpha.salesperson.userId,source_key_hash:hash,content_hash:hash,excerpt:'Atomic capture',occurred_at:'2026-10-01T14:00:00Z'});
 }},
 ...Object.entries({source_kind:'other',source_revision:0,source_hash:'bad',context_hash:'bad',authorization_hash:'bad',purpose_revision:-1,processor_version:'',model_version:'',state:'other',reason:'',workspace_id:absent,requested_by:absent,original_firm_id:absent,source_owner_user_id:absent}).map(([column,value])=>({constraint:column==='workspace_id'?'crm_extraction_generations_workspace_id_fkey':column==='requested_by'?'crm_extraction_generations_workspace_id_requested_by_fkey':column==='original_firm_id'?'crm_extraction_generations_workspace_id_original_firm_id_fkey':column==='source_owner_user_id'?'crm_extraction_source_owner_fk':`crm_extraction_generations_${column}_check`,run:async(f:Fixture)=>await insert(f,'crm_extraction_generations',generation(f,{[column]:value}))})),
 {constraint:'crm_extraction_generations_pkey',run:async f=>{const row=generation(f);await insert(f,'crm_extraction_generations',row);return await insert(f,'crm_extraction_generations',{...row,source_id:randomUUID()});}},
 {constraint:'crm_extraction_generations_workspace_id_source_kind_source__key',run:async f=>{const row=generation(f);await insert(f,'crm_extraction_generations',row);return await insert(f,'crm_extraction_generations',{...row,id:randomUUID()});}},
 ...Object.entries({revision:0,endpoint_id:'',model_version:'',access_grant_version:'',data_handling_version:'',daily_ceiling_cents:0,monthly_ceiling_cents:0,input_token_price_micros:0,output_token_price_micros:-1,approved_by:absent,workspace_id:absent}).map(([column,value])=>({constraint:column==='workspace_id'?'crm_extraction_purposes_workspace_id_fkey':column==='approved_by'?'crm_extraction_purposes_workspace_id_approved_by_fkey':`crm_extraction_purposes_${column}_check`,run:async(f:Fixture)=>await insert(f,'crm_extraction_purposes',purpose(f,{[column]:value}))})),
 {constraint:'crm_extraction_purposes_pkey',run:async f=>{await insert(f,'crm_extraction_purposes',purpose(f));return await insert(f,'crm_extraction_purposes',purpose(f));}},
 ...Object.entries({kind:'other',interpretation:'',status:'other',locator:'',quote:'',claim_hash:'bad',generation_id:absent}).map(([column,value])=>({constraint:column==='generation_id'?'crm_extraction_claims_workspace_id_generation_id_fkey':`crm_extraction_claims_${column}_check`,run:async(f:Fixture)=>await insert(f,'crm_extraction_claims',await claim(f,{[column]:value}))})),
 {constraint:'crm_extraction_claims_pkey',run:async f=>{const row=await claim(f);await insert(f,'crm_extraction_claims',row);return await insert(f,'crm_extraction_claims',row);}},
 ...Object.entries({generation_id:absent,reservation_id:absent,job_id:absent,dispatch_state:'other',fencing_token:0,purpose_revision:0,endpoint_id:'',model_version:'',access_grant_version:'',data_handling_version:'',input_price_micros:0,output_price_micros:-1}).map(([column,value])=>({constraint:({generation_id:'crm_extraction_financial_receip_workspace_id_generation_id_fkey',reservation_id:'crm_extraction_financial_recei_workspace_id_reservation_id_fkey',job_id:'crm_extraction_financial_receipts_workspace_id_job_id_fkey',dispatch_state:'crm_extraction_financial_receipts_dispatch_state_check',fencing_token:'crm_financial_fence_positive',purpose_revision:'crm_financial_purpose_positive',endpoint_id:'crm_financial_endpoint_bounded',model_version:'crm_financial_model_bounded',access_grant_version:'crm_financial_grant_bounded',data_handling_version:'crm_financial_policy_bounded',input_price_micros:'crm_financial_input_price_bounded',output_price_micros:'crm_financial_output_price_bounded'} as Record<string,string>)[column]!,run:async(f:Fixture)=>await insert(f,'crm_extraction_financial_receipts',await financial(f,{[column]:value}))})),
 {constraint:'crm_extraction_financial_receipts_pkey',run:async f=>{const row=await financial(f);await insert(f,'crm_extraction_financial_receipts',row);return await insert(f,'crm_extraction_financial_receipts',row);}},
 {constraint:'call_transcripts_crm_revision_check',run:async f=>await insert(f,'call_transcripts',{workspace_id:f.seeded.alpha.workspaceId,call_session_id:await callSession(f),provider:'deepgram',model:'nova-3',language:'en',duration_seconds:60,utterances:'[]',crm_revision:0})},
 {constraint:'meeting_recordings_crm_capture_owner_fk',run:async f=>{const meeting=randomUUID();await insert(f,'meetings',{workspace_id:f.seeded.alpha.workspaceId,id:meeting,booking_uid:meeting,current_booking_uid:meeting,firm_id:f.crm.alpha.firmId,state:'booked',starts_at:'2026-10-01T14:00:00Z',ends_at:'2026-10-01T14:20:00Z',last_event_at:'2026-10-01T14:00:00Z'});return await insert(f,'meeting_recordings',{workspace_id:f.seeded.alpha.workspaceId,meeting_id:meeting,segment:1,participant_label:'Fixture',sha256:hash,size_bytes:100,s3_key:`meetings/${meeting}/${hash}.m4a`,crm_capture_owner_user_id:absent});}},
];

export async function seedExtractionFinancialReceipt(f:Pick<Fixture,'session'|'seeded'|'crm'>){const row=await financial(f);await insert(f,'crm_extraction_financial_receipts',row);return String(row['generation_id']);}
