import {EMAIL_EVALUATION_MANIFEST} from '../../../outreach/emailEvaluationManifest.ts';
import {ciGateReleaseReference} from '@fss/contracts';
import {createHash,randomUUID} from 'node:crypto';
import type {RepositoryContext} from '../../../db/workspaceScope.ts';
import {fixtureCiGateRecord,FIXTURE_API_DIGEST,FIXTURE_WORKER_DIGEST} from '../../release/support/releaseRecords.ts';
import {putReleaseRecord} from '../../../release/records.ts';
import {readSequenceVersion} from '../../../sequences/rows.ts';
import {readTemplateVersion,renderTemplateVersion} from '../../../templates/templates.ts';
import {REQUIRED_SCHEMA} from '../../../db/schemaRange.ts';
import type {EmailAdmissionActivationProof,EmailAdmissionRuntime} from '../../../outreach/emailActivation.ts';
export async function controlledActivationProof(ctx:RepositoryContext,mailboxId:string,sequenceVersionId:string,commit:string){
 if(ctx.scope.actor.kind!=='user')throw new Error('fixture_admin_required');
 const w=ctx.scope.workspaceId,owner=ctx.scope.actor.userId;
 const record=fixtureCiGateRecord('12345');record.commit=commit;record.artifacts.desktopCommitStamp=commit;record.releaseGateReference=ciGateReleaseReference('12345',commit);
 const stored=await putReleaseRecord(ctx,record);if(!stored.ok)throw new Error(stored.reason+stored.detail);
 const guards=['does not create a prospect when automatic email admission is off','rejects a changed exact-version evaluation without partial admission','rejects revoked and reauthorized mailbox bindings until reevaluation','does not reassign a supported firm owned by someone else','refuses a retired evaluated sequence','sees a concurrent recipient stop committed while the worker waits for the send gate','concurrent workers and later retries preserve one enrollment and its original scheduled execution','refuses new admission when the sender ramp has no room','preserves the original manually enrolled Key prospect without rearming or enrolling it again'];
 const report={version:1,implementationCommit:commit,policyVersion:'outreach-email-fit-v2',promptVersion:'qualification-growth-v6',promptSourceSha256:EMAIL_EVALUATION_MANIFEST.promptSourceSha256,evidenceAsOf:EMAIL_EVALUATION_MANIFEST.evidenceAsOf,recordedPromptMatches:true,complete:true,scope:'Synthetic controlled activation fixture; never live evidence',limitations:['No live model, provider, deployment or population precision claim'],corpus:EMAIL_EVALUATION_MANIFEST.corpus,reviewedEligible:2,falseEligible:0,requiredGuardTests:guards,tests:[...guards.map(name=>({name,status:'passed'})),...EMAIL_EVALUATION_MANIFEST.cases.map(c=>({name:'evaluates labeled email admission: '+c.id,status:'passed'}))],cases:EMAIL_EVALUATION_MANIFEST.cases.map(c=>({...c,actual:{actualAdmission:c.expectedAdmission,evidenceAccepted:c.expectedEvidenceAccepted,actualRank:c.expectedAdmission?c.expectedRank:null}}))};
 const evaluationReportJson=JSON.stringify(report),reportSha256=createHash('sha256').update(evaluationReportJson).digest('hex');
 const firm=(await ctx.db.query<{id:string}>('INSERT INTO firms(workspace_id,name,assigned_user_id) VALUES($1,$2,$3) RETURNING id',[w,'Historical original fixture',owner])).rows[0]!.id;
 const contact=(await ctx.db.query<{id:string}>('INSERT INTO contacts(workspace_id,firm_id,full_name) VALUES($1,$2,$3) RETURNING id',[w,firm,'Historical fixture'])).rows[0]!.id;
 const opportunity=(await ctx.db.query<{id:string}>("INSERT INTO opportunities(workspace_id,firm_id,stage_id,control_mode_changed_at) SELECT $1,$2,id,now() FROM pipeline_stages WHERE workspace_id=$1 AND key='new' RETURNING id",[w,firm])).rows[0]!.id;
 const originalEnrollmentId=randomUUID(),stepId=randomUUID(),originalOutboundId=randomUUID();
 await ctx.db.query("INSERT INTO sequence_enrollments(workspace_id,id,sequence_version_id,firm_id,contact_id,assigned_user_id,state,ended_at,end_reason,firm_time_zone,holiday_calendar_version,origin_kind,opportunity_id) VALUES($1,$2,$3,$4,$5,$6,'completed',now(),'sequence_complete','America/New_York','holidays.2026','cold_legacy',$7)",[w,originalEnrollmentId,sequenceVersionId,firm,contact,owner,opportunity]);
 await ctx.db.query("INSERT INTO step_executions(workspace_id,id,enrollment_id,step_id,firm_id,contact_id,channel,ordinal,state,due_at,not_before,original_due_at,source_zone,rule_version,completion_source,result,completed_at) SELECT $1,$2,$3,id,$4,$5,'email',1,'completed',now()-interval '1 day',now()-interval '1 day',now()-interval '1 day','America/New_York','fixture','send','sent',now()-interval '1 day' FROM sequence_steps WHERE workspace_id=$1 AND sequence_version_id=$6 AND ordinal=1",[w,stepId,originalEnrollmentId,firm,contact,sequenceVersionId]);
 const providerId=`synthetic-${randomUUID()}`;
 await ctx.db.query("INSERT INTO outbound_messages(workspace_id,id,mailbox_id,state,origin_kind,enrollment_id,step_execution_id,firm_id,contact_id,recipient_address,subject,body,rendered_hash,provider_message_id_header,send_at,source_zone,placement_rule_version,attempt_token,dispatch_started_at,sent_at,provider_message_id) VALUES($1,$2,$3,'sent','step_execution',$4,$5,$6,$7,'original@fictional.test','Original fixture','Retained synthetic sent fixture',$8,$9,now()-interval '1 day','America/New_York','fixture',$10,now()-interval '1 day',now()-interval '1 day',$11)",[w,originalOutboundId,mailboxId,originalEnrollmentId,stepId,firm,contact,'a'.repeat(64),`<${originalOutboundId}@example.test>`,randomUUID(),providerId]);
 const sequence=await readSequenceVersion(ctx,sequenceVersionId);if(!sequence)throw new Error('fixture_sequence_missing');
 const variables={firm_name:'Fixture PM',contact_first_name:'Shirley',sender_name:'Fixture',sender_email:'owner@example.test',cal_link:'https://example.test/demo'};
 const steps=[];for(const step of sequence.steps){const template=await readTemplateVersion(ctx,step.templateVersionId!);if(!template)throw new Error('fixture_template_missing');const rendered=renderTemplateVersion(template,variables);if(!rendered.rendered)throw new Error(JSON.stringify(rendered));steps.push({ordinal:step.ordinal,templateVersionId:template.id,subject:rendered.subject,body:rendered.body});}
 const at=new Date().toISOString();
 const proof:EmailAdmissionActivationProof={version:1,evaluationReportJson,release:{recordReference:record.releaseGateReference,observedAt:at,apiDigest:FIXTURE_API_DIGEST,workerDigest:FIXTURE_WORKER_DIGEST,schemaVersion:REQUIRED_SCHEMA,postSmokeReadback:'existing',deploymentReceiptJson:JSON.stringify({commit,to_schema:REQUIRED_SCHEMA,status:'verified_backend_release_complete',production:{commit,schema:REQUIRED_SCHEMA,passed:true,failures:[],services:[{stable:true,running:1,desired:1},{stable:true,running:1,desired:1}]},smoke:{passed:true,results:['health','readiness','schema_range','connectivity','canary','sending_enabled'].map(name=>({name,passed:true}))},release_record:{reference:record.releaseGateReference,outcome:'existing',apiDigest:FIXTURE_API_DIGEST,workerDigest:FIXTURE_WORKER_DIGEST}})},received:{mailboxId,senderAddress:'owner@example.test',observedAt:at,messageReference:'synthetic-received-fixture',reviewReference:'synthetic-operator-review',headerText:'From: owner@example.test\r\nReturn-Path: <owner@example.test>\r\nAuthentication-Results: mx.google.com; spf=pass smtp.mailfrom=owner@example.test; dkim=pass header.i=@example.test; dmarc=pass header.from=example.test'},sequence:{sequenceVersionId,renderedEvidenceJson:JSON.stringify({variables,steps})},interruptions:{originalOutboundId,originalEnrollmentId,providerId,observedAt:at,reviewReference:'synthetic-original-review',integrationEvidenceJson:JSON.stringify({implementationCommit:commit,scope:'real_postgres_controlled_provider',tests:['reply','booking','opt_out'].map(scenario=>({scenario,status:'passed'}))})}};
 const runtime:EmailAdmissionRuntime={implementationCommit:commit,imageDigest:FIXTURE_API_DIGEST,side:'api',production:true,schemaVersion:REQUIRED_SCHEMA,deploymentSendingEnabled:true};
 return {proof,runtime,reportSha256,reviewedEligible:report.reviewedEligible};
}
