import {createHash,randomUUID} from 'node:crypto';
import {expect,it} from 'vitest';
import {dispatch} from '../src/server.ts';
import {createAuthFixture,CURRENT_CLIENT_VERSION} from './support/authFixture.ts';
import {issueSessionFor} from './support/sessionFixture.ts';

it('explicitly commits a human note from current keyword evidence without enabling answering or copying content into its command receipt',async()=>{
 const fixture=await createAuthFixture();
 try{
  const token=(await issueSessionFor(fixture,fixture.alpha,fixture.alpha.salesperson)).accessToken;
  const post=(path:string,body:unknown)=>dispatch({method:'POST',path,body,query:new URLSearchParams(),headers:{authorization:`Bearer ${token}`}},{session:fixture.db,auth:fixture.deps,supportedClientVersions:fixture.deps.config.supportedClientVersions,sendingEnabled:false});
  const person=await post('/crm/people/create',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,fullName:'Manual note context'});
  expect(person.status).toBe(200);
  const personId=(person.body as {result:{personId:string}}).result.personId;
  const text='Repairs need clearer routing.';
  const added=await post('/crm/people/source/add',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,personId,sourceKey:'manual-note-source',excerpt:text,occurredAt:'2026-10-01T14:00:00Z'});
  expect(added.status).toBe(200);
  const sourceId=(added.body as {result:{sourceId:string}}).result.sourceId;
  const requested=await post('/ask/answers/request',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,question:'repairs',scope:{sources:[{workspaceId:fixture.alpha.workspaceId,sourceId,kind:'selected_note',revision:1,contentHash:createHash('sha256').update(text).digest('hex'),locator:null}]}});
  expect(requested.status).toBe(200);
  const requestId=(requested.body as {result:{requestId:string}}).result.requestId;
  const committed=await post('/ask/actions/create',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,requestId,expectedVersion:1,finding:{kind:'keyword_passage',index:0},action:{kind:'note',text:'Ask about the repair routing process.',target:{kind:'person',personId}}});
  expect(committed.status).toBe(200);
  expect(committed.body).toMatchObject({result:{actionId:expect.any(String),version:1,kind:'note'}});
  expect(JSON.stringify(committed.body)).not.toContain('repair routing');
  const actionId=(committed.body as {result:{actionId:string}}).result.actionId;
  const notes=await post('/ask/actions/read',{scope:{kind:'person',personId}});
  expect(notes.status).toBe(200);
  expect(notes.body).toMatchObject({items:[{actionId,version:1,kind:'note',status:'active',text:'Ask about the repair routing process.',provenance:'human',supportState:'current'}],nextAfterId:null});
  const task=await post('/ask/actions/create',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,requestId,expectedVersion:1,finding:{kind:'keyword_passage',index:0},action:{kind:'task',label:'Discuss repair routing',due:{kind:'date',date:'2099-10-12',zone:'America/Chicago',expression:'October 12'},target:{kind:'person',personId}}});
  expect(task.status).toBe(200);
  expect(task.body).toMatchObject({result:{actionId:expect.any(String),version:1,kind:'task'}});
  const taskId=(task.body as {result:{actionId:string}}).result.actionId;
  const tasks=await post('/ask/actions/read',{scope:{kind:'person',personId}});
  expect(tasks.status).toBe(200);
  expect(tasks.body).toMatchObject({items:expect.arrayContaining([expect.objectContaining({actionId:taskId,kind:'task',status:'open',label:'Discuss repair routing',text:null,due:{kind:'date',date:'2099-10-12',zone:'America/Chicago',expression:'October 12'},reviewRequired:false,supportState:'current'})]),nextAfterId:null});
  const laterTasks=await post('/ask/actions/read',{scope:{kind:'today'}});
  expect(laterTasks.status).toBe(200);
  expect(laterTasks.body).toEqual({items:[],nextAfterId:null});
  const proposal=await post('/ask/actions/create',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,requestId,expectedVersion:1,finding:{kind:'keyword_passage',index:0},action:{kind:'preference',text:'Consider prioritizing repair routing examples.'}});
  expect(proposal.status).toBe(200);
  expect(proposal.body).toMatchObject({result:{actionId:expect.any(String),version:1,kind:'preference'}});
  const proposalId=(proposal.body as {result:{actionId:string}}).result.actionId;
  const history=await post('/ask/actions/read',{scope:{kind:'history'}});
  expect(history.status).toBe(200);
  expect(history.body).toMatchObject({items:expect.arrayContaining([{actionId:proposalId,version:1,kind:'preference',status:'proposed',provenance:'human',text:'Consider prioritizing repair routing examples.',label:null,due:null,target:null,supportState:'current',reviewRequired:false,createdAt:expect.any(String),updatedAt:expect.any(String),completedAt:null,sources:expect.any(Array)}])});
  const completionCommand={commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,actionId:taskId,expectedVersion:1,action:'complete_task'};
  const completion=await post('/ask/actions/change',completionCommand);
  expect(completion.status).toBe(200);
  expect(completion.body).toMatchObject({result:{actionId:taskId,version:2,status:'done',completedAt:expect.any(String)}});
  const completionReplay=await post('/ask/actions/change',completionCommand);
  expect(completionReplay.status).toBe(200);
  expect(completionReplay.body).toMatchObject({replayed:true,result:(completion.body as {result:unknown}).result});
  const staleCancellation=await post('/ask/actions/change',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,actionId:taskId,expectedVersion:1,action:'cancel_task'});
  expect(staleCancellation.status).toBe(409);
  const unrelatedTarget=await post('/ask/actions/create',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,requestId,expectedVersion:1,finding:{kind:'keyword_passage',index:0},action:{kind:'note',text:'Unrelated target must not receive evidence.',target:{kind:'person',personId:randomUUID()}}});
  expect(unrelatedTarget.status).toBe(409);
  const dismissal=await post('/ask/actions/change',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,actionId:proposalId,expectedVersion:1,action:'dismiss_preference'});
  expect(dismissal.status).toBe(200);
  expect(dismissal.body).toMatchObject({result:{actionId:proposalId,version:2,status:'dismissed',completedAt:null}});
  const undated=await post('/ask/actions/create',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,requestId,expectedVersion:1,finding:{kind:'keyword_passage',index:0},action:{kind:'task',label:'Optional repair follow-up',due:null,target:{kind:'person',personId}}});
  expect(undated.status).toBe(200);
  const undatedId=(undated.body as {result:{actionId:string}}).result.actionId;
  const datedOnly=await post('/ask/actions/read',{scope:{kind:'today'}});
  expect(datedOnly.body).toEqual({items:[],nextAfterId:null});
  const cancelled=await post('/ask/actions/change',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,actionId:undatedId,expectedVersion:1,action:'cancel_task'});
  expect(cancelled.status).toBe(200);
  expect(cancelled.body).toMatchObject({result:{actionId:undatedId,version:2,status:'cancelled',completedAt:null}});
  const pastDateTask=await post('/ask/actions/create',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,requestId,expectedVersion:1,finding:{kind:'keyword_passage',index:0},action:{kind:'task',label:'Overdue date follow-up',due:{kind:'date',date:'2000-01-01',zone:'Pacific/Kiritimati',expression:'January 1, 2000'},target:{kind:'person',personId}}});
  expect(pastDateTask.status).toBe(200);
  const pastInstantTask=await post('/ask/actions/create',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,requestId,expectedVersion:1,finding:{kind:'keyword_passage',index:0},action:{kind:'task',label:'Overdue instant follow-up',due:{kind:'instant',at:'2000-01-02T01:00:00Z',zone:'America/Los_Angeles',expression:'January 1, 2000 evening'},target:{kind:'person',personId}}});
  expect(pastInstantTask.status).toBe(200);
  const overdue=await post('/ask/actions/read',{scope:{kind:'today'}});
  expect(overdue.status).toBe(200);
  expect((overdue.body as {items:unknown[]}).items).toHaveLength(2);
  expect(overdue.body).toMatchObject({items:expect.arrayContaining([expect.objectContaining({actionId:(pastDateTask.body as {result:{actionId:string}}).result.actionId,status:'open',label:'Overdue date follow-up'}),expect.objectContaining({actionId:(pastInstantTask.body as {result:{actionId:string}}).result.actionId,status:'open',label:'Overdue instant follow-up'})]),nextAfterId:null});
  const adminToken=(await issueSessionFor(fixture,fixture.alpha,fixture.alpha.admin)).accessToken;
  const adminRead=await dispatch({method:'POST',path:'/ask/actions/read',body:{scope:{kind:'history'}},query:new URLSearchParams(),headers:{authorization:`Bearer ${adminToken}`}},{session:fixture.db,auth:fixture.deps,supportedClientVersions:fixture.deps.config.supportedClientVersions,sendingEnabled:false});
  expect(adminRead.status).toBe(200);
  expect(adminRead.body).toEqual({items:[],nextAfterId:null});
  const saved=await post('/ask/history/list',{});
  expect(saved.status).toBe(200);
  const historyRevision=(saved.body as {items:{historyRevision:number}[]}).items[0]!.historyRevision;
  const deletedHistory=await post('/ask/history/change',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,requestId,expectedRevision:historyRevision,action:{kind:'delete'}});
  expect(deletedHistory.status).toBe(200);
  const preservedNotes=await post('/ask/actions/read',{scope:{kind:'person',personId}});
  expect(preservedNotes.status).toBe(200);
  expect(preservedNotes.body).toMatchObject({items:expect.arrayContaining([expect.objectContaining({actionId,kind:'note',text:'Ask about the repair routing process.',supportState:'current'}),expect.objectContaining({actionId:taskId,status:'done',completedAt:expect.any(String)})])});
  const forbiddenCreation=await post('/ask/actions/create',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,requestId,expectedVersion:1,finding:{kind:'keyword_passage',index:0},action:{kind:'note',text:'Do not restore the deleted investigation.',target:{kind:'person',personId}}});
  expect(forbiddenCreation.status).toBe(409);
  const erasedSource=await post('/crm/people/source/delete',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,personId,sourceId,expectedRevision:1});
  expect(erasedSource.status).toBe(200);
  const erasedActions=await post('/ask/actions/read',{scope:{kind:'history'}});
  expect(erasedActions.status).toBe(200);
  const erasedItems=(erasedActions.body as {items:{supportState:string;text:null;label:null;target:null;due:null;sources:unknown[]}[]}).items;
  expect(erasedItems).toHaveLength(6);
  for(const item of erasedItems)expect(item).toMatchObject({supportState:'deleted',text:null,label:null,target:null,due:null,sources:[]});
  expect(erasedActions.body).toMatchObject({items:expect.arrayContaining([expect.objectContaining({actionId:taskId,status:'done',completedAt:(completion.body as {result:{completedAt:string}}).result.completedAt,reviewRequired:false}),expect.objectContaining({actionId:(pastDateTask.body as {result:{actionId:string}}).result.actionId,status:'open',reviewRequired:true})])});
  const restoredSource=await post('/crm/people/source/restore',{commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION,personId,sourceId,expectedRevision:2});
  expect(restoredSource.status).toBe(200);
  const afterRestore=await post('/ask/actions/read',{scope:{kind:'history'}});
  expect(afterRestore.body).toEqual(erasedActions.body);
 }finally{await fixture.stop();}
});
