import {expect,it} from 'vitest';
import {randomUUID} from 'node:crypto';
import {createAuthFixture} from './support/authFixture.ts';
import {repositoryContext,workspaceScope} from '@fss/domain/db/workspaceScope.ts';
import {enqueueJob,claimJobs} from '@fss/domain/jobs/jobStore.ts';
import {businessAccountBinding,METADATA_REVIEW_DISCLOSURE} from '@fss/domain/business/acquisition.ts';
import {CRM_MAIL_CAPTURE_DISCLOSURE,activateCrmCapability,readCrmCapability,provisionCrmCapabilityAuthority,revokeCrmCapabilityAuthority,crmCapabilityConfigurationFingerprint} from '@fss/domain/crm/capabilityAuthority.ts';
import {createCrmCapabilityVerifiers,crmBackfillScopeFingerprint,crmBackfillAllocationFingerprint} from '@fss/domain/crm/capabilityVerifiers.ts';
import {createApprovedBusinessMailObserver} from '@fss/domain/mail/crmSources.ts';
import {withTransaction} from '@fss/domain/db/queryable.ts';
import {createGmailHttpClient} from '@fss/domain/mail/gmailClientHttp.ts';
import {createGmailMailCaptureProvider} from '@fss/domain/mail/crmGmailProvider.ts';
import {HandlerRegistry} from '@fss/domain/jobs/handlerRegistry.ts';
import {registerHandlers} from '../../worker/src/bootstrap/main.ts';
import {storeFixtureCiGateRecord,FIXTURE_CI_COMMIT,FIXTURE_API_DIGEST,FIXTURE_WORKER_DIGEST} from '@fss/domain/test/release/support/releaseRecords.ts';
import {crmAskPurposeSaveSchema, type CrmCapabilityAuthorityReceipt,type CrmCapabilityConfiguration} from '@fss/contracts';
async function seedCapture(
  fixture: Awaited<ReturnType<typeof createAuthFixture>>,
  ownerUserId = fixture.alpha.admin.userId,
) {
  const workspaceId = fixture.alpha.workspaceId;
  const mailbox = (
    await fixture.db.query<{
      id: string;
      owner_user_id: string;
      email_address: string;
      provider_account_id: string;
      generation: number;
      status: string;
    }>(
      "INSERT INTO mailboxes(workspace_id,owner_user_id,email_address,provider_account_id,status) VALUES($1,$2,'business@example.test','google-business','connected') RETURNING *",
      [workspaceId, ownerUserId],
    )
  ).rows[0]!;
  const binding = businessAccountBinding(workspaceId, mailbox)!;
  await fixture.db.query(
    "INSERT INTO crm_business_policies(workspace_id,mailbox_id,owner_user_id,provider_account_id,account_binding,generation,revision,enabled) VALUES($1,$2,$3,'google-business',$4,1,1,false)",
    [workspaceId, mailbox.id, ownerUserId, binding],
  );
  const conversationId = (
    await fixture.db.query<{ id: string }>(
      "INSERT INTO crm_business_conversations(workspace_id,mailbox_id,owner_user_id,account_binding,provider_thread_id,subject,participants,latest_provider_at,category,reason,classifier_version,metadata_hash) VALUES($1,$2,$3,$4,'approved-thread','Business','[]',now(),'business','fixture','fixture',$5) RETURNING id",
      [workspaceId, mailbox.id, ownerUserId, binding, 'a'.repeat(64)],
    )
  ).rows[0]!.id;
  await fixture.db.query(
    "INSERT INTO crm_mail_capture_controls(workspace_id,mailbox_id,owner_user_id,provider_account_id,account_binding,generation,revision,enabled,policy_revision,disclosure_version,disclosure_sha256,grant_receipt,provider_policy_receipt,evaluation_receipt,release_receipt) VALUES($1,$2,$3,'google-business',$4,1,1,true,1,'full-body-fixture',$5,'fixture-grant','fixture-provider','fixture-evaluation','fixture-release')",
    [workspaceId, mailbox.id, ownerUserId, binding, 'b'.repeat(64)],
  );
  await enqueueJob(fixture.db, {
    workspaceId,
    kind: 'crm.mail_capture',
    idempotencyKey: randomUUID(),
    payload: {
      mailboxId: mailbox.id,
      providerMessageId: 'approved-message',
      providerAccountId: 'google-business',
      generation: 1,
      conversationId,
      controlsRevision: 1,
      policyRevision: 1,
      decisionRevision: 0,
    },
  });
  const job = (
    await claimJobs(fixture.db, {
      owner: 'capture-fixture',
      kinds: ['crm.mail_capture'],
      limit: 1,
      leaseSeconds: 120,
    })
  )[0]!;
  return { workspaceId, ownerUserId, mailbox, binding, conversationId, job };
}

async function authorize(fixture:Awaited<ReturnType<typeof createAuthFixture>>,seeded:Awaited<ReturnType<typeof seedCapture>>){
 const runtime={implementationCommit:FIXTURE_CI_COMMIT,imageDigest:FIXTURE_WORKER_DIGEST,side:'worker' as const,schemaVersion:88,adapterAvailable:()=>true};
 const releaseReference=await storeFixtureCiGateRecord(fixture.db,'98811');
 const session=await fixture.database.appRuntimeSession(),verifierSession=await fixture.database.appRuntimeSession();
 const context=repositoryContext(workspaceScope(seeded.workspaceId,{kind:'user',userId:seeded.ownerUserId,role:'admin'}),session);
 const observed=(await fixture.db.query<{id:string}>("INSERT INTO mailbox_oauth_grant_observations(workspace_id,mailbox_id,owner_user_id,provider_account_id,generation,granted_scopes) VALUES($1,$2,$3,'google-business',1,$4) RETURNING id",[seeded.workspaceId,seeded.mailbox.id,seeded.ownerUserId,['https://www.googleapis.com/auth/gmail.readonly','https://www.googleapis.com/auth/gmail.send']])).rows[0]!.id;
 async function provision(configuration:CrmCapabilityConfiguration){const r:CrmCapabilityAuthorityReceipt={id:randomUUID(),configuration,configurationFingerprint:crmCapabilityConfigurationFingerprint(configuration),reviewedBy:seeded.ownerUserId,reviewReference:'synthetic independent acceptance',verifiedAt:new Date(Date.now()-1000).toISOString(),validUntil:new Date(Date.now()+3600000).toISOString(),proof:{evaluationKind:configuration.capability==='ask_answer'||configuration.capability==='crm_extraction'?'actual_representative':'actual_acceptance',evaluationFingerprint:'a'.repeat(64),evaluationConfigurationFingerprint:crmCapabilityConfigurationFingerprint(configuration),evaluationReference:configuration.capability==='mail_capture'?configuration.evaluationReceipt:'synthetic bounded acceptance',accessGrantReference:'synthetic actual grant',dataHandlingReference:'synthetic handling',providerAcceptanceReference:'synthetic HTTP acceptance',deletionAcceptanceReference:'synthetic deletion',fundingReference:'synthetic funding',oauthGrantObservationId:observed,release:{reference:releaseReference,implementationCommit:FIXTURE_CI_COMMIT,apiImageDigest:FIXTURE_API_DIGEST,workerImageDigest:FIXTURE_WORKER_DIGEST,schemaVersion:88,nativeAcceptanceReference:'synthetic native'}}};await fixture.db.query('SET ROLE migration');try{expect(await provisionCrmCapabilityAuthority(fixture.db,r)).toMatchObject({ok:true});}finally{await fixture.db.query('RESET ROLE');}return r.id;}
 await fixture.db.query('UPDATE crm_business_policies SET disclosure_version=$3,disclosure_sha256=$4 WHERE workspace_id=$1 AND mailbox_id=$2',[seeded.workspaceId,seeded.mailbox.id,METADATA_REVIEW_DISCLOSURE.version,METADATA_REVIEW_DISCLOSURE.sha256]);
 const metadata=(await readCrmCapability(context,{capability:'metadata_review',mailboxId:seeded.mailbox.id},runtime))!.configuration!;
 const metadataAuthority=await provision({...metadata,revision:2});expect(await activateCrmCapability(context,{capability:'metadata_review',mailboxId:seeded.mailbox.id,expectedRevision:1,authorityReceiptId:metadataAuthority},runtime)).toMatchObject({ok:true});
 await fixture.db.query('UPDATE crm_mail_capture_controls SET enabled=false,policy_revision=2,disclosure_version=$3,disclosure_sha256=$4,release_receipt=$5 WHERE workspace_id=$1 AND mailbox_id=$2',[seeded.workspaceId,seeded.mailbox.id,CRM_MAIL_CAPTURE_DISCLOSURE.version,CRM_MAIL_CAPTURE_DISCLOSURE.sha256,releaseReference]);
 const capture=(await readCrmCapability(context,{capability:'mail_capture',mailboxId:seeded.mailbox.id},runtime))!.configuration!;
 const captureAuthority=await provision({...capture,revision:2});expect(await activateCrmCapability(context,{capability:'mail_capture',mailboxId:seeded.mailbox.id,expectedRevision:1,authorityReceiptId:captureAuthority},runtime)).toMatchObject({ok:true});
 await fixture.db.query("UPDATE jobs SET payload=payload||'{\"controlsRevision\":2,\"policyRevision\":2}'::jsonb WHERE workspace_id=$1 AND id=$2",[seeded.workspaceId,seeded.job.id]);
 const job={...seeded.job,payload:{...seeded.job.payload,controlsRevision:2,policyRevision:2}};
 const verifiers=createCrmCapabilityVerifiers({runtime,openSession:async()=>({session:verifierSession,close:async()=>{}})});
 return {runtime,context,session,job,metadataAuthority,captureAuthority,verifiers,provision};
}
for(const revoked of [false,true])it(`registered actual-registry Gmail capture ${revoked?'refuses publication after revocation':'publishes current owner original'}`,async()=>{
 const fixture=await createAuthFixture();try{const seeded=await seedCapture(fixture);const authority=await authorize(fixture,seeded);let calls=0;
 const gmail=createGmailHttpClient({apiBaseUrl:'https://gmail.example.test',fetch:async url=>{calls++;const full=new URL(url).searchParams.get('format')==='full';if(full&&revoked){await fixture.db.query('SET ROLE migration');try{await revokeCrmCapabilityAuthority(fixture.db,{workspaceId:seeded.workspaceId,authorityReceiptId:authority.captureAuthority,reference:'synthetic revoke after body read'});}finally{await fixture.db.query('RESET ROLE');}}return {status:200,headers:{},body:JSON.stringify({id:'approved-message',threadId:'approved-thread',internalDate:String(Date.now()),labelIds:['SENT'],payload:{mimeType:'text/plain',headers:[{name:'From',value:'business@example.test'},{name:'To',value:'person@example.test'}],...full?{body:{data:Buffer.from('Original business reply').toString('base64url')}}:{}}})};}});
 const handler=registerHandlers(new HandlerRegistry(),{classifier:undefined,mail:undefined,send:undefined,research:undefined,crmMailCapture:{proofVerifier:authority.verifiers.captureVerifier,provider:createGmailMailCaptureProvider({gmail,resolveAccess:async()=>({mailboxId:seeded.mailbox.id,providerAccountId:'google-business',generation:1,access:{accessToken:'synthetic-only',expiresAtEpochSeconds:Date.now()/1000+3600}})})}}).get('crm.mail_capture')!;
 await handler.handle({session:authority.session,scope:workspaceScope(seeded.workspaceId,{kind:'system',component:'worker'}),job:authority.job});expect(calls).toBe(2);
 const rows=(await fixture.db.query('SELECT * FROM crm_mail_sources WHERE workspace_id=$1',[seeded.workspaceId])).rows;expect(rows).toHaveLength(revoked?0:1);if(!revoked){expect((await fixture.db.query('SELECT direction FROM mail_messages WHERE id=$1',[rows[0]!['source_id']])).rows[0]).toMatchObject({direction:'outgoing'});expect(rows[0]).toMatchObject({sent_proof:false,owner_user_id:seeded.ownerUserId});}
 }finally{await fixture.stop();}
});
it('revoked metadata authority vetoes new CRM observation while operational metadata is separate',async()=>{const fixture=await createAuthFixture();try{const seeded=await seedCapture(fixture);const a=await authorize(fixture,seeded);const observer=createApprovedBusinessMailObserver({revalidateAuthority:a.verifiers.revalidateMetadata});await fixture.db.query('SET ROLE migration');try{await revokeCrmCapabilityAuthority(fixture.db,{workspaceId:seeded.workspaceId,authorityReceiptId:a.metadataAuthority,reference:'synthetic metadata revoke'});}finally{await fixture.db.query('RESET ROLE');}const result=await withTransaction(a.session,()=>observer.observe(repositoryContext(workspaceScope(seeded.workspaceId,{kind:'system',component:'worker'}),a.session),{mailboxId:seeded.mailbox.id,ownerUserId:seeded.ownerUserId,providerAccountId:'google-business',generation:1,metadata:{id:'new-message',threadId:'new-thread',internalDateEpochMilliseconds:Date.now(),attachments:[],sizeEstimate:100,labelIds:['INBOX'],headers:{}}}));expect(result).toMatchObject({ok:false,reason:'metadata_observation_unavailable'});expect((await fixture.db.query("SELECT id FROM crm_business_conversations WHERE provider_thread_id='new-thread'")).rows).toHaveLength(0);}finally{await fixture.stop();}});

for(const revoked of [false,true])it(`bounded historical registry ${revoked?'revocation conserves observed quota and refuses progress':'preserves the independently approved frozen interval'}`,async()=>{
 const fixture=await createAuthFixture();try{const seeded=await seedCapture(fixture);const a=await authorize(fixture,seeded);
 const {requestCrmMailImport}=await import('@fss/domain/mail/crmBackfill.ts');const {readBackfillAuthority}=await import('@fss/domain/mail/crmBackfillAuthority.ts');const {readBackfillAllocation}=await import('@fss/domain/mail/crmBackfillBudget.ts');const {recordedGmailClient}=await import('@fss/domain/mail/gmailClientFake.ts');
 const imported=await withTransaction(a.session,()=>requestCrmMailImport(a.context,{mailboxId:seeded.mailbox.id}));if(!imported.ok)throw new Error('synthetic import unavailable');const importId=imported.value.importId;
 await fixture.db.query("INSERT INTO crm_mail_import_allocations(workspace_id,mailbox_id,revision,owner_user_id,account_binding,generation,project_hash,user_hash,user_limit_units,project_limit_units,user_headroom_units,project_headroom_units,profile_units,list_units,history_units,metadata_units,body_units,verification_sha256,verified_until) VALUES($1,$2,1,$3,$4,1,repeat('c',64),repeat('d',64),1000,1000,100,100,1,1,1,1,1,repeat('e',64),clock_timestamp()+interval '1 hour')",[seeded.workspaceId,seeded.mailbox.id,seeded.ownerUserId,seeded.binding]);
 const system=repositoryContext(workspaceScope(seeded.workspaceId,{kind:'system',component:'worker'}),a.session);const authority=await readBackfillAuthority(system,importId),allocation=await readBackfillAllocation(system,seeded.mailbox.id);if(!authority||!allocation)throw new Error('synthetic bounded configuration absent');
 const backfillId=await a.provision({capability:'mail_backfill',workspaceId:seeded.workspaceId,ownerUserId:seeded.ownerUserId,revision:allocation.revision,mailboxId:seeded.mailbox.id,providerAccountId:'google-business',generation:1,accountBinding:seeded.binding,scopeFingerprint:crmBackfillScopeFingerprint(authority),allocationFingerprint:crmBackfillAllocationFingerprint(allocation)});
 expect(await a.verifiers.allocationVerifier.verify(allocation,authority)).toBe(true);expect(await a.verifiers.allocationVerifier.verify({...allocation,body_units:2},authority)).toBe(false);
 let profiles=0;let lists=0;const original=recordedGmailClient({emailAddress:'business@example.test',historyId:'100',messages:[]});const gmail={...original,getProfile:async(access:Parameters<typeof original.getProfile>[0])=>{profiles++;if(revoked){await fixture.db.query('SET ROLE migration');try{await revokeCrmCapabilityAuthority(fixture.db,{workspaceId:seeded.workspaceId,authorityReceiptId:backfillId,reference:'synthetic bounded revoke during provider'});}finally{await fixture.db.query('RESET ROLE');}}return original.getProfile(access);},listMessageIds:async(...args:Parameters<typeof original.listMessageIds>)=>{lists++;return original.listMessageIds(...args);}};
 const job=(await claimJobs(a.session,{owner:'synthetic-history',kinds:['crm.mail_backfill'],limit:1,leaseSeconds:120}))[0]!;
 const handler=registerHandlers(new HandlerRegistry(),{classifier:undefined,mail:undefined,send:undefined,research:undefined,crmMailBackfill:{gmail,resolveAccess:async()=>({mailboxId:seeded.mailbox.id,providerAccountId:'google-business',generation:1,access:{accessToken:'synthetic-only',expiresAtEpochSeconds:Date.now()/1000+3600}}),proofVerifier:a.verifiers.captureVerifier,allocationVerifier:a.verifiers.allocationVerifier,observer:createApprovedBusinessMailObserver({revalidateAuthority:a.verifiers.revalidateMetadata})}}).get('crm.mail_backfill')!;
 if(revoked)await expect(handler.handle({session:a.session,scope:system.scope,job})).rejects.toThrow('quota_or_authority_unavailable');else await handler.handle({session:a.session,scope:system.scope,job});
 expect(profiles).toBe(1);expect(lists).toBe(revoked?0:1);const after=await readBackfillAuthority(system,importId);expect(after?.fromEpochMicroseconds).toBe(authority.fromEpochMicroseconds);expect(after?.toEpochMicroseconds).toBe(authority.toEpochMicroseconds);expect(after?.historyAnchor).toBe(revoked?null:'100');
 expect((await fixture.db.query("SELECT method,state FROM crm_mail_import_read_reservations WHERE workspace_id=$1 AND import_id=$2 ORDER BY reserved_at",[seeded.workspaceId,importId])).rows).toEqual(revoked?[{method:'profile',state:'observed'}]:[{method:'profile',state:'observed'},{method:'list',state:'observed'}]);
 }finally{await fixture.stop();}
});
for(const mutation of ['revoke','disable']as const)it(`holds authority/control publication locks against concurrent ${mutation}`,async()=>{const fixture=await createAuthFixture();try{const seeded=await seedCapture(fixture);const a=await authorize(fixture,seeded);const competing=mutation==='revoke'?fixture.db:await fixture.database.appRuntimeSession();if(mutation==='revoke')await competing.query('SET ROLE migration');await competing.query("SET statement_timeout='150ms'");let release=()=>{};const held=new Promise<void>(resolve=>{release=resolve;});let ready=()=>{};const acquired=new Promise<void>(resolve=>{ready=resolve;});const observer=createApprovedBusinessMailObserver({revalidateAuthority:async(context,input)=>{const valid=await a.verifiers.revalidateMetadata(context,input);ready();await held;return valid;}});const work=withTransaction(a.session,()=>observer.observe(repositoryContext(workspaceScope(seeded.workspaceId,{kind:'system',component:'worker'}),a.session),{mailboxId:seeded.mailbox.id,ownerUserId:seeded.ownerUserId,providerAccountId:'google-business',generation:1,metadata:{id:'locked-message',threadId:'locked-thread',internalDateEpochMilliseconds:Date.now(),attachments:[],sizeEstimate:100,labelIds:['INBOX'],headers:{From:'prospect@example.test',To:'business@example.test'}}}));await acquired;
 try{const action=mutation==='revoke'?revokeCrmCapabilityAuthority(competing,{workspaceId:seeded.workspaceId,authorityReceiptId:a.metadataAuthority,reference:'concurrent synthetic revoke'}):competing.query('UPDATE crm_business_policies SET enabled=false,revision=revision+1 WHERE workspace_id=$1 AND mailbox_id=$2',[seeded.workspaceId,seeded.mailbox.id]);await expect(action).rejects.toMatchObject({code:'57014'});}finally{release();}await work;expect((await fixture.db.query("SELECT id FROM crm_business_conversations WHERE provider_thread_id='locked-thread'")).rows).toHaveLength(1);
 }finally{await fixture.stop();}});
it('revocation between Ask dispatch proof and markCalling releases reservation without disclosure',async()=>{
 const fixture=await createAuthFixture();try{const seeded=await seedCapture(fixture);const a=await authorize(fixture,seeded);const {saveCrmAskPurpose}=await import('@fss/domain/crm/capabilityAuthority.ts');const {dispatch}=await import('../src/server.ts');const {issueSessionFor}=await import('./support/sessionFixture.ts');const {CURRENT_CLIENT_VERSION}=await import('./support/authFixture.ts');const {runOnce}=await import('../../worker/src/runner/jobRunner.ts');const {personPageSchema}=await import('@fss/contracts');const token=(await issueSessionFor(fixture,fixture.alpha,fixture.alpha.admin)).accessToken;
 const post=(path:string,body:unknown)=>dispatch({method:'POST',path,body,query:new URLSearchParams(),headers:{authorization:`Bearer ${token}`}},{session:a.session,auth:{...fixture.deps,db:a.session},supportedClientVersions:fixture.deps.config.supportedClientVersions,sendingEnabled:false});const command=(value:Record<string,unknown>)=>({...value,commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION});
 expect(await withTransaction(a.session,()=>saveCrmAskPurpose(a.context,crmAskPurposeSaveSchema.parse(command({purpose:'answer',expectedRevision:0,enabled:false,endpointId:'synthetic-answer',modelVersion:'literal-v1',accessGrantVersion:'independent-answer-grant',dataHandlingVersion:'independent-answer-handling',evaluationFingerprint:'a'.repeat(64),processorVersion:'ask-answer-v1',retrievalVersion:'lexical-original-v1',answerVersion:'literal-v1',supportVersion:'exact-original-v1',chunkerVersion:'lexical-original-v1',dailyCeilingCents:10,monthlyCeilingCents:100,inputTokenPriceMicros:1,outputTokenPriceMicros:1}))))).toMatchObject({ok:true});
 const configuration=(await readCrmCapability(a.context,{capability:'ask_answer'},a.runtime))!.configuration!;const answerReceipt=await a.provision({...configuration,revision:2});expect(await activateCrmCapability(a.context,{capability:'ask_answer',expectedRevision:1,authorityReceiptId:answerReceipt},a.runtime)).toMatchObject({ok:true});
 const created=await post('/crm/people/create',command({fullName:'Synthetic Ask owner'}));const personId=(await import('zod')).z.object({result:(await import('zod')).z.object({personId:(await import('zod')).z.uuid()})}).parse(created.body).result.personId;
 await post('/crm/people/source/add',command({personId,sourceKey:'ask-race-source',excerpt:'We need faster repairs.',occurredAt:'2026-10-01T14:00:00Z'}));const source=personPageSchema.parse((await post('/crm/people/read',{personId})).body).sources[0]!;
 const request=await post('/ask/answers/request',command({question:'repairs',scope:{sources:[{workspaceId:source.workspaceId,sourceId:source.sourceId,revision:source.revision,contentHash:source.contentHash,kind:source.kind,locator:null}]}}));expect(request.body).toMatchObject({result:{state:'pending'}});
 let proofs=0,calls=0;const registry=registerHandlers(new HandlerRegistry(),{classifier:undefined,mail:undefined,send:undefined,research:undefined,crmAskAnswers:{verifyPurpose:async input=>{const proof=await a.verifiers.verifyAskPurpose(input);expect(proof).not.toBeNull();if(++proofs===2){await fixture.db.query('SET ROLE migration');try{await revokeCrmCapabilityAuthority(fixture.db,{workspaceId:seeded.workspaceId,authorityReceiptId:answerReceipt,reference:'synthetic revoke after dispatch proof'});}finally{await fixture.db.query('RESET ROLE');}}return proof;},revalidatePurpose:a.verifiers.revalidateAskPurpose,answer:{endpointId:'synthetic-answer',modelVersion:'literal-v1',providerKey:'synthetic-answer',run:async()=>{calls++;return {acceptance:'accepted',usage:{inputTokens:20,outputTokens:10},answer:null};}}}});
 await runOnce(a.session,{registry,owner:'synthetic-ask-race',limit:20});expect(proofs).toBe(2);expect(calls).toBe(0);expect((await fixture.db.query("SELECT dispatch_state FROM crm_ask_financial_receipts WHERE workspace_id=$1",[seeded.workspaceId])).rows).toEqual([{dispatch_state:'released'}]);expect((await fixture.db.query("SELECT state,settled_cents FROM provider_reservations WHERE workspace_id=$1 AND subject_kind='crm_ask_answer'",[seeded.workspaceId])).rows).toEqual([{state:'released',settled_cents:0}]);
 }finally{await fixture.stop();}
});
for(const revoked of [false,true])it(`historical original body ${revoked?'revocation blocks publication with both reads observed':'uses independently scoped allocation'}`,async()=>{const fixture=await createAuthFixture();try{const seeded=await seedCapture(fixture);const a=await authorize(fixture,seeded);const {requestCrmMailImport}=await import('@fss/domain/mail/crmBackfill.ts');const {readBackfillAuthority}=await import('@fss/domain/mail/crmBackfillAuthority.ts');const {readBackfillAllocation}=await import('@fss/domain/mail/crmBackfillBudget.ts');const {createHistoricalGmailMailCaptureProvider}=await import('@fss/domain/mail/crmBackfillCapture.ts');const imported=await withTransaction(a.session,()=>requestCrmMailImport(a.context,{mailboxId:seeded.mailbox.id}));if(!imported.ok)throw new Error('synthetic import missing');const importId=imported.value.importId;
 await fixture.db.query("INSERT INTO crm_mail_import_allocations(workspace_id,mailbox_id,revision,owner_user_id,account_binding,generation,project_hash,user_hash,user_limit_units,project_limit_units,user_headroom_units,project_headroom_units,profile_units,list_units,history_units,metadata_units,body_units,verification_sha256,verified_until) VALUES($1,$2,1,$3,$4,1,repeat('c',64),repeat('d',64),1000,1000,100,100,1,1,1,1,1,repeat('e',64),clock_timestamp()+interval '1 hour')",[seeded.workspaceId,seeded.mailbox.id,seeded.ownerUserId,seeded.binding]);
 const system=repositoryContext(workspaceScope(seeded.workspaceId,{kind:'system',component:'worker'}),a.session),scope=await readBackfillAuthority(system,importId),allocation=await readBackfillAllocation(system,seeded.mailbox.id);if(!scope||!allocation)throw new Error('synthetic scope missing');const receiptId=await a.provision({capability:'mail_backfill',workspaceId:seeded.workspaceId,ownerUserId:seeded.ownerUserId,revision:allocation.revision,mailboxId:seeded.mailbox.id,providerAccountId:'google-business',generation:1,accountBinding:seeded.binding,scopeFingerprint:crmBackfillScopeFingerprint(scope),allocationFingerprint:crmBackfillAllocationFingerprint(allocation)});
 const {createHash}=await import('node:crypto');const messageHash=createHash('sha256').update(JSON.stringify({accountBinding:seeded.binding,providerMessageId:'approved-message'})).digest('hex');await fixture.db.query("INSERT INTO crm_mail_import_messages(workspace_id,import_id,message_hash,provider_message_id,provider_thread_id,provider_at,scope,state) VALUES($1,$2,$3,'approved-message','approved-thread',clock_timestamp()-interval '1 second','historical','available')",[seeded.workspaceId,importId,messageHash]);const job={...a.job,payload:{...a.job.payload,acquisitionOrigin:{importId}}};await fixture.db.query('UPDATE jobs SET payload=$3::jsonb WHERE workspace_id=$1 AND id=$2',[seeded.workspaceId,job.id,JSON.stringify(job.payload)]);
 const gmail=createGmailHttpClient({apiBaseUrl:'https://gmail.example.test',fetch:async url=>{const full=new URL(url).searchParams.get('format')==='full';if(full&&revoked){await fixture.db.query('SET ROLE migration');try{await revokeCrmCapabilityAuthority(fixture.db,{workspaceId:seeded.workspaceId,authorityReceiptId:receiptId,reference:'synthetic bounded body revoke'});}finally{await fixture.db.query('RESET ROLE');}}return {status:200,headers:{},body:JSON.stringify({id:'approved-message',threadId:'approved-thread',internalDate:String(Date.now()-1000),labelIds:['SENT'],payload:{mimeType:'text/plain',headers:[{name:'From',value:'business@example.test'},{name:'To',value:'person@example.test'}],...full?{body:{data:Buffer.from('Historical business reply').toString('base64url')}}:{}}})};}});const deps={gmail,resolveAccess:async()=>({mailboxId:seeded.mailbox.id,providerAccountId:'google-business',generation:1,access:{accessToken:'synthetic-only',expiresAtEpochSeconds:Date.now()/1000+3600}}),proofVerifier:a.verifiers.captureVerifier,allocationVerifier:a.verifiers.allocationVerifier};const handler=registerHandlers(new HandlerRegistry(),{classifier:undefined,mail:undefined,send:undefined,research:undefined,crmMailCapture:{provider:createGmailMailCaptureProvider(deps),proofVerifier:deps.proofVerifier,historicalProvider:createHistoricalGmailMailCaptureProvider(deps)}}).get('crm.mail_capture')!;const run=()=>handler.handle({session:a.session,scope:system.scope,job});if(revoked)await expect(run()).rejects.toThrow('historical_capture_authority_changed');else await run();expect((await fixture.db.query('SELECT source_id FROM crm_mail_sources WHERE workspace_id=$1',[seeded.workspaceId])).rows).toHaveLength(revoked?0:1);expect((await fixture.db.query('SELECT method,state FROM crm_mail_import_read_reservations WHERE import_id=$1 ORDER BY reserved_at',[importId])).rows).toEqual([{method:'metadata',state:'observed'},{method:'body',state:'observed'}]);
 }finally{await fixture.stop();}});
it('normal Gmail capture revocation during metadata prevents the next body request',async()=>{const fixture=await createAuthFixture();try{const seeded=await seedCapture(fixture);const a=await authorize(fixture,seeded);let metadataReads=0,bodyReads=0;const gmail=createGmailHttpClient({apiBaseUrl:'https://gmail.example.test',fetch:async url=>{const full=new URL(url).searchParams.get('format')==='full';if(full)bodyReads++;else{metadataReads++;await fixture.db.query('SET ROLE migration');try{await revokeCrmCapabilityAuthority(fixture.db,{workspaceId:seeded.workspaceId,authorityReceiptId:a.captureAuthority,reference:'synthetic revoke during metadata read'});}finally{await fixture.db.query('RESET ROLE');}}return {status:200,headers:{},body:JSON.stringify({id:'approved-message',threadId:'approved-thread',internalDate:String(Date.now()-1000),labelIds:['INBOX'],payload:{headers:[{name:'From',value:'prospect@example.test'},{name:'To',value:'business@example.test'}]}})};}});const {composeCrmGmail}=await import('../../worker/src/bootstrap/crmGmail.ts');const composition=composeCrmGmail({gmail,resolveAccess:async()=>({mailboxId:seeded.mailbox.id,providerAccountId:'google-business',generation:1,access:{accessToken:'synthetic-only',expiresAtEpochSeconds:Date.now()/1000+3600}}),proofVerifier:a.verifiers.captureVerifier,allocationVerifier:a.verifiers.allocationVerifier,observer:createApprovedBusinessMailObserver({revalidateAuthority:a.verifiers.revalidateMetadata})});const handler=registerHandlers(new HandlerRegistry(),{classifier:undefined,mail:undefined,send:undefined,research:undefined,...composition}).get('crm.mail_capture')!;await expect(handler.handle({session:a.session,scope:workspaceScope(seeded.workspaceId,{kind:'system',component:'worker'}),job:a.job})).rejects.toThrow('CRM mail capture authority unavailable');expect(metadataReads).toBe(1);expect(bodyReads).toBe(0);expect((await fixture.db.query('SELECT source_id FROM crm_mail_sources WHERE workspace_id=$1',[seeded.workspaceId])).rows).toHaveLength(0);}finally{await fixture.stop();}});

it('workspace Ask activation does not grant another owner private originals',async()=>{
 const fixture=await createAuthFixture();try{const seeded=await seedCapture(fixture);const a=await authorize(fixture,seeded);const {saveCrmAskPurpose}=await import('@fss/domain/crm/capabilityAuthority.ts');const {dispatch}=await import('../src/server.ts');const {issueSessionFor}=await import('./support/sessionFixture.ts');const {CURRENT_CLIENT_VERSION}=await import('./support/authFixture.ts');const {runOnce}=await import('../../worker/src/runner/jobRunner.ts');const {personPageSchema}=await import('@fss/contracts');const token=(await issueSessionFor(fixture,fixture.alpha,fixture.alpha.admin)).accessToken;
 const post=(path:string,body:unknown)=>dispatch({method:'POST',path,body,query:new URLSearchParams(),headers:{authorization:`Bearer ${token}`}},{session:a.session,auth:{...fixture.deps,db:a.session},supportedClientVersions:fixture.deps.config.supportedClientVersions,sendingEnabled:false});const command=(value:Record<string,unknown>)=>({...value,commandId:randomUUID(),clientVersion:CURRENT_CLIENT_VERSION});
 expect(await withTransaction(a.session,()=>saveCrmAskPurpose(a.context,crmAskPurposeSaveSchema.parse(command({purpose:'answer',expectedRevision:0,enabled:false,endpointId:'synthetic-answer',modelVersion:'literal-v1',accessGrantVersion:'independent-answer-grant',dataHandlingVersion:'independent-answer-handling',evaluationFingerprint:'a'.repeat(64),processorVersion:'ask-answer-v1',retrievalVersion:'lexical-original-v1',answerVersion:'literal-v1',supportVersion:'exact-original-v1',chunkerVersion:'lexical-original-v1',dailyCeilingCents:10,monthlyCeilingCents:100,inputTokenPriceMicros:1,outputTokenPriceMicros:1}))))).toMatchObject({ok:true});
 const configuration=(await readCrmCapability(a.context,{capability:'ask_answer'},a.runtime))!.configuration!;const answerReceipt=await a.provision({...configuration,revision:2});expect(await activateCrmCapability(a.context,{capability:'ask_answer',expectedRevision:1,authorityReceiptId:answerReceipt},a.runtime)).toMatchObject({ok:true});

 const otherToken=(await issueSessionFor(fixture,fixture.alpha,fixture.alpha.salesperson)).accessToken;
 const otherPost=(path:string,body:unknown)=>dispatch({method:'POST',path,body,query:new URLSearchParams(),headers:{authorization:`Bearer ${otherToken}`}},{session:a.session,auth:{...fixture.deps,db:a.session},supportedClientVersions:fixture.deps.config.supportedClientVersions,sendingEnabled:false});
 const z=(await import('zod')).z;const personId=z.object({result:z.object({personId:z.uuid()})}).parse((await otherPost('/crm/people/create',command({fullName:'Other private source owner'}))).body).result.personId;
 expect((await otherPost('/crm/people/source/add',command({personId,sourceKey:'other-owned-original',excerpt:'We need faster repairs.',occurredAt:'2026-10-01T14:00:00Z'}))).status).toBe(200);const source=personPageSchema.parse((await post('/crm/people/read',{personId})).body).sources[0]!;
 const request=await post('/ask/answers/request',command({question:'repairs',scope:{sources:[{workspaceId:source.workspaceId,sourceId:source.sourceId,revision:source.revision,contentHash:source.contentHash,kind:source.kind,locator:null}]}}));expect(request.body).toMatchObject({result:{state:'pending'}});
 let calls=0,refusals=0;const registry=registerHandlers(new HandlerRegistry(),{classifier:undefined,mail:undefined,send:undefined,research:undefined,crmAskAnswers:{verifyPurpose:async input=>{const proof=await a.verifiers.verifyAskPurpose(input);expect(proof).toBeNull();refusals++;return proof;},revalidatePurpose:a.verifiers.revalidateAskPurpose,answer:{endpointId:'synthetic-answer',modelVersion:'literal-v1',providerKey:'synthetic-answer',run:async()=>{calls++;return {acceptance:'accepted',usage:{inputTokens:20,outputTokens:10},answer:null};}}}});await runOnce(a.session,{registry,owner:'synthetic-other-owner',limit:20});expect(refusals).toBe(1);expect(calls).toBe(0);expect((await fixture.db.query("SELECT id FROM provider_reservations WHERE workspace_id=$1 AND subject_kind='crm_ask_answer'",[seeded.workspaceId])).rows).toHaveLength(0);expect((await fixture.db.query("SELECT state FROM crm_ask_requests WHERE workspace_id=$1",[seeded.workspaceId])).rows).toEqual([{state:'unavailable'}]);
 }finally{await fixture.stop();}
});
