import {expect,it,vi} from 'vitest';
import {stageLinkedInText} from '../src/main/social/adapters/linkedinStage.ts';
import type {ApprovedPost} from '../src/main/social/adapters.ts';
const post:ApprovedPost={deliveryId:'d',postId:'p',revision:1,account:{platform:'linkedin',externalId:'profile',displayName:'Founder'},text:'Approved text',images:[],publishAt:'2026-11-02T15:00:00Z',zone:'America/New_York',fingerprint:'hash'};
function setup(){let current=true;const view={zone:'America/New_York',kind:'composer',postingName:'Founder',text:'',date:null as string|null,time:null as string|null,identities:[] as {name:string;selected:boolean}[],scheduleLabel:null as string|null};const actions:string[]=[];
 const contents={getURL:()=> 'https://www.linkedin.com/sharing/compose',insertText:vi.fn(async(text:string)=>{view.text=text;}),executeJavaScriptInIsolatedWorld:vi.fn(async(_world:number,scripts:{code:string}[])=>{const input=JSON.parse(scripts[0]!.code.match(/const input=(.*);/)![1]!) as {action:string;date:string;time:string};actions.push(input.action);switch(input.action){case 'read':return {ok:true,view:structuredClone(view)};case 'openIdentity':view.identities=view.identities.length?[]:[{name:'Founder',selected:true}];break;case 'openSchedule':view.kind='schedule';break;case 'fillSchedule':view.date=input.date;view.time=input.time;break;case 'confirmSchedule':view.kind='composer';view.scheduleLabel='Posting at Mon, Nov 2, 10:00 AM';break;}return {ok:true};})};return {view,actions,contents,current:()=>current,now:()=>Date.parse('2026-10-06T12:00:00Z'),wait:async()=>{},stop:()=>{current=false;}};}
it('stages exact text and native wall-clock time, reads back, and never submits',async()=>{const p=setup();expect(await stageLinkedInText(post,p)).toEqual({ready:true});expect(p.contents.insertText).toHaveBeenCalledWith(post.text);expect(p.view.date).toBe('11/02/2026');expect(p.view.time).toBe('10:00 AM');expect(p.actions).not.toContain('submit');});
it('refuses wrong destinations, images not yet verified, and expired times before text entry',async()=>{const p=setup();p.view.postingName='Company';expect(await stageLinkedInText(post,p)).toMatchObject({ready:false});expect(p.contents.insertText).not.toHaveBeenCalled();const q=setup();expect(await stageLinkedInText({...post,images:[{} as never]},q)).toEqual({ready:false,reason:'format_not_verified'});expect(await stageLinkedInText({...post,publishAt:'2020-01-01T00:00:00Z'},q)).toMatchObject({ready:false});});
it('refuses changed readback and sign-out during insertion',async()=>{const p=setup();p.contents.insertText.mockImplementation(async()=>{p.view.text='Different text';});expect(await stageLinkedInText(post,p)).toEqual({ready:false,reason:'content_mismatch'});const q=setup();q.contents.insertText.mockImplementation(async()=>{q.stop();});expect(await stageLinkedInText(post,q)).toMatchObject({ready:false});});
it('refuses repeated DST wall-clock times that the native form cannot disambiguate',async()=>{const p=setup();expect(await stageLinkedInText({...post,publishAt:'2026-11-01T05:30:00Z'},p)).toEqual({ready:false,reason:'ambiguous_platform_time'});expect(p.actions).not.toContain('confirmSchedule');});
it('does not overwrite an existing native text draft',async()=>{const p=setup();p.view.text='My unfinished personal post';expect(await stageLinkedInText(post,p)).toEqual({ready:false,reason:'existing_draft'});expect(p.contents.insertText).not.toHaveBeenCalled();expect(p.actions).not.toContain('openIdentity');});
