import sharp from 'sharp';
import {it,expect,vi} from 'vitest';import {mkdtemp,writeFile,rm,symlink} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createHash} from 'node:crypto';
import {stageLinkedInImages} from '../src/main/social/adapters/linkedinImages.ts';
const png=await sharp({create:{width:2,height:2,channels:3,background:'red'}}).png().toBuffer(),hash=createHash('sha256').update(png).digest('hex');
it('sends only approved image bytes under generic filenames through an isolated input action',async()=>{const root=await mkdtemp(join(tmpdir(),'social-images-'));try{const path=join(root,'private-name.png');await writeFile(path,png);const execute=vi.fn(async(..._args:unknown[])=>({ok:true,count:1}));expect(await stageLinkedInImages([{localPath:path,sha256:hash}],{root,current:()=>true,contents:{getURL:()=> 'https://www.linkedin.com/sharing/compose',executeJavaScriptInIsolatedWorld:execute}})).toEqual({ready:true});const code=execute.mock.calls[0]?.[1] as unknown;expect(JSON.stringify(code)).toContain('image-1.png');expect(JSON.stringify(code)).not.toContain('private-name');}finally{await rm(root,{recursive:true,force:true});}});
it('refuses changed bytes, paths outside its private directory, and symlinks before browser handoff',async()=>{const root=await mkdtemp(join(tmpdir(),'social-images-'));try{const path=join(root,'image.png');await writeFile(path,png);await symlink(path,join(root,'link.png'));const execute=vi.fn(async(..._args:unknown[])=>({ok:true,count:1}));const ports={root,current:()=>true,contents:{getURL:()=> 'https://www.linkedin.com/sharing/compose',executeJavaScriptInIsolatedWorld:execute}};for(const image of [{localPath:path,sha256:'0'.repeat(64)},{localPath:path,sha256:hash},{localPath:join(root,'link.png'),sha256:hash}]){const p=image.localPath===path&&image.sha256===hash?{...ports,root:join(root,'other')}:ports;expect(await stageLinkedInImages([image],p)).toMatchObject({ready:false});}expect(execute).not.toHaveBeenCalled();}finally{await rm(root,{recursive:true,force:true});}});
it('does not transfer bytes after sign-out or on another page',async()=>{const execute=vi.fn();expect(await stageLinkedInImages([],{root:'/unused',current:()=>false,contents:{getURL:()=> 'https://www.linkedin.com/sharing/compose',executeJavaScriptInIsolatedWorld:execute}})).toMatchObject({ready:false});expect(execute).not.toHaveBeenCalled();});
it('refuses a hash-matching file that still contains private photo metadata',async()=>{
 const root=await mkdtemp(join(tmpdir(),'social-images-'));try{
 const bytes=await sharp(png).withMetadata().jpeg().toBuffer(),path=join(root,'photo.jpg');await writeFile(path,bytes);
 const execute=vi.fn();expect(await stageLinkedInImages([{localPath:path,sha256:createHash('sha256').update(bytes).digest('hex')}],{root,current:()=>true,contents:{getURL:()=> 'https://www.linkedin.com/sharing/compose',executeJavaScriptInIsolatedWorld:execute}})).toMatchObject({ready:false});expect(execute).not.toHaveBeenCalled();
 }finally{await rm(root,{recursive:true,force:true});}
});
