import {expect,it,vi} from 'vitest';
import {mkdtemp,readFile,readdir,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createHash} from 'node:crypto';import sharp from 'sharp';
import type {AuthedClient} from '../src/main/authedClient.ts';
import type {SocialDeliveryQueue} from '@fss/contracts';
import {withQueuedSocialPost} from '../src/main/social/queuedPost.ts';
const id='11111111-1111-4111-8111-111111111111';
const bytes=await sharp({create:{width:10,height:10,channels:3,background:'white'}}).png().toBuffer();const hash=createHash('sha256').update(bytes).digest('hex');
const item:SocialDeliveryQueue['items'][number]={deliveryId:id,postId:id,revision:1,action:'submit',submissionId:null,receiptId:null,fingerprint:'a'.repeat(64),snapshot:{account:{id,platform:'linkedin',externalId:'profile',revision:1,adapterVersion:'test-v1'},text:'Approved',publishAt:'2026-11-02T15:00:00.000Z',zone:'America/New_York',images:[{assetId:id,version:1,sha256:hash,mime:'image/png',width:10,height:10,altText:'White square'}]}};
function harness(){const account={id,platform:'linkedin',displayName:'Founder',externalId:'profile',accountKind:'profile',state:'connected',adapterVersion:'test-v1',verifiedAt:'2026-10-06T00:00:00.000Z'};const object={version:1,kind:'derivative',state:'ready',sha256:hash,mime:'image/png',width:10,height:10,bytes:bytes.length};
 const read=vi.fn(async(path:string,parse:(v:unknown)=>unknown,_body?:unknown)=>({ok:true,value:parse(path==='/social'?{accounts:[account],posts:[]}:path.endsWith('/read')?{asset:{id,state:'ready',version:2,origin:{kind:'upload',sourceUrl:null,usageNote:null},objects:[object,{...object,version:2,sha256:'b'.repeat(64)}]}}:{url:'https://bucket.s3.us-east-1.amazonaws.com/image',expiresAt:'2099-01-01T00:00:00.000Z'})}));return {account,object,read,api:{read,command:vi.fn()} as unknown as AuthedClient};}
it('uses the approved derivative version rather than newest and cleans files after callback',async()=>{const root=await mkdtemp(join(tmpdir(),'queued-social-'));try{const h=harness();const result=await withQueuedSocialPost(item,{root,current:()=>true,api:h.api,adapterVersion:'test-v1',send:async()=>new Response(new Uint8Array(bytes))},async post=>{expect(await readFile(post.images[0]!.localPath)).toEqual(bytes);expect(post.images[0]!.version).toBe(1);expect(post.account.displayName).toBe('Founder');return 'staged';});expect(result).toBe('staged');expect(h.read.mock.calls[2]?.[2]).toEqual({assetId:id,version:1});expect(await readdir(root)).toEqual([]);}finally{await rm(root,{recursive:true,force:true});}});
it('refuses changed asset metadata before fetching signed bytes',async()=>{const h=harness();h.object.sha256='c'.repeat(64);const use=vi.fn(),send=vi.fn();await expect(withQueuedSocialPost(item,{root:'/unused',current:()=>true,api:h.api,adapterVersion:'test-v1',send},use)).rejects.toThrow('approved_image_changed');expect(send).not.toHaveBeenCalled();expect(use).not.toHaveBeenCalled();expect(h.read).toHaveBeenCalledTimes(2);});
it('blocks unsupported or changed account adapters before looking up images',async()=>{const h=harness();h.account.state='unsupported';await expect(withQueuedSocialPost(item,{root:'/unused',current:()=>true,api:h.api,adapterVersion:'test-v1'},vi.fn())).rejects.toThrow('account_not_verified');expect(h.read).toHaveBeenCalledTimes(1);});
