import {expect,it,vi} from 'vitest';
import {createSocialDeliveryRunner} from '../src/main/social/deliveryRunner.ts';
import type {AuthedClient} from '../src/main/authedClient.ts';
import {operationHandlers,type OperationHostDeps} from '../src/main/operationHost.ts';
const id='11111111-1111-4111-8111-111111111111';
const account={id,platform:'linkedin',externalId:'profile',displayName:'Founder',accountKind:'profile',state:'connected',adapterVersion:'v1',verifiedAt:'2026-10-01T00:00:00Z'};
function fixture(){const command=vi.fn();const read=vi.fn(async(_path:string,parse:(raw:unknown)=>unknown)=>({ok:true,value:parse({accounts:[account],posts:[]})}));const check=vi.fn(async(_scope:unknown,_expected:unknown,report:(stage:'composer',outcome:'refused',reason:string)=>void)=>{report('composer','refused','private DOM secret');return {ready:false,reason:'private DOM secret'};});const runner=createSocialDeliveryRunner({api:{read,command} as unknown as AuthedClient,root:'/unused',identity:async()=>({workspaceId:id,userId:id}),now:()=>0,adapters:{linkedin:{version:'v1',open:async()=>{},check}}});return {read,command,check,runner};}
it('scopes explicit checks through authenticated social reads, sanitizes metadata and never calls a command',async()=>{const h=fixture();const handlers=operationHandlers({socialDelivery:h.runner} as unknown as OperationHostDeps);expect(await handlers['social.checkPreparation']({accountId:id} as never)).toEqual({ready:false,reason:'unknown',events:[{stage:'composer',outcome:'refused',reason:'unknown',at:'1970-01-01T00:00:00.000Z'}]});expect(h.command).not.toHaveBeenCalled();expect(h.read).toHaveBeenCalledWith('/social',expect.any(Function),{});expect(h.check).toHaveBeenCalledWith({workspaceId:id,userId:id,accountId:id,platform:'linkedin'},{platform:'linkedin',externalId:'profile',displayName:'Founder'},expect.any(Function));});
it('refuses unknown accounts and drops a late check after sign-out',async()=>{const h=fixture();expect(await h.runner.checkPreparation('22222222-2222-4222-8222-222222222222')).toMatchObject({ready:false});expect(h.check).not.toHaveBeenCalled();h.check.mockImplementation(async()=>{h.runner.resetStatus();return {ready:false,reason:'private old owner'};});expect(await h.runner.checkPreparation(id)).toEqual({ready:false,reason:'session_changed',events:[]});expect(h.runner.status()).toEqual({queue:'unread',lastReadAt:null});});
it('bounds one browser check metadata to 32 events',async()=>{const h=fixture();h.check.mockImplementation(async(_scope,_expected,report)=>{for(let i=0;i<100;i++)report('composer','refused','layout_changed');return {ready:false,reason:'layout_changed'};});expect((await h.runner.checkPreparation(id)).events).toHaveLength(32);});
it('refuses a ready browser result if the account is disconnected during its check',async()=>{const h=fixture();h.check.mockImplementation(async()=>{h.read.mockImplementation(async(_path,parse)=>({ok:true,value:parse({accounts:[{...account,state:'disconnected'}],posts:[]})}));return {ready:true} as never;});expect(await h.runner.checkPreparation(id)).toMatchObject({ready:false,reason:'session_changed',events:[]});});
it('drops diagnostics when an old owner check throws after sign-out',async()=>{const h=fixture();h.check.mockImplementation(async(_scope,_expected,report)=>{report('composer','refused','layout_changed');h.runner.resetStatus();throw new Error('old owner');});expect(await h.runner.checkPreparation(id)).toEqual({ready:false,reason:'session_changed',events:[]});});
