import {useEffect,useReducer,useRef,useState} from 'react';
import type {SocialWorkspace} from '@fss/contracts';
import {useSessionEpoch} from '../app/drafts.tsx';
import {operations} from '../app/bridges.ts';
import {Button} from '../ui/button.tsx';
type Input={accountId:string;commandId:string};type Answer={accepted:boolean;reason:string|null};
export interface AccountPorts{connect(input:Input):Promise<Answer>;disconnect(input:Input):Promise<Answer>}
const defaults:AccountPorts={connect:async input=>{const api=operations();if(!api)throw new Error('unavailable');return api.command('social.connectAccount',input);},disconnect:async input=>{const api=operations();if(!api)throw new Error('unavailable');return api.command('social.disconnectAccount',input);}};
type Pending=Input&{action:'connect'|'disconnect'};type Memory={pending:Pending|null;busy:boolean;message:string|null};
const fresh=():Memory=>({pending:null,busy:false,message:null}),memories=new WeakMap<object,Memory>();
export function SocialAccounts({accounts,onChanged,ports=defaults}:{accounts:SocialWorkspace['accounts'];onChanged():void;ports?:AccountPorts}){
 const epoch=useSessionEpoch(),[fallback]=useState(fresh),[,render]=useReducer(n=>n+1,0);let m=epoch?memories.get(epoch):fallback;if(!m){m=fresh();memories.set(epoch!,m);}const state=m,live=useRef(0);
 useEffect(()=>{const g=++live.current;state.busy=false;return()=>{live.current=g+1;};},[state]);
 const run=async(input:Pending)=>{if(state.busy)return;const g=live.current;state.pending=input;state.busy=true;state.message=input.action==='connect'?'Complete sign-in in the LinkedIn window. Callie will close it after checking your profile.':'Disconnecting this account…';render();
  try{const {action,...body}=input,answer=await ports[action](body);if(g!==live.current)return;if(answer.accepted){state.pending=null;state.message=action==='connect'?'Account saved. Scheduling still needs verification before posts can be sent.':'Disconnected. Existing platform schedules remain; reconnect to manage them.';onChanged();}else{const retry=['offline','unreadable_answer','connection_unavailable','login_cleanup_failed'].includes(answer.reason??'');if(!retry)state.pending=null;state.message=answer.reason==='account_identity_changed'?'Sign in to the original LinkedIn profile to reconnect this account.':retry?'The result is not confirmed. Retry the same connection action.':'Could not verify this account. Sign in to LinkedIn and try again.';}}catch{if(g===live.current)state.message='The result is not confirmed. Retry the same connection action.';}finally{if(g===live.current){state.busy=false;render();}}
 };
 return <details className="rounded-lg border border-border p-4"><summary className="cursor-pointer text-sm font-medium">Social accounts</summary><div className="mt-4 space-y-3 text-sm"><p className="text-muted-foreground">Connect opens a separate sign-in window. Background scheduling stays hidden.</p><Button variant="outline" disabled={state.busy||!!state.pending} onClick={()=>void run({action:'connect',accountId:crypto.randomUUID(),commandId:crypto.randomUUID()})}>Connect LinkedIn</Button>{accounts.map(a=><div key={a.id} className="flex items-center justify-between gap-3"><span>{a.displayName} · {a.platform} · {a.state==='unsupported'?'Scheduling not verified':a.state}</span><div className="flex gap-2">{a.platform==='linkedin'&&<Button variant="ghost" disabled={state.busy||!!state.pending} onClick={()=>void run({action:'connect',accountId:a.id,commandId:crypto.randomUUID()})}>Reconnect</Button>}<Button variant="ghost" disabled={state.busy||!!state.pending} onClick={()=>void run({action:'disconnect',accountId:a.id,commandId:crypto.randomUUID()})}>Disconnect</Button></div></div>)}{state.message&&<p role="status">{state.message}</p>}{state.pending&&!state.busy&&<Button variant="outline" onClick={()=>void run(state.pending!)}>Retry connection</Button>}</div></details>;
}
