import type {SocialDeliveryStatus,SocialPreparationResult} from '../../shared/socialDiagnostics.ts';
import {ManualHandoffPanel} from './ManualHandoffPanel.tsx';
import {ManualSocialDestination} from './ManualDestination.tsx';
import {SocialAccounts} from './SocialAccounts.tsx';
import {SocialDraftStudio} from './DraftStudio.tsx';
import {SocialImage} from './SocialImage.tsx';
import {AssetLibrary} from './AssetLibrary.tsx';
import {useEffect,useLayoutEffect,useReducer,useRef,useState} from 'react';
import type {SocialWorkspace,SocialPostMutation,SaveSocialPost,PostRevision} from '@fss/contracts';
import {useSessionEpoch} from '../app/drafts.tsx';import {operations} from '../app/bridges.ts';
import {Button} from '../ui/button.tsx';import {Input} from '../ui/input.tsx';import {socialScheduleInstants} from './scheduleTime.ts';
type DeliveryStatus=SocialDeliveryStatus;
export interface SocialPorts{checkPreparation?(accountId:string):Promise<SocialPreparationResult>;deliveryStatus?():Promise<DeliveryStatus>;read():Promise<{view:SocialWorkspace|null;reason:string|null}>;mutate(input:SocialPostMutation):Promise<{accepted:boolean;view:SocialWorkspace|null;reason:string|null}>}
const defaults:SocialPorts={checkPreparation:async(accountId)=>{const api=operations();if(!api)throw new Error('unavailable');return api.command('social.checkPreparation',{accountId});},deliveryStatus:async()=>{const api=operations();if(!api)throw new Error('unavailable');return api.read('social.deliveryStatus',{});},read:async()=>{const api=operations();if(!api)throw new Error('unavailable');return api.read('social.workspace',{});},mutate:async input=>{const api=operations();if(!api)throw new Error('unavailable');return api.command('social.mutate',input);}};
function BrowserPreparationChecks({accounts,check}:{accounts:SocialWorkspace['accounts'];check:NonNullable<SocialPorts['checkPreparation']>}){
 const [busy,setBusy]=useState(false),[result,setResult]=useState<Awaited<ReturnType<typeof check>>|null>(null);const generation=useRef(0);
 useLayoutEffect(()=>{const lifetime=generation;lifetime.current++;setBusy(false);setResult(null);return()=>{lifetime.current++;};},[accounts]);
 const run=async(accountId:string)=>{const g=++generation.current;setBusy(true);setResult(null);try{const answer=await check(accountId);if(g===generation.current)setResult(answer);}catch{if(g===generation.current)setResult({ready:false,reason:'preparation_unavailable',events:[]});}finally{if(g===generation.current)setBusy(false);}};
 return <details className="rounded-md border border-border p-3 text-sm"><summary>Check LinkedIn browser</summary><p>This check does not type, schedule or publish a post.</p>{accounts.filter(a=>a.platform==='linkedin'&&a.state==='connected').map(a=><div key={a.id}><span>{a.displayName} </span><Button disabled={busy} variant="outline" onClick={()=>void run(a.id)}>Check browser preparation</Button></div>)}{result&&<div role="status"><p>{result.ready?'Identity and empty composer verified. Scheduling acceptance is still unverified.':`Browser check needs attention: ${(result.reason??'unknown').replaceAll('_',' ')}.`}</p><ol>{result.events.map((e,i)=><li key={i}>{e.stage.replaceAll('_',' ')}: {e.outcome}{e.reason?` (${e.reason.replaceAll('_',' ')})`:''}</li>)}</ol></div>}</details>;
}
type Editor=SaveSocialPost&{local:string;instant:string};
type Memory={sessionKey:string;deliveryStatus:DeliveryStatus|null;previewReady:Set<string>;tab:'Drafts'|'Calendar'|'Assets';view:SocialWorkspace|null;editor:Editor|null;busy:boolean;error:string|null;pending:SocialPostMutation|null};
const fresh=():Memory=>({sessionKey:crypto.randomUUID(),deliveryStatus:null,previewReady:new Set(),tab:'Drafts',view:null,editor:null,busy:false,error:null,pending:null});const memories=new WeakMap<object,Memory>();
const stateLabel:Record<PostRevision['state'],string>={draft:'Draft',approved:'Pending scheduling',submitting:'Checking submission',scheduled:'Scheduled on platform',published:'Published',cancellation_pending:'Cancellation pending',cancelled:'Cancelled',failed:'Needs attention',unknown:'Awaiting platform confirmation'};
function recoveryMessage(post:PostRevision):string|null{
 if(post.state==='unknown'||post.state==='submitting'||post.state==='cancellation_pending')return 'Platform acceptance is uncertain. Check the original submission before replacing or posting manually.';
 if(post.state!=='failed')return null;
 if(['schedule_missed','schedule_in_past','claim_expired'].includes(post.reason??''))return 'This time was missed. Choose a new time and approve the revised post.';
 if(['account_identity_changed','account_not_verified'].includes(post.reason??''))return 'The destination could not be verified. Reconnect the correct account and approve a revised post.';
 if(post.reason==='adapter_unavailable')return 'Native delivery is unavailable for this account. Review a manual handoff or reconnect before approving a revised post.';
 if(post.reason==='approved_image_changed')return 'An approved image changed. Review the exact images and approve a revised post.';
 return 'This post needs review before a new approval. Confirm its platform status before any manual handoff.';
}
function localValue(instant:string,zone:string){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(instant)).map(v=>[v.type,v.value]));return `${p['year']}-${p['month']}-${p['day']}T${p['hour']}:${p['minute']}`;}
function message(reason:string|null){return ({stale_revision:'This post changed elsewhere. Refresh before saving.',destination_unverified:'Connect and verify this destination before scheduling.',facebook_page_required:'Choose a Facebook Page for business posts.',schedule_in_past:'Choose a future time.',content_needs_edit:'Edit this post to fit the selected platform.',cancel_before_edit:'Cancel the existing native schedule before editing.',image_unavailable:'An image changed or was removed. Review the images again.',approval_changed:'The approved content or account changed. Save a new revision.',already_published:'This post is already published. Create a new post to make changes.'}[reason??'']??'The action could not be completed. Refresh and try again.');}
export function SocialRoute({ports=defaults}:{ports?:SocialPorts}){
 const epoch=useSessionEpoch(),[fallback]=useState(fresh),[,render]=useReducer(n=>n+1,0);let found=epoch?memories.get(epoch):fallback;if(!found){found=fresh();memories.set(epoch!,found);}const m=found;const live=useRef(0),port=useRef(ports);port.current=ports;
 const touch=()=>render();
 useEffect(()=>{const g=++live.current;m.busy=false;m.deliveryStatus=null;const readDelivery=async()=>{if(!port.current.deliveryStatus)return;try{const status=await port.current.deliveryStatus();if(live.current===g){m.deliveryStatus=status;render();}}catch{if(live.current===g){m.deliveryStatus={queue:'unavailable',lastReadAt:m.deliveryStatus?.lastReadAt??null};render();}}};void readDelivery();const deliveryTimer=setInterval(()=>void readDelivery(),60_000);void port.current.read().then(answer=>{if(live.current!==g)return;if(answer.view)m.view=answer.view;else m.error=message(answer.reason);render();}).catch(()=>{if(live.current===g){m.error='Could not load social content. Your draft is kept.';render();}});return()=>{live.current=g+1;clearInterval(deliveryTimer);};},[m]);
 const run=async(input:SocialPostMutation)=>{if(m.busy)return;const g=live.current;m.busy=true;m.pending=input;m.error=null;touch();try{const result=await port.current.mutate(input);if(g!==live.current)return;if(result.accepted){m.pending=null;if(result.view)m.view=result.view;if(input.action==='save')m.editor=null;if(!result.view)m.error='Saved. Refresh to see the latest posts.';}else{if(!['offline','unreadable_answer'].includes(result.reason??''))m.pending=null;m.error=m.pending?'No definite answer. Retry the same action.':message(result.reason);}}catch{if(g===live.current)m.error='No definite answer. Retry the same action.';}finally{if(g===live.current){m.busy=false;touch();}}};
 const edit=(post?:PostRevision)=>{if(m.pending)return;const zone=post?.zone??Intl.DateTimeFormat().resolvedOptions().timeZone;m.editor=post?{postId:post.postId,expectedRevision:post.revision,accountId:post.accountId,text:post.text,images:post.images,publishAt:post.publishAt,zone,local:post.publishAt?localValue(post.publishAt,zone):'',instant:post.publishAt??''}:{accountId:m.view?.accounts[0]?.id??'',text:'',images:[],publishAt:null,zone,local:'',instant:''};touch();};
 const e=m.editor,choices=e?.local?socialScheduleInstants(e.local,e.zone):[];
 const save=()=>{if(!e)return;const instant=e.local?(choices.length===1?choices[0]!.instant:choices.find(v=>v.instant===e.instant)?.instant):null;if(e.local&&!instant){m.error=choices.length>1?'Choose which UTC offset you mean.':'That local time does not exist in this timezone.';touch();return;}const {local:_local,instant:_instant,...post}=e;void run({...post,publishAt:instant??null,action:'save',commandId:crypto.randomUUID()});};
 const list=(m.view?.posts??[]).filter(p=>m.tab==='Calendar'?p.state!=='draft':p.state==='draft'||p.state==='failed').sort((a,b)=>(a.publishAt??'').localeCompare(b.publishAt??''));
 return <section className="callie-v2 mx-auto w-full max-w-5xl space-y-6 px-8 py-7" aria-label="Social content">
  <header className="flex items-center justify-between"><div><h1 className="text-xl font-semibold tracking-tight">Social</h1><p className="mt-1 text-sm text-muted-foreground">Your voice, ready for the right moment.</p></div><Button disabled={m.busy||m.pending!==null||!m.view?.accounts.length} onClick={()=>edit()}>New post</Button></header>
  <div className="flex gap-5 border-b border-border" role="tablist">{(['Drafts','Calendar','Assets'] as const).map(tab=><button key={tab} role="tab" aria-selected={m.tab===tab} className="pb-3 text-sm aria-selected:border-b-2 aria-selected:border-foreground aria-selected:font-medium" onClick={()=>{m.tab=tab;touch();}}>{tab}</button>)}</div>
  {m.deliveryStatus?.queue==='unavailable'&&<div role="status" className="rounded-md border border-border p-3 text-sm"><p>Delivery queue is unavailable. Existing schedules and uncertain submissions are unchanged.</p>{m.deliveryStatus.lastReadAt?<p>Last successful delivery check: <time dateTime={m.deliveryStatus.lastReadAt}>{new Date(m.deliveryStatus.lastReadAt).toLocaleString()}</time></p>:<p>No successful delivery check is available in this session.</p>}</div>}
  {!!m.deliveryStatus?.diagnostics?.length&&<details className="rounded-md border border-border p-3 text-sm"><summary>Browser delivery checks</summary><p>Checks from this app session. A completed preparation step does not prove platform acceptance. Restart clears these details; saved delivery holds remain.</p>{m.deliveryStatus.diagnostics.filter(a=>m.view?.posts.some(p=>p.postId===a.postId&&p.revision===a.revision)).map(a=><div key={a.postId}><p>Post revision {a.revision}</p><ol>{a.events.map((e,i)=><li key={i}>{e.stage.replaceAll('_',' ')}: {e.outcome}{e.reason?` (${e.reason.replaceAll('_',' ')})`:''}</li>)}</ol></div>)}</details>}
  {m.error&&<div role="status" className="rounded-md border border-border p-3 text-sm">{m.error}{m.pending&&<Button variant="outline" className="ml-3" disabled={m.busy} onClick={()=>void run(m.pending!)}>Retry same action</Button>}</div>}
  <ManualSocialDestination key={m.sessionKey} ports={{register:async input=>{const api=operations();if(!api)throw new Error('unavailable');return api.command('social.registerManualDestination',input);}}} onAdded={()=>{const g=live.current;void port.current.read().then(a=>{if(g===live.current&&a.view){m.view=a.view;touch();}}).catch(()=>{});}}/><SocialAccounts accounts={m.view?.accounts??[]} onChanged={()=>{const g=live.current;void port.current.read().then(a=>{if(g===live.current&&a.view){m.view=a.view;touch();}}).catch(()=>{});}}/>
  {port.current.checkPreparation&&m.view&&<BrowserPreparationChecks key={m.sessionKey} accounts={m.view.accounts} check={port.current.checkPreparation}/>}
  {!m.view?.accounts.length&&<p className="text-sm text-muted-foreground">Connect a social account to choose where your drafts will go.</p>}
  {m.tab==='Drafts'&&!e&&<SocialDraftStudio disabled={m.busy||m.pending!==null||e!==null} onUse={variant=>{if(m.busy||m.pending||m.editor)return;const zone=Intl.DateTimeFormat().resolvedOptions().timeZone;m.editor={accountId:m.view?.accounts.find(a=>a.platform===variant.platform)?.id??'',text:variant.text,images:[],publishAt:null,zone,local:'',instant:''};touch();}}/>}
  {e&&m.tab!=='Assets'&&<div className="space-y-4 rounded-xl border border-border bg-card p-5">
   <label className="block text-sm">Post as<select aria-label="Post as" className="mt-2 block w-full rounded-md border border-input bg-background p-2" value={e.accountId} disabled={m.busy||m.pending!==null} onChange={event=>{e.accountId=event.target.value;touch();}}><option value="">Choose an account</option>{m.view?.accounts.map(a=><option key={a.id} value={a.id}>{a.displayName} · {a.platform}{a.accountKind==='page'?' Page':''}</option>)}</select></label>
   <label className="block text-sm">Post text<textarea aria-label="Post text" className="mt-2 min-h-48 w-full resize-y rounded-md border border-input bg-background p-3 leading-relaxed" value={e.text} disabled={m.busy||m.pending!==null} onChange={event=>{e.text=event.target.value;touch();}}/></label>
   <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Publish time<Input aria-label="Publish time" type="datetime-local" value={e.local} disabled={m.busy||m.pending!==null} onChange={event=>{e.local=event.target.value;e.instant='';touch();}}/></label><label className="text-sm">Timezone<Input aria-label="Timezone" value={e.zone} disabled={m.busy||m.pending!==null} onChange={event=>{e.zone=event.target.value;e.instant='';touch();}}/></label></div>
   {choices.length>1&&<label className="block text-sm">This time occurs twice<select aria-label="UTC offset" value={e.instant} onChange={event=>{e.instant=event.target.value;touch();}}><option value="">Choose an offset</option>{choices.map(v=><option value={v.instant} key={v.instant}>{v.label}</option>)}</select></label>}
   <Button variant="outline" disabled={m.busy||m.pending!==null} onClick={()=>{m.tab='Assets';touch();}}>Choose image</Button><div className="flex items-center gap-3"><Button disabled={m.busy||m.pending!==null||!e.text.trim()||!e.accountId} onClick={save}>Save draft</Button><Button variant="ghost" disabled={m.busy||m.pending!==null} onClick={()=>{m.editor=null;touch();}}>Discard changes</Button><span className="text-xs text-muted-foreground">Saving does not schedule a post.</span></div>
  </div>}
  {m.tab==='Assets'?<AssetLibrary onSelect={e?(image)=>{if(m.busy||m.pending)return;e.images=[...e.images.filter(item=>item.assetId!==image.assetId),image];m.tab='Drafts';touch();}:undefined}/>:<div className="space-y-3">{list.length===0&&!e&&<p className="py-10 text-center text-sm text-muted-foreground">{m.tab==='Calendar'?'No scheduled posts yet.':'Start with a short observation from your work.'}</p>}{list.map(p=><article key={`${p.postId}:${p.revision}`} className="space-y-3 rounded-xl border border-border bg-card p-5"><div className="flex justify-between text-xs text-muted-foreground"><span>{(()=>{const a=m.view?.accounts.find(a=>a.id===p.accountId);return a?`${a.displayName} · ${a.platform} · ${a.accountKind}`:'Destination unavailable';})()}</span><span>{stateLabel[p.state]}</span></div><p className="whitespace-pre-wrap text-sm leading-relaxed">{p.text}</p>{recoveryMessage(p)&&<p role="status" className="text-sm text-muted-foreground">{recoveryMessage(p)}</p>}{p.images.length>0&&<ul aria-label="Attached images" className="text-sm text-muted-foreground">{p.images.map(image=><li key={`${image.assetId}:${image.version}`}><SocialImage assetId={image.assetId} version={image.version} alt={image.altText} onReady={()=>{m.previewReady.add(`${p.postId}:${p.revision}:${image.assetId}:${image.version}`);touch();}}/>{image.altText} · image version {image.version}</li>)}</ul>}{p.publishAt&&<p className="text-xs text-muted-foreground">{new Intl.DateTimeFormat(undefined,{timeZone:p.zone,dateStyle:'medium',timeStyle:'short'}).format(new Date(p.publishAt))} · {p.zone}</p>}{['draft','failed'].includes(p.state)?<ManualHandoffPanel postId={p.postId} revision={p.revision}/>:null}<div className="flex gap-2">{['draft','failed','cancelled'].includes(p.state)&&<Button variant="outline" disabled={m.busy||m.pending!==null} onClick={()=>edit(p)}>Edit</Button>}{p.state==='draft'&&<Button disabled={m.busy||m.pending!==null||p.publishAt===null||p.images.some(image=>!m.previewReady.has(`${p.postId}:${p.revision}:${image.assetId}:${image.version}`))} onClick={()=>void run({action:'approve',postId:p.postId,expectedRevision:p.revision,commandId:crypto.randomUUID()})}>Approve &amp; schedule</Button>}{['approved','submitting','scheduled','unknown'].includes(p.state)&&<Button variant="outline" disabled={m.busy||m.pending!==null} onClick={()=>void run({action:'cancel',postId:p.postId,expectedRevision:p.revision,commandId:crypto.randomUUID()})}>Cancel schedule</Button>}</div></article>)}</div>}
 </section>;
}
